["本週運勢"]
inclusive = ["本週運勢"]
exclusive = []
category = ["#節目"]

["Meditation"]
inclusive = ["Meditation"]
exclusive = []
category = ["#節目"]

["丹公解夢"]
inclusive = ["丹公解夢"]
exclusive = []
category = ["#節目"]

["冥想"]
inclusive = ["冥想","Meditation"]
exclusive = []
category = ["方法"]

["水晶"]
inclusive = ["水晶"]
exclusive = []
category = ["方法"]

["靈魂契約"]
inclusive = ["靈魂契約"]
exclusive = []
category = ["方法"]

["許願"]
inclusive = ["許願"]
exclusive = []
category = ["方法"]

["生命靈數"]
inclusive = ["生命靈數"]
exclusive = []
category = ["方法"]

["星座"]
inclusive = ["星座"]
exclusive = []
category = ["方法"]

["五行"]
inclusive = ["五行"]
exclusive = []
category = ["方法"]

["塔羅牌"]
inclusive = ["塔羅"]
exclusive = []
category = ["方法"]

["守護天使"]
inclusive = ["守護天使"]
exclusive = []
category = ["靈體"]

["雙生火焰"]
inclusive = ["雙生火焰"]
exclusive = []
category = ["方法"]

["擴大療癒法"]
inclusive = ["擴大療癒法","擴療"]
exclusive = []
category = ["方法"]

["奇蹟"]
inclusive = ["奇蹟"]
exclusive = []
category = ["方法"]

["靈擺"]
inclusive = ["靈擺"]
exclusive = []
category = ["方法"]

["揚升"]
inclusive = ["揚升"]
exclusive = []
category = ["方法"]

["指導靈"]
inclusive = ["指導靈"]
exclusive = []
category = ["靈體"]

["高我"]
inclusive = ["高我"]
exclusive = []
category = ["靈體"]

["人類圖"]
inclusive = ["人類圖"]
exclusive = []
category = ["方法"]

["夢"]
inclusive = ["夢"]
exclusive = []
category = ["方法"]

["催眠"]
inclusive = ["催眠"]
exclusive = []
category = ["方法"]

["風水"]
inclusive = ["風水"]
exclusive = []
category = ["方法"]

["東方靈數"]
inclusive = ["東方靈數"]
exclusive = []
category = ["方法"]

["神仙雜貨殿"]
inclusive = ["神仙雜貨殿"]
exclusive = []
category = ["神仙雜貨殿"]

["算命"]
inclusive = ["命會不會越算越差"]
exclusive = []
category = ["方法"]

["桃花"]
inclusive = ["桃花"]
exclusive = []
category = ["關係"]

["姻緣"]
inclusive = ["姻緣"]
exclusive = []
category = ["關係"]

["財神"]
inclusive = ["財神"]
exclusive = []
category = ["靈體"]

["女神"]
inclusive = ["母娘"]
exclusive = []
category = ["靈體"]

["脈輪"]
inclusive = ["七脈輪","7脈輪"]
exclusive = []
category = ["方法"]

["黃金紀元"]
inclusive = ["黃金紀元","黃金世紀"]
exclusive = []
category = ["方法"]

["紫色火焰"]
inclusive = ["紫色火焰"]
exclusive = []
category = ["方法"]
