[spotify]
"EP209｜泰辣的🇪🇸巴塞隆納與🇵🇹里斯本之旅，居然跟老公當街上演分手擂台？！" = "https://open.spotify.com/episode/2lPbF06lNHfYoWWRUNdku1"
"EP208｜那那大師來了！被打還飛蛾撲火😱總是愛上不對的人，情路未免也太坎坷🥺" = "https://open.spotify.com/episode/3SpqqiqbxDkNJAMM0aqlds"
"EP208｜那那大師來了！被打還飛蛾撲火😱總是愛上不對的人，感情之路也太坎坷🥺" = "https://open.spotify.com/episode/3SpqqiqbxDkNJAMM0aqlds"
"EP207｜我們的恩人，陪伴瘋女人跨過心魔！TAG音樂劇導演、編劇來了！ft.小馬、姜杯" = "https://open.spotify.com/episode/0TaarhlL4x3zhrjdERpl9q"
"EP206｜母單27年終於穩交！爸爸竟然覺得難堪？！ft.泰妹Anya" = "https://open.spotify.com/episode/5VcNSTKkha9YM2aAhIAibL"
"週間節目｜說「辛苦了」也會惹怒人？婚禮竟然不能祝人幸福？｜姐妹潑辣死" = "https://open.spotify.com/episode/7xuRL6qLT4qv9kf8Kc2PGH"
"EP205｜Apple為了見閨蜜的英國之旅🇬🇧 早知道不要帶老公去了啦😩" = "https://open.spotify.com/episode/0DZXqOBi19gzS8N6q5qPms"
"EP204｜閒聊時間：Energy演唱會心得！把青春追回來了 + 近期流行追追追（這些流行語跟小物你聽過嗎？）" = "https://open.spotify.com/episode/4FxYol7oV63v2uEWE7rJag"
"EP203｜愛情診療室💌如果有一天我變得很可怕，請把我拋棄" = "https://open.spotify.com/episode/7MypBIGuv2lTFyEbE22iIX"
"EP202｜雷⚠️ 腦筋急轉彎2：你也有易焦慮體質嗎？來聊聊我們主控台是什麼情緒" = "https://open.spotify.com/episode/5ig53S8AWP14nFdwuHn5Ga"
"EP201｜閒聊時間 + 人為什麼長大後時間越過越快，你虛度光陰了嗎？" = "https://open.spotify.com/episode/67xnFSBbra16EjpMqr7QAg"
"EP200｜性愛診療室🔞對方沒有射就沒有結束！ft.摩摩渣渣不能說" = "https://open.spotify.com/episode/0JxGnXs1zaAid6kh4uvUjQ"
"EP199｜一天賠掉70萬！關韶文的投資理財之路！投資新手第一步怎麼做？" = "https://open.spotify.com/episode/7lBNZEco8ho5qIvWtVn9ec"
"EP198｜快樂有方法嗎？要怎麼感到心靈富足？（下集）" = "https://open.spotify.com/episode/125R5tGZzbf5GiKXGsiXh1"
"EP197｜性愛診療室🔞沒有自慰過，就無法體驗高潮嗎？ft.摩摩渣渣不能說" = "https://open.spotify.com/episode/6aQ3jsXiQtN3gNU82OjUD4"
"週間節目｜男同性戀想要什麼沒有？除了真愛｜射後不理 ＃爽就好了" = "https://open.spotify.com/episode/74GN9nvZHFfdQnIGVgbaai"
"EP196｜母胎單身26年，快來教教我怎麼談戀愛！ft.寶賤" = "https://open.spotify.com/episode/36m8lu4LstD6PmiLxLdmL5"
"EP195｜愛情診療室💌男友想跟異性好友單獨出國，是合理的嗎？" = "https://open.spotify.com/episode/6FM61RTVmKaqMwFtnI8MAk"
"EP194｜要怎麼感到心靈富足？你都做什麼事情讓自己開心？（上集）" = "https://open.spotify.com/episode/2buYt8CxYd1Xk7fhIrouYA"
"EP193｜江老師來了！聊老公聊到哭，她也是真正的瘋女人！" = "https://open.spotify.com/episode/2YiJ5qS3Y2hwlwLZKs9RHO"
"EP192｜苦命社畜變老闆的抓馬之路 ft. 尚恩" = "https://open.spotify.com/episode/4jez4zGX9LmNNfxYX9Hp4J"
"EP191｜不會吧！又想搬家了！" = "https://open.spotify.com/episode/2HaQ3umlztfcHrZHIGra1C"
"EP190｜愛情診療室💌 有這樣的男友請趕快分手！" = "https://open.spotify.com/episode/3ye1s8xYaUKQM4eckqABJz"
"EP189｜荒謬戀愛故事大集結！男友是雙重人格？交往三年都沒發現的秘密？" = "https://open.spotify.com/episode/0cXvB2TwbpAOW5ZczZYitz"
"EP188｜小吳來了！從見習網美到百萬YouTuber！從爆紅秘訣聊到牡羊男感情觀！（好豐富的一集）" = "https://open.spotify.com/episode/14uGw24VmuppmtqSczSmvC"
"EP187｜寶賤來了！校園主持得罪歌手有多糗？爆笑糗事一籮筐！！！" = "https://open.spotify.com/episode/7egvKPX48aZimUqRdXT7e0"
"EP186｜台灣人要不要放過諧音梗？不要！" = "https://open.spotify.com/episode/5HeapPTGFTWKfc6T3GKNYf"
"EP185｜直男們學起來！請這樣回覆你老婆！多年後再談「男友不娶我」" = "https://open.spotify.com/episode/3bHG79Yp0LwyNVBzc5Myu5"
"EP184｜網友投稿✉️ 在一起13年，能接受開放式關係嗎？最後一個投稿有彩蛋🤭一定要聽到最後！" = "https://open.spotify.com/episode/0dAxHKHcjmJoL5hDbKmll5"
"EP183｜千年一遇的鳥事特輯暨荒謬諧音大會！" = "https://open.spotify.com/episode/48Vp7ALUGvp2BRtm5wuiVp"
"EP182｜結婚以後老公就變了？！" = "https://open.spotify.com/episode/5vEW1gYL1ZTe1Ox4Cr5ggk"
"EP181｜過年大家還好嗎？Apple的第一次婚後過年初體驗😂 feat.阿該" = "https://open.spotify.com/episode/5fczOq5CNO9zCI1DQ98ymF"
"EP180｜怪人怪聞事件簿！邊騎車邊吃便當的同事！約會到一半跛腳的網友！你也遇過這樣的奇葩嗎？" = "https://open.spotify.com/episode/0QXxSKX5tV2jGbl6kE9b9N"
"EP179｜朋友能當一輩子嗎？交友前請詳閱使用手冊！ft.童話裡都是騙人的" = "https://open.spotify.com/episode/0jj7E9RSvXpSQsVFPYxCMM"
"EP178｜面試奇譚！老闆面試遇過哪些怪人？這些面試地雷你也中了嗎？ft.達菇" = "https://open.spotify.com/episode/2KgcroM8Ky1D2sKTtlKCUF"
"EP177｜歐娜來了！怎麼熬過苦瓜人生？減重的契機居然是被男友逼？" = "https://open.spotify.com/episode/4N5WTnOwNlkSoYMZyOUVq2"
"EP176｜愛情診療室💌失去了最愛的人，要怎麼走出來？" = "https://open.spotify.com/episode/5AlG690IZ52wqhKeS06ih2"
"EP175｜李千娜來了！19歲結婚生子，38歲再次遇見真愛❤️ 到底要怎麼做自己？有標準答案嗎？" = "https://open.spotify.com/episode/3MH5UBxuolWRdEyAfc2E4O"
"EP174｜美食地圖：跨七縣市共13家喫茶咖啡店推薦！過年走春可以去！" = "https://open.spotify.com/episode/38O8zAk65P8c3YEceGt6y5"
"EP173｜Apple婚後心得，G蛋布丁再度熱戀期❤️" = "https://open.spotify.com/episode/4SLynsy1JzbeXZ4YZanATY"
"EP172｜愛情診療室💌 老公和初戀女友偷約會，這樣算出軌嗎？" = "https://open.spotify.com/episode/1jRuzvXFWQBqRV7HSPMqOd"
"EP171｜情侶同居注意事項！天天相處怕吵架怎麼辦？" = "https://open.spotify.com/episode/5Qr3ciRq59MuYKZwmh8j1x"
"EP170｜搬家是很痛苦的！" = "https://open.spotify.com/episode/1CzCb4faFE9m0ZwqUZjjaW"
"EP169｜年末回顧與新年新希望🌟 去年許的有一一實現嗎？" = "https://open.spotify.com/episode/4dF8Z7cMAvu3xd12xsziCp"
"EP168｜當父母到底有多辛苦？遇到惡魔小孩怎麼辦😫" = "https://open.spotify.com/episode/6Rpwn32am6rIf9w3mK5Zem"
"EP167｜白目🙄" = "https://open.spotify.com/episode/3BLykz4vjlYsEhYiaFSL4B"
"EP166｜Apple和布丁正式分居！為什麼要搬家？當了五年室友的心路歷程🥹" = "https://open.spotify.com/episode/5xeVBfi5ezNeGz2ryialDW"
"EP165｜朋友變室友如何不吵架！泰辣跟阿該的室友特輯！ft.閨蜜該該叫" = "https://open.spotify.com/episode/1pJNT0tWLuv7GYZAKV0Cr2"
"EP164｜曼谷旅遊口袋名單推薦！阿該的各種奇特豔遇？！ ft.閨蜜該該叫" = "https://open.spotify.com/episode/3t1kh2oHXTUGwNwMyL27PF"
"EP163｜裝修鬼故事！苦主現身說法：裝潢遇到惡劣工班，付了錢就落跑擺爛不做！（N）" = "https://open.spotify.com/episode/6ig6l0AJfigD7oh6z5y1F0"
"EP162｜愛情診療室💌 婚後被逼生小孩，公婆說沒生會被祖先詛咒？！" = "https://open.spotify.com/episode/3FFlygO0GnVi6SzRzaCXUB"
"EP161｜職場診療室✉️臭臉同事真討厭！想離職去創業但大家都反對！" = "https://open.spotify.com/episode/3gxqdmNq0m4iQw2pABJiIL"
"EP160｜短影音才是王道！看YouTube長影片已經不流行了？！" = "https://open.spotify.com/episode/1VtisUMLbyLvtvDMHwLxLl"
