# Add your own tag to each episode

[08c00014]
name = "EP17 天生歌乩｜在原唱面前挑戰《陪妳過假日》 feat. 9m88、東區德、聶小聶、RayRay、怡岑"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/d897917f-4bf9-4c8e-be79-96ff2089a708/rssFileVip.mp3?timestamp=1655154058272"
apple = "https://podcasts.apple.com/tw/podcast/ep17-%E5%A4%A9%E7%94%9F%E6%AD%8C%E4%B9%A9-%E5%9C%A8%E5%8E%9F%E5%94%B1%E9%9D%A2%E5%89%8D%E6%8C%91%E6%88%B0-%E9%99%AA%E5%A6%B3%E9%81%8E%E5%81%87%E6%97%A5-feat-9m88-%E6%9D%B1%E5%8D%80%E5%BE%B7-%E8%81%B6%E5%B0%8F%E8%81%B6-rayray-%E6%80%A1%E5%B2%91/id1542576888?i=1000520420414"
spotify = "https://open.spotify.com/episode/7fTlHrSe6LNSCABFTGYshQ"
image = "96d5b0dbe2c6191a46b446d6d0765328324957ce488abb337fa84b93d2e10770"
description = "#零捌歐北共 Podcast第17 集\n這次有幸受到大港開唱邀請，有機會在熱情的高雄出外景錄歐北共！\n還很幸運的請到了爵士女伶—9m88來到現場，希望她沒有被我們這群瘋子嚇到😍😍😍\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/b8jAq2vHaCM\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-9m88⭐️\nhttps://www.facebook.com/9m88baba\n\n⭐️特別來賓-東區德⭐️\nhttps://www.facebook.com/DongQuDer/\n\n⭐️特別來賓-聶小聶⭐️\nhttps://www.facebook.com/Mr.two1111\n\n⭐️特別來賓-RayRay⭐️\nhttps://www.facebook.com/thisisrayray\n\n⭐️特別來賓-怡岑⭐️\nhttps://www.facebook.com/andrewpatanie"
names = ["EP17 天生歌乩｜在原唱面前挑戰《陪妳過假日》 feat. 9m88、東區德、聶小聶、RayRay、怡岑"]
tag = ["May 2021", "2021", "瑞恩", "東區德", "怡岑", "9m88", "小聶"]
category = ["喜劇演員", "喜劇演員", "喜劇演員", "來賓", "來賓"]

[08c00013]
name = "EP16 08CUMEDY｜床上的Dirty Talk怎麼說 feat.欣西亞、RayRay"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/af7f669e-fe4b-47c0-a49b-9129f0186c3f/rssFileVip.mp3?timestamp=1655154019933"
apple = "https://podcasts.apple.com/tw/podcast/ep16-08cumedy-%E5%BA%8A%E4%B8%8A%E7%9A%84dirty-talk%E6%80%8E%E9%BA%BC%E8%AA%AA-feat-%E6%AC%A3%E8%A5%BF%E4%BA%9E-rayray/id1542576888?i=1000517209494"
spotify = "https://open.spotify.com/episode/2WAvtDhzuYewNqLQDRK4R1"
image = "37437a256c5f488b074848f02c3f00fee4eb261b3e2bbfafc66892f5350dad45"
description = "這集邀請到性諮詢師-欣西亞，以及女同天菜 RayRay\n來聊聊現在男女的性事煩惱！\n瘋狂開車的一集不知道各位招架得住嗎：）\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/5_utO9hIwHE\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-欣西亞⭐️\nhttps://www.facebook.com/americavstaiwan\n\n⭐️特別來賓-RayRay⭐️\nhttps://www.facebook.com/thisisrayray"
names = ["EP16 08CUMEDY｜床上的Dirty Talk怎麼說 feat.欣西亞、RayRay"]
tag = ["Apr 2021", "2021", "瑞恩", "欣西亞"]
category = ["喜劇演員", "來賓"]

[08c00012]
name = "EP15 The KK Sh!t feat. 百靈果-凱莉與Ken"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/1078f0f5-8aca-4b9b-9acb-c62f8da73345/rssFileVip.mp3?timestamp=1655154033887"
apple = "https://podcasts.apple.com/tw/podcast/ep15-the-kk-sh-t-feat-%E7%99%BE%E9%9D%88%E6%9E%9C-%E5%87%B1%E8%8E%89%E8%88%87ken/id1542576888?i=1000514849268"
spotify = "https://open.spotify.com/episode/1kGvr5xHqWdPhvdayUGKrr"
image = "f54affef0c7c4f736bc736234b35f3411a2ca908625db357628e6012625ae3e0"
description = "沒錯KKSH!T又來了！今天邀請百靈果來跟我們聊聊，百靈果在成為百萬Podcaster前的故事～\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/NxEC-6K-ZWc\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️特別來賓-百靈果兩位主持⭐️\nhttps://www.facebook.com/puppydailynews"
names = ["EP15 The KK Sh!t feat. 百靈果-凱莉與Ken"]
tag = ["Mar 2021", "2021", "凱莉", "Ken", "The KK Sh!t"]
category = ["喜劇演員", "喜劇演員", "#節目系列"]

[08c00011]
name = "EP14 貼近你的星｜水星逆行到底是什麼情況？feat. 安格斯、酸酸"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/0a4f4b51-3f7c-406f-8827-81e52a14a59d/rssFileVip.mp3?timestamp=1655154025062"
apple = "https://podcasts.apple.com/tw/podcast/ep14-%E8%B2%BC%E8%BF%91%E4%BD%A0%E7%9A%84%E6%98%9F-%E6%B0%B4%E6%98%9F%E9%80%86%E8%A1%8C%E5%88%B0%E5%BA%95%E6%98%AF%E4%BB%80%E9%BA%BC%E6%83%85%E6%B3%81-feat-%E5%AE%89%E6%A0%BC%E6%96%AF-%E9%85%B8%E9%85%B8/id1542576888?i=1000513393296"
spotify = "https://open.spotify.com/episode/0XnKvEQDcVwoSMhrW3sybW"
image = "6d959c581fbdd7753943ba70d78ad534aa27cac793f989aacf7fd961ab4c06d6"
description = "2021新的一年，過完年後新的一集歐北共我們來聊星座！\n這次找來了星星教授 安格斯老師，以及星座迷 酸酸\n和不相信星座的凱莉和馬克，會擦出什麼樣的火花呢 (˶‾᷄ ⁻̫ ‾᷅˵)\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/947qFg9PZ8A\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-安格斯⭐️\nhttps://www.facebook.com/Writer.angus\n\n⭐️特別來賓-酸酸⭐️\nhttps://www.facebook.com/AcidComedy"
names = ["EP14 貼近你的星｜水星逆行到底是什麼情況？feat. 安格斯、酸酸"]
tag = ["Mar 2021", "2021", "酸酸", "安格斯"]
category = ["喜劇演員", "來賓"]

[08c00010]
name = "EP10 旅伴還是旅絆｜你的旅伴是個雷包該怎麼辦？！ feat.欸你這週要幹嘛"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/731f1dc7-aa37-4733-b5e3-3530b13f4a70/rssFileVip.mp3?timestamp=1655154026796"
apple = "https://podcasts.apple.com/tw/podcast/ep10-%E6%97%85%E4%BC%B4%E9%82%84%E6%98%AF%E6%97%85%E7%B5%86-%E4%BD%A0%E7%9A%84%E6%97%85%E4%BC%B4%E6%98%AF%E5%80%8B%E9%9B%B7%E5%8C%85%E8%A9%B2%E6%80%8E%E9%BA%BC%E8%BE%A6-feat-%E6%AC%B8%E4%BD%A0%E9%80%99%E9%80%B1%E8%A6%81%E5%B9%B9%E5%98%9B/id1542576888?i=1000507557867"
spotify = "https://open.spotify.com/episode/1sTDRpi6ZsVNFCtHnKjFFK"
image = "2686dc25b84df1d3796285565fd24ae06955c051e7434028409d4c8c15313da2"
description = "好的旅伴帶你上天堂，不好的旅伴只會讓你回國之後就想一生拒絕往來!\n凱莉教你如何對付豬隊友!但不見得受用….\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/geDyTJuAi0I\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-欸你這週要幹嘛⭐️\nhttps://reurl.cc/1gZVrD"
names = ["EP10 旅伴還是旅絆｜你的旅伴是個雷包該怎麼辦？！ feat.欸你這週要幹嘛"]
tag = ["Feb 2021", "2021"]
category = []

[08c00009]
name = "EP9 戀之呼吸｜學生時期在暗處...印象深刻的戀愛 feat.賀瓏、大鵰博士、東區德"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/f4a99fc1-4920-4b89-b814-4853e05a99ca/rssFileVip.mp3?timestamp=1655154028215"
apple = "https://podcasts.apple.com/tw/podcast/ep9-%E6%88%80%E4%B9%8B%E5%91%BC%E5%90%B8-%E5%AD%B8%E7%94%9F%E6%99%82%E6%9C%9F%E5%9C%A8%E6%9A%97%E8%99%95-%E5%8D%B0%E8%B1%A1%E6%B7%B1%E5%88%BB%E7%9A%84%E6%88%80%E6%84%9B-feat-%E8%B3%80%E7%93%8F-%E5%A4%A7%E9%B5%B0%E5%8D%9A%E5%A3%AB-%E6%9D%B1%E5%8D%80%E5%BE%B7/id1542576888?i=1000506719158"
spotify = "https://open.spotify.com/episode/5hRTf3mErZMJ74MkY9OsC7"
image = "352aa070089d86de29651c236fab32350142bb5eb5daea1b691c2996827f0ee8"
description = "賀瓏爆料戀愛特殊癖好，第一次性幻想的對象竟然是小病毒!\n校園戀愛最隱蔽刺激的約會地點…最後一個也太誇張了吧!\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/DUoDUiMXQys\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-賀瓏⭐️\nhttps://www.facebook.com/horlunghello\n\n⭐️特別來賓-大鵰博士⭐️\nhttps://www.facebook.com/drdiao\n\n⭐️特別來賓-東區德⭐️\nhttps://www.facebook.com/DongQuDer"
names = ["EP9 戀之呼吸｜學生時期在暗處...印象深刻的戀愛 feat.賀瓏、大鵰博士、東區德"]
tag = ["Jan 2021", "2021", "東區德", "賀瓏", "大鵰博士"]
category = ["喜劇演員", "喜劇演員", "喜劇演員"]

[08c00008]
name = "EP8 網紅吸睛大法｜Youtuber真的好難當！ feat.酷炫、怡岑、么么"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/12e9087d-0837-4ea4-9476-5b1656a9bfab/rssFileVip.mp3?timestamp=1655154020241"
spotify = "https://open.spotify.com/episode/2pOi8pUXAr8Yzq0rxmw5i6"
image = "2451b70d916ab6d0ece2aa2a70cdee907f76d304d57c7254b3399fbd6c70ce17"
description = "在這個人人都可以成為Youtuber的時代，要如何吸引到觀眾的眼球呢？\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/QHCitUhLYEA\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️特別來賓-莊酷炫(小苦苓)⭐️\nhttps://reurl.cc/g88x44\n\n⭐️特別來賓-么么巴豆夭⭐️\nhttps://www.facebook.com/wasiyaoyao\n\n⭐️特別來賓-移動岑寶 怡岑⭐️\nhttps://www.facebook.com/andrewpatanie"
names = ["EP8 網紅吸睛大法｜Youtuber真的好難當！ feat.酷炫、怡岑、么么"]
tag = ["Jan 2021", "2021", "么么", "怡岑"]
category = ["喜劇演員", "喜劇演員"]

[08c00007]
name = "EP7 兵員歷險記｜當四個月的兵都在做什麼？ feat.黃大謙、彥儒、么么"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/6f850eec-133f-4f74-9b95-14fe30b276df/rssFileVip.mp3?timestamp=1655154029305"
spotify = "https://open.spotify.com/episode/2AiP6j0aEdgSG1eQlGVcWm"
image = "46444b7cece1f1783bcddce808fd92e85d87595e464c091af3ae006ce48ad93d"
description = "人生如戲，做兵就像演一場大戲…單兵戰鬥教練最難的是記住台詞跟憋笑？\n現場有退伍八年的老兵、只當四個月的爽兵、沒當過兵、以及替代役，聊一聊當兵都在做什麼？！\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/YNV9V70PAqk\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️特別來賓-黃大謙⭐️\nhttps://www.facebook.com/HuangDaChien\n\n⭐️特別來賓-厭儒⭐️\nhttps://www.facebook.com/YenRuHateWorld\n\n⭐️特別來賓-么么⭐️\nhttps://www.facebook.com/wasiyaoyao"
names = ["EP7 兵員歷險記｜當四個月的兵都在做什麼？ feat.黃大謙、彥儒、么么"]
tag = ["Jan 2021", "2021", "么么", "彥儒", "黃大謙"]
category = ["喜劇演員", "來賓", "來賓"]

[08c00006]
name = "EP6 姻人而異｜結婚前應該先同居嗎？ feat.黃小胖、歐耶、艾董"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/03bfc88e-db6d-4d37-9b33-2e82f5f0c357/rssFileVip.mp3?timestamp=1655154025361"
spotify = "https://open.spotify.com/episode/5D5tpcLKqN6UOJz1gc8jKq"
image = "83419dc088c4caec2773803f555c7fc4411cebe37b26acc5dfc5fbf40fbb4487"
description = "這集有幸邀到資深脫口秀演員a.k.a.卡米地人生勝利組——歐耶、黃小胖以及艾董來聊聊婚姻！\n怎麼感覺每個人都活在悔恨之中？？？\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/4doBx-zb528\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-新激梗社歐耶⭐️\nhttps://www.facebook.com/ngclub99\n\n⭐️特別來賓-黃小胖⭐️\nhttps://www.facebook.com/ponponyellow\n\n⭐️特別來賓-艾董⭐️\nhttps://www.facebook.com/Comedy.I.am.Mr.E"
names = ["EP6 姻人而異｜結婚前應該先同居嗎？ feat.黃小胖、歐耶、艾董"]
tag = ["Jan 2021", "2021", "黃小胖", "艾董"]
category = ["喜劇演員", "喜劇演員"]

[08c00005]
name = "EP5 「侍」寵而驕！你是狗派還是貓派？寵物溝通是真的嗎？ feat.一隻阿圓、城寶"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/c5801bd9-0055-46ff-a5d0-661f7be03168/rssFileVip.mp3?timestamp=1655154026667"
spotify = "https://open.spotify.com/episode/5bvFKHQimnvQ2GU39oLNgq"
image = "33b25bc4efe467e258bb59284d20f23f5e10e3414f1d9f1342e4cb0520f02039"
description = "你是否曾幾何時覺得自己比狗還累…不!你錯了!!狗都沒你那麼累!\n寵物不再只是寵物，甚至超越兒女般的家人關係\n\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/QBaj2ZYfybI\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐️節目主持人黃豪平⭐️\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐️固定班底-馬克吐司⭐️\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐️固定班底-凱莉⭐️\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐️特別來賓-一隻阿圓⭐️\nhttps://www.facebook.com/nanciaociao\n\n⭐️特別來賓-成軍三分鐘城寶⭐️\nhttps://www.facebook.com/Chenggin3"
names = ["EP5 「侍」寵而驕！你是狗派還是貓派？寵物溝通是真的嗎？ feat.一隻阿圓、城寶"]
tag = ["Dec 2020", "2020", "一隻阿圓", "城寶"]
category = ["來賓", "來賓"]

[08c00004]
name = "EP4 時尚玩家｜那些你不懂的穿搭 feat.安安邊緣子 阿民、大可愛"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/f709b8a7-d1be-4b2f-8aa1-adf9363f643e/rssFileVip.mp3?timestamp=1655154036703"
spotify = "https://open.spotify.com/episode/33Rixi4QfYqGizYZP8As8B"
image = "064ad5d107c708bf40ba94721cf4f5800f7eed1a8237e93131dd76e0921db2d0"
description = "\n"
names = ["EP4 時尚玩家｜那些你不懂的穿搭 feat.安安邊緣子 阿民、大可愛"]
tag = ["Dec 2020", "2020", "大可愛", "安安邊緣子", "阿民"]
category = ["喜劇演員", "來賓", "來賓"]

[08c00003]
name = "EP3 鬼月都市傳說｜遇到好兄弟的經驗 feat.嚎哮排演"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/51f92679-77e0-4685-b531-3c2720ba79e0/rssFileVip.mp3?timestamp=1655154024728"
spotify = "https://open.spotify.com/episode/0bn6gU1u13hxB6dCMSfY0h"
image = "e05ab259c8c81dca56a219eac59c038310a79eeefbd03abc2b7b280d846a8a6a"
description = "第三集邀請嚎哮排演來聊「鬼月的禁忌」\n其中一項是不能講鬼故事，因為鬼會來湊熱鬧，\n但這群人根本不能講鬼故事吧！講幾句就歪樓！\n歪到連鬼都不想來聽了XXXD\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/6X1A38Y5uCQ\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐節目主持人黃豪平⭐\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐固定班底-馬克吐司⭐\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐固定班底-凱莉⭐\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐特別來賓-嚎哮排演⭐\nhttps://www.facebook.com/HAOxHSIAO\n\n\n"
names = ["EP3 鬼月都市傳說｜遇到好兄弟的經驗 feat.嚎哮排演"]
tag = ["Dec 2020", "2020"]
category = []

[08c00002]
name = "EP2 咩噗的愛情｜網路交友渣男渣女經驗談 feat.涵冷娜、東區德"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/ba6ef291-c242-408a-8cec-ac5b410d4e86/rssFileVip.mp3?timestamp=1655154031012"
spotify = "https://open.spotify.com/episode/0WFDyH1EL5KYZGx6WTdWSO"
image = "d9b203e5b1759388a0111e9d3ba719247c6bcdc78fd50856691981b62fe4bdd3"
description = "這集邀請到脫口秀界循利寧—東區德！\n和全台最美的早餐店阿姨—涵冷娜！\n以感情為主題，大家各自講述自己的愛情觀\n只是到最後全變成爆料大會：）\n\n🎤想看會動的可以在YouTube頻道上收看！\nhttps://youtu.be/QezAZ9M6Ees\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐節目主持人黃豪平⭐\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐固定班底-馬克吐司⭐\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐固定班底-凱莉⭐\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐特別來賓-東區德⭐\nhttps://www.facebook.com/DongQuDer\n\n⭐特別來賓-涵冷娜⭐\nhttps://www.facebook.com/Cold.Na\n\n"
names = ["EP2 咩噗的愛情｜網路交友渣男渣女經驗談 feat.涵冷娜、東區德"]
tag = ["Dec 2020", "2020", "東區德"]
category = ["喜劇演員"]

[08c00001]
name = "EP1 工不應求｜新鮮人求職秘訣大公開！老闆在履歷上最關注的是... feat呱吉、曹小歐"
feed = "https://chtbl.com/track/GEA7F2/rss.soundon.fm/rssf/61b793e3-6ed9-405a-bea1-566679b12d3d/feedurl/ad01b4bb-4735-4c22-be77-3eff88f989b5/rssFileVip.mp3?timestamp=1655154049665"
spotify = "https://open.spotify.com/episode/4QDO9Sqfpem6HFmhcClwuu"
image = "98ce98253a0933e0ec8ff7e91b0cfc30715372f58a1ce32e4e22433e22ca6f9b"
description = "首集大來賓是上班不要看的—呱吉、曹小歐！\n人民的公僕呱吉\n竟然做過人體模特兒！！！\n\n究竟新鮮人該如何找工作呢？\n這些人來傳授求職的秘訣囉～～～\n（不一定可以參考）\n\n🎤在這裡可以看到呱吉履歷表的照片！\nhttps://youtu.be/syBmEQ2CDhc\n\n「零捌卡好笑」YouTube 官方平台\nhttps://reurl.cc/x0oaGV\n「零捌卡好笑」Facebook 粉絲專頁\nhttps://www.facebook.com/08comedy\n「零捌卡好笑」Instagram\nhttps://www.instagram.com/08comedy/\n\n⭐節目主持人黃豪平⭐\nhttps://www.facebook.com/sayhellotoping\n「零負評」金鐘紅毯主持人\n\n⭐固定班底-馬克吐司⭐\nhttps://www.facebook.com/markloveliz\n資深單口喜劇演員\n\n⭐固定班底-凱莉⭐\nhttps://www.facebook.com/kyliesquats\n知名Podcast《百靈果》教主\n\n⭐特別來賓-呱吉⭐\nhttps://www.facebook.com/froggychiu\n\n⭐特別來賓-曹小歐⭐\nhttps://www.facebook.com/otis5hundredtsao\n\n\n"
names = ["EP1 工不應求｜新鮮人求職秘訣大公開！老闆在履歷上最關注的是... feat呱吉、曹小歐"]
tag = ["Nov 2020", "2020", "小歐", "呱吉"]
category = ["喜劇演員", "喜劇演員"]
