"EP1 工不應求｜新鮮人求職秘訣大公開！老闆在履歷上最關注的是... feat呱吉、曹小歐" = "extra"
"EP2 咩噗的愛情｜網路交友渣男渣女經驗談 feat.涵冷娜、東區德" = "extra"
"EP3 鬼月都市傳說｜遇到好兄弟的經驗 feat.嚎哮排演" = "extra"
"EP4 時尚玩家｜那些你不懂的穿搭 feat.安安邊緣子 阿民、大可愛" = "extra"
"EP5 「侍」寵而驕！你是狗派還是貓派？寵物溝通是真的嗎？ feat.一隻阿圓、城寶" = "extra"
"EP6 姻人而異｜結婚前應該先同居嗎？ feat.黃小胖、歐耶、艾董" = "extra"
"EP7 兵員歷險記｜當四個月的兵都在做什麼？ feat.黃大謙、彥儒、么么" = "extra"
"EP8 網紅吸睛大法｜Youtuber真的好難當！ feat.酷炫、怡岑、么么" = "extra"
"EP9 戀之呼吸｜學生時期在暗處...印象深刻的戀愛 feat.賀瓏、大鵰博士、東區德" = "extra"
"EP10 旅伴還是旅絆｜你的旅伴是個雷包該怎麼辦？！ feat.欸你這週要幹嘛" = "extra"
"EP14 貼近你的星｜水星逆行到底是什麼情況？feat. 安格斯、酸酸" = "extra"
"EP15 The KK Sh!t feat. 百靈果-凱莉與Ken" = "extra"
"EP16 08CUMEDY｜床上的Dirty Talk怎麼說 feat.欣西亞、RayRay" = "extra"
"EP17 天生歌乩｜在原唱面前挑戰《陪妳過假日》 feat. 9m88、東區德、聶小聶、RayRay、怡岑" = "extra"
"如何在娃娃機店把四隻玩偶都全夾出來？｜殘影狂龍｜【2022卡米地站立喜劇爭霸賽】決賽遺珠" = "extra"
"當口吃困擾遇上各種生活難題！｜JH｜【2022卡米地站立喜劇爭霸賽】決賽遺珠" = "extra"
"「等一下」到底是要等幾下？！｜藍恩｜【2022卡米地站立喜劇爭霸賽】決賽冠軍" = "extra"
"【2022卡米地站立喜劇爭霸賽】敗部復活（下）｜參賽者：唐墨、硬硬、鐵鋁、巴斯、巨陽尼｜主持人：佳諭" = "extra"
"【2022卡米地站立喜劇爭霸賽】敗部復活（上）｜參賽者：LILI講、醋咪、小蘇、黑黑、麋鹿、下水彼得｜主持人：佳諭" = "extra"
"【一飲泯恩仇】黃豪平自曝XX太小 沒有玻璃心？！本來是要來解決心魔的，怎麼好像越解決心魔越多？" = "extra"
"【一飲泯恩仇】喜劇全明星翻唱 你怎麼能不愛上KK Bar" = "extra"
"【2023卡米地站立喜劇爭霸賽】A場（上）｜參賽者：摩洛哥可可、穎珍、哈達、LILI講、光頭哥Evan、小蘇｜評審：酸酸、馬克吐司｜主持人：瑞恩" = "extra"
"【2023卡米地站立喜劇爭霸賽】A場（下）｜參賽者：Sunny、六塊錢、Birdy、硬硬、Jimmy Stone、醋咪｜評審：酸酸、馬克吐司｜主持人：瑞恩" = "extra"
"【2023卡米地站立喜劇爭霸賽】B場（上）｜參賽者：巨陽尼、駒哥、俊彥、佳偉、Boss、啊真｜評審：歐耶、大可愛｜主持人：阿海" = "extra"
"【2023卡米地站立喜劇爭霸賽】B場（下）｜參賽者：小馬、下水彼得、懿霽、GE、KJ、Ryan｜評審：歐耶、大可愛｜主持人：阿海" = "extra"
"【2023卡米地站立喜劇爭霸賽】C場（上）｜參賽者：阿舜順、權樂、令潔、巴斯、可樂、阿育｜評審：龍哥、艾董｜主持人：招弟" = "extra"
"【2023卡米地站立喜劇爭霸賽】C場（下）｜參賽者：鐵鋁、洪阿花、阿太老師、品客大叔、梅森、樂樂法利｜評審：龍哥、艾董｜主持人：招弟" = "extra"
"【零捌卡好笑】瑋德求你不要結婚" = "extra"
"【零捌卡好笑】《問題兒 Outlier》巴斯2023單口喜劇專場｜全片特輯" = "extra"
"【再乾一杯】壯歐漫才即興爆改風獅爺 超強喜劇陣容降臨KK Bar" = "extra"
"【2023卡米地站立喜劇爭霸賽】決賽（上）｜參賽者：梅森、阿太老師、阿育、Boss、GE、啊真、Birdy、醋咪、LiLi講｜評審：博恩、壯壯、張碩修Social、眼肉芽｜主持人：賀瓏" = "extra"
"【2023卡米地站立喜劇爭霸賽】決賽（下）｜參賽者：梅森、阿太老師、阿育、Boss、GE、啊真、Birdy、醋咪、LiLi講｜評審：博恩、壯壯、張碩修Social、眼肉芽｜主持人：賀瓏" = "extra"
