"【2023卡米地站立喜劇爭霸賽】B場（下）｜參賽者：小馬、下水彼得、懿霽、GE、KJ、Ryan｜評審：歐耶、大可愛｜主持人：阿海" = "extra"
"【2023卡米地站立喜劇爭霸賽】C場（上）｜參賽者：阿舜順、權樂、令潔、巴斯、可樂、阿育｜評審：龍哥、艾董｜主持人：招弟" = "extra"
"【2023卡米地站立喜劇爭霸賽】C場（下）｜參賽者：鐵鋁、洪阿花、阿太老師、品客大叔、梅森、樂樂法利｜評審：龍哥、艾董｜主持人：招弟" = "extra"
"【零捌卡好笑】瑋德求你不要結婚" = "extra"
"【零捌卡好笑】《問題兒 Outlier》巴斯2023單口喜劇專場｜全片特輯" = "extra"
"【再乾一杯】壯歐漫才即興爆改風獅爺 超強喜劇陣容降臨KK Bar" = "extra"
"【2023卡米地站立喜劇爭霸賽】決賽（上）｜參賽者：梅森、阿太老師、阿育、Boss、GE、啊真、Birdy、醋咪、LiLi講｜評審：博恩、壯壯、張碩修Social、眼肉芽｜主持人：賀瓏" = "extra"
"【2023卡米地站立喜劇爭霸賽】決賽（下）｜參賽者：梅森、阿太老師、阿育、Boss、GE、啊真、Birdy、醋咪、LiLi講｜評審：博恩、壯壯、張碩修Social、眼肉芽｜主持人：賀瓏" = "extra"
"2024 台北喜劇節形象影片" = "extra"
"【零捌卡好笑】權樂：單口喜劇第一場專場全片" = "extra"
"【零捌卡好笑】阿舜順專場：巷口那個喜劇演員" = "extra"
"【2024卡米地站立喜劇爭霸賽】初賽A場台北 主持：么么 評審：歐耶、微笑丹尼 參賽者：Jimmy Stone、黑黑、醋咪、帥哥欣霖、公慶、祐先、Lucy、山石、FOHER、Sam" = "extra"
"【2024卡米地站立喜劇爭霸賽】初賽B場台中 11/29 五 8pm 主持：佳諭 評審：龍哥、馬克吐司 參賽者：阿綸 aka 正常水電、貝克書、旗魚、余恩、鐵鋁、巴斯、懿霽、巨陽尼、翰雅、林肯" = "extra"
"【2024卡米地站立喜劇爭霸賽】初賽C場高雄 11/30 六 7pm 主持：GE 評審：壯壯、阿海 參賽者：跩姬、康普臉、姸慧、Ryan、寬仔、佳偉、俊彥、竣喭、致葦、下水彼得" = "extra"
"【2024卡米地站立喜劇爭霸賽】初賽D場台北 12/1 日 主持：曹小歐 評審：大可愛. 黃逸豪 參賽者：阿檀叔叔、阿包、漢娜Hannah、威弟、皓宇、余胖、光頭哥Evan、傑森、蘇郁智、貓兵衛" = "extra"
"【權樂紀念專場】腦洞大開 feat 13位演員" = "extra"
"【天殘紀念影像】還有第七人-台女與處男的魚菜共生" = "extra"
"【天殘紀念影像】沒雞雞的不羈夜-歡樂教學" = "extra"
