hsd00001 = ["valuen"]
hsd00002 = ["valuen"]
hsd00003 = ["valuen"]
hsd00004 = ["valuen"]
hsd00005 = ["valuen"]
hsd00006 = ["valuen"]
hsd00007 = ["valuen"]
hsd00008 = ["valuen"]
hsd00009 = ["valuen"]
hsd00010 = ["valuen"]
hsd00011 = ["valuen"]
hsd00012 = ["valuen"]
hsd00013 = ["valuen"]
hsd00014 = ["valuen"]
hsd00015 = ["valuen"]
hsd00016 = ["valuen"]
hsd00017 = ["valuen"]
hsd00018 = ["valuen"]
hsd00019 = ["valuen"]
hsd00020 = ["valuen"]
hsd00021 = ["valuen"]
hsd00022 = ["valuen"]
hsd00023 = ["valuen"]
hsd00024 = ["valuen"]
hsd00025 = ["valuen"]
hsd00026 = ["valuen"]
hsd00027 = ["valuen"]
hsd00028 = ["valuen"]
hsd00029 = ["valuen"]
hsd00030 = ["valuen"]
hsd00031 = ["valuen"]
hsd00032 = ["valuen"]
hsd00033 = ["valuen"]
hsd00034 = ["valuen"]
hsd00035 = ["valuen"]
hsd00036 = ["valuen"]
hsd00037 = ["valuen"]
hsd00038 = ["valuen"]
hsd00039 = ["valuen"]
hsd00040 = ["valuen"]
hsd00041 = ["valuen"]
