"來當我們的觀眾吧｜涵酸電波 - 好難搞女孩SP8" = "extra"
"瑞恩的正能量，是站在世界中心對紫禁城的三千人企業大喊" = "extra"
"拜託跟我們合照然後標記我們，我們不怕這種打擾" = "extra"
"這樣到底有沒有禮貌｜涵酸電波 - 好難搞女孩SP9" = "extra"
"關於應援緞帶的小插曲，請好好珍惜別讓它溜走" = "extra"
"吵到差點取消加演？！｜涵酸電波 - 好難搞女孩SP10" = "extra"
"許願加演場有觀眾能在現場直接聯誼" = "extra"
"來聊大人的玩具！ft.紅犀牛品牌代表Jessie｜涵酸電波S3EP01" = "extra"
"潛意識的翻譯師幫我們看桃花！ft.塔羅師愛芙菈｜涵酸電波S3EP02" = "extra"
"跟長輩聊天聊到接手一間卡拉OK！ft.浪漫屋馬尾｜涵酸電波S3EP03" = "extra"
"挑戰問答！用36題愛上我們（上）｜涵酸電波S3EP04" = "extra"
"Yes And！沒劇本的表演好好玩 ft.勇氣即興 晏瑜｜涵酸電波S3EP05" = "extra"
"走心了啦！用36題愛上我們（下）｜涵酸電波S3EP06" = "extra"
"當演員通靈時！涵冷娜的拍片奇遇｜涵酸電波S3EP07" = "extra"
"伴著茶香動態冥想 ft.每日茶事 玫融｜涵酸電波S3EP08" = "extra"
