"工作上的機車人格｜涵酸電波 - 好難搞女孩SP2" = "extra"
"身體好像快壞掉了｜涵酸電波 - 好難搞女孩SP3" = "extra"
"吃東西怎麼可以隨便｜涵酸電波 - 好難搞女孩SP4" = "extra"
"酸酸的使用說明書｜涵酸電波 - 好難搞女孩SP5" = "extra"
"太過努力的涵冷娜｜涵酸電波 - 好難搞女孩SP6" = "extra"
"瑞恩的愛計較傳說｜涵酸電波 - 好難搞女孩SP7" = "extra"
"聽完這集還願意跟酸酸交往的，不管男人女人一定都是不得了的人" = "extra"
"不要再叫涵冷娜阿姨了！以下開放有創意的叫法" = "extra"
"來當我們的觀眾吧｜涵酸電波 - 好難搞女孩SP8" = "extra"
"瑞恩的正能量，是站在世界中心對紫禁城的三千人企業大喊" = "extra"
"拜託跟我們合照然後標記我們，我們不怕這種打擾" = "extra"
"這樣到底有沒有禮貌｜涵酸電波 - 好難搞女孩SP9" = "extra"
"關於應援緞帶的小插曲，請好好珍惜別讓它溜走" = "extra"
"吵到差點取消加演？！｜涵酸電波 - 好難搞女孩SP10" = "extra"
"許願加演場有觀眾能在現場直接聯誼" = "extra"
"來聊大人的玩具！ft.紅犀牛品牌代表Jessie｜涵酸電波S3EP01" = "extra"
"潛意識的翻譯師幫我們看桃花！ft.塔羅師愛芙菈｜涵酸電波S3EP02" = "extra"
"跟長輩聊天聊到接手一間卡拉OK！ft.浪漫屋馬尾｜涵酸電波S3EP03" = "extra"
"挑戰問答！用36題愛上我們｜涵酸電波S3EP04" = "extra"
"挑戰問答！用36題愛上我們（上）｜涵酸電波S3EP04" = "extra"
"Yes And！沒劇本的表演好好玩 ft.勇氣即興 晏瑜｜涵酸電波S3EP05" = "extra"
"走心了啦！用36題愛上我們（下）｜涵酸電波S3EP06" = "extra"
