"The KK Show - #00 一切的起源 - Podcast的馬力歐" = "blg00120"
"The KK Show - #01 國合會技術團 - Mario" = "blg00113"
"The KK Show - #02 香港脫口秀演員 - Tim Chen" = "blg00118"
"The KK Show - #161 @喬瑟夫 ChillSeph" = "blg00591"
"#Clips 再怎麼窮還是要待在劇團，什麼是漫才？ | The KK Show - #161 @喬瑟夫 ChillSeph" = "extra00591"
"#Clips 自己個性上特立獨行跟小時候的經驗沒關係 | The KK Show - #161 @喬瑟夫 ChillSeph" = "extra00591"
"#Clips 小時候的喬瑟夫沒有被性侵| The KK Show - #161 @喬瑟夫 ChillSeph" = "extra00591"
"【週二夜現場】會說唱的美國反賊 - 樂樂法利 @LeLe Farley" = "extra00592"
"【週二夜現場】樂樂法利來台灣！ @LeLe Farley" = "extra00592"
"掉到波蘭的飛彈到底是誰的？好大的一盤棋啊 #shorts" = "extra00593"
"#Clips 川普宣布選總統 民主黨雙手歡迎？| 百靈果News" = "extra00593"
"#Clips 波蘭飛彈事件要謹慎對待 | 百靈果News" = "extra00593"
"#Clips 習近平當全世界的面教訓加拿大 | 百靈果News" = "extra00593"
"The KK Show - #162 來福好事 - 龍哥" = "blg00594"
"#Clips 台中人聽到這個一定笑？ | The KK Show - #162 散盡家財做喜劇 - 龍哥" = "extra00594"
"#Clips 太年輕學喜劇會壞掉？ | The KK Show - #162 散盡家財做喜劇 - 龍哥" = "extra00594"
"￼如何￼ 3秒內跟台中人變成好朋友￼ #shorts" = "extra00594"
"【週二夜現場】喬瑟夫 & 博恩 @Stand up, Brian! 博恩站起來！ @喬瑟夫 ChillSeph" = "blg00595"
"博恩的鳥笑話 #shorts" = "extra00595"
"博恩覺得賀瓏是冗員？？#shorts" = "extra00595"
"Last night hundred of people gathered in Shanghai to call for RESIGNATION of Xi Jinping 上海聚集抗議" = "extra00596"
"11/27 上海法租界警察抓人 （螢幕錄製）" = "extra00596"
"習近平把加拿大總理當孫子訓話，旁邊翻譯都驚呆了 🤯#百靈果news #百靈果" = "extra00597"
"醫師與蘭嶼人面對死亡的態度｜KK Show - #149 離島醫生 - 黃京葦醫師" = "extra00558"
"剛到蘭嶼的文化衝擊｜KK Show - #149 離島醫生 - 黃京葦醫師" = "extra00558"
"打不過中國怎麼辦｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra00562"
"希望捐出來的30億要怎麼用｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra00562"
"為什麼要捐30億？｜KK Show - 150 拿出30億反共的男人 - #曹興誠" = "extra00562"
"講不到兩年辦專場被別人靠北？｜KK Show - #151 巴斯" = "extra00564"
"結婚多年後 凱莉重新認識老公｜KK Show - #151 巴斯" = "extra00564"
"五燈獎是在石器時代前還是之後？｜The KK Show - #152 #趙詠華＆#林俊逸" = "extra00567"
"歌手會被騙去飯局發展事業第二春？｜The KK Show - #152 趙詠華＆林俊逸" = "extra00567"
"(CC字幕) The KK Show - #153 逃出中國 - Michael Smith" = "blg00570"
"(Complete Version)(CC字幕) The KK Show - #153 逃出中國 - Michael Smith" = "blg00570"
"逃出上海 Escape Shanghai!｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra00570"
"Escape Shanghai! 逃出上海 ｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra00570"
"有外媒相信中國的謊言？ Western media bought into Chinese LIES about XINJIANG｜ The KK Show - #153 Michael Smith" = "extra00570"
"Western media bought into Chinese LIES about XINJIANG 有外媒相信中國的謊言？ ｜ The KK Show - #153 Michael Smith" = "extra00570"
"#clips Western media bought into Chinese LIES about XINJIANG 有外媒相信中國的謊言？ ｜ The KK Show Michael Smith" = "extra00570"
"#Clips Escape Shanghai! 逃出上海 ｜ The KK Show - #153 逃出中國 - Michael Smith" = "extra00570"
"The KK Show - #154 好機車-嗩吶 @好機車" = "blg00573"
"Andrew Tate到底是誰？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra00573"
"#Clips Andrew Tate到底是誰？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra00573"
"#Clips 戰狼電影幕後秘辛、被解放軍圍起來？ ｜ The KK Show - #154 好機車-嗩吶 @好機車" = "extra00573"
"#Clips 離鄉背井結果被當成白猴子，後來反轉人生！ ｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra00576"
"#Clips 台灣要留住外來人才法規需要更友善｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra00576"
"#Clips 台灣流行樂壇沒落的原因 ｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra00576"
"#Clips 離鄉背井在中國被當成白猴子｜ The KK Show - #155 自由的爵士野獸 - Musa 明馬丁 @Musa明馬丁" = "extra00576"
"#Clips 以前成功的那套在新媒體不一定吃得開｜ The KK Show - #156 吳念真" = "extra00579"
"#Clips 政治歸政治 藝術歸藝術是屁話｜ The KK Show - #156 吳念真" = "extra00579"
"#Clips 舞台是烏托邦的展現｜ The KK Show - #156 吳念真" = "extra00579"
"#Clips 館長電商經營甘苦談 | The KK Show - #157 館長" = "extra00583"
"#Clips 疫情對健身產業的影響 | The KK Show - #157 館長" = "extra00583"
"#Clips 除了掃地 除草，軍人可以做更多 | The KK Show - #157 館長" = "extra00583"
"The KK Show - #158 與鯨魚游泳的男人 - 剛哥" = "blg00586"
"#Clips 在海中\"淺\"出全新的世界 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra00586"
"#Clips 看美女水下美照 不如看鯨魚 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra00586"
"#Clips 在海中\"潛\"出全新的世界 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra00586"
"#Clips 看辣妹水下美照 不如看鯨魚 | The KK show - #158 與鯨魚游泳的男人 - 剛哥" = "extra00586"
"#Clips 擦槍走火的論文門事件內幕 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra00587"
"#Clips 投票率創下30年來新低 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra00587"
"#Clips 尼采認為的 道德枷鎖？ ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra00587"
"#Clips 今年投票率將創下30年來新低 ｜The KK Show - #159 聊聊選舉 - 人渣文本" = "extra00587"
"The KK Show - #160 民進黨新竹縣候選人 - 周江杰" = "blg00588"
"#Clips 新竹縣的年輕人需要什麼？ | The KK Show - #160 新竹縣長候選人 - 周江杰" = "extra00588"
"#Clips 沒有資源要怎麼選艱困選區？ | The KK Show - #160 新竹縣長候選人 - 周江杰" = "extra00588"
"【CC字幕】The KK Show - #163 小澤瑪莉雅 @MARIA OZAWA【Official】" = "blg00599"
"0814 川普豪宅為什麼被FBI闖入、歐洲能源現狀、經濟學人fat shaming？" = "blg00551"
"PELOSI ARRIVES in TAIWAN, We talk to REAL People, REAL Thoughts" = "blg00545"
"越戰美國大兵有嚴重的用藥問題、讀書會：同情者 CH 2" = "blg00535"
"女演員的互相傷害 觀眾在旁吃瓜 feat @酸酸脫口秀 @許乃涵 涵冷娜" = "blg00523"
"喜劇演員開喜劇俱樂部是悲劇的開始嗎？ 笑友會的無情工商 @黃豪平 @微笑丹尼的喜劇頻道" = "blg00515"
"The KK Show - #129 揭發聯合國的記者 - Naomi O’Leary (有CC字幕)⏐The Reporter Who EXPOSED the United Nations" = "blg00495"
"『Clubhouse特別企劃』歡迎被封城的聽眾來聊天" = "blg00492"
"閒聊 #威爾史密斯 巴掌事件 ft. @酸酸脫口秀" = "blg00485"
"0327 俄國股市大漲但是通膨漲更多、泰國將禁止用虛擬貨幣支付、推薦Youtube： @Will Tennyson" = "blg00483"
"The KK Show - #124 杜汶澤 @杜汶澤喱騷 Chapman To's Lateshow" = "blg00478"
"讀書會： Fat Leonard 完結，關心一下隔離中的 @敏迪選讀" = "blg00476"
"美國海軍出賣台灣機密為了滿足私慾，讀書會：Fat Leonard #04" = "blg00473"
"The KK Show - #122 匿名者 - 蕭東意 @嚎哮排演HaoxHsiaoTroupe" = "blg00472"
"第一次在秘密基地錄音、小看女人會出大事 | 讀書會：Fat Leonard #03" = "blg00470"
"The KK Show - #121 運動歸運動 政治歸政治(?) - 人渣文本" = "blg00469"
"The KK Show - #119 @黃大謙" = "blg00462"
"The KK Show - #117 @呱吉" = "blg00456"
"The KK Show - #115 與自己的奶和解 - @泥泥學姐Janie" = "blg00450"
"0109 凱莉是真五迷、哈薩克暴動 俄國支援、教宗譴責不生小孩的人、推薦：Don’t Look Up, 疫年記西藏" = "blg00449"
"【百靈果】直接槓上 #五月天 ！自家小編打工竟然被翻手機？！" = "blg00446"
"1212 教練帶辣妹去教人生道理、中國公務員被砍薪 連獎金都要交回去、蘋果跟中國的秘密協議、推薦： Youtube 頻道 @Colin and Samir" = "blg00437"
"1205 八角籠預告、Airbnb在新疆有房子是解放軍的、靠加密貨幣成爲最富有華人、紐約時報批評左派" = "blg00434"
"性教育：只要我不尷尬，尷尬的就是別人，讀書會：吃佛 Eat The Buddha #07 Ch22-23 (End)" = "blg00427"
"美國演唱會意外8人死亡、上字幕上到大哭、藏人喇嘛用自焚説出他們説不出的話，讀書會：吃佛 Eat the Buddha #06 Ch18-21" = "blg00424"
"（有CC字幕）The KK Show - # 106 收起你的玻璃心 - Kimberley 陳芳語 @Kimberley Chen" = "blg00423"
"彭帥事件、英國女生夜店被下藥事件、西藏314事件、不過年就是搞分裂 讀書會：吃佛 #05 Ch 15-17" = "blg00421"
"The KK Show - #105 #OnlyFans 男男片創作者- 社畜" = "blg00420"
"百靈果到處跑 #2 - John Oliver 觀後感, 原本要去慈湖可是休息所以去龍潭" = "blg00418"
"1024 NBA球星聲援西藏、台灣的朋友要民主化我們要支持嗎、推薦劇：House of Secrets" = "blg00416"
"油價暴漲、韓國總統候選人希望人人有錢拿、理查吉爾不受全中共歡迎、 讀書會： 吃佛 Eat The Buddha #03" = "blg00412"
"1003 凱莉壓力太大崩潰、員工傻眼 、泰國性產業被疫情衝擊 feat. @敏迪選讀" = "blg00407"
"The KK Show - #100 @寶島神很大 -龍哥" = "blg00405"
"0919 #世界銀行 逃不出中國魔爪、川普參謀長超怕第三次世界大戰、玩遊戲賺 #加密貨幣、#台南 跟澎湖旅遊" = "blg00401"
"0912 美國的強制疫苗令會引起内戰吧？中國對塔利班是真心的、孟晚舟在加拿大過很爽 推薦：喜劇攻略、#勇者動畫系列 、#尚氣" = "blg00398"
"0905 封殺 #娘炮 文化 ？中國要抵制的 #台灣 都歡迎、歐盟有 #川普 創傷症候群" = "blg00395"
"0829 #遠端工作 慢慢主流化 老闆們要調整、#阿富汗 食物短缺問題、推薦書：Project Hail Mary" = "blg00392"
"#塔利班 拿跟 #習近平 合照給大家看、公務員要兼差養活自己？ 宮前町九十番地 04" = "blg00391"
"0822 #OnlyFans 洗白性工作者怎麽辦？拜登這次被 #Taliban 搞得很難看 Feat. @敏迪選讀" = "blg00389"
"#阿富汗 #塔利班 新聞更新、 刺殺蔣經國的人還在台灣、海上吹風之旅 (Audio Fix)" = "blg00388"
"#讀書會 又要重啓了，#宮前町九十番地 序" = "blg00379"
"The KK Show - #90 馬來西亞 的聲音 - 秉昀 @Byun小眼睛秉昀" = "blg00375"
"百靈果之友: 004 報導者 致昕" = "blg00376"
"百靈果之友: 003 無國界醫生 劉董" = "blg00372"
"百靈果之友: 002 呱吉 議員說他沒上班" = "blg00368"
"百靈果之友: 001 阿滴英文 S is for Sister" = "blg00365"
"The KK Show - #88 台越混血的和平黑音人 - @桃子A1J" = "blg00367"
"醫護人員We Love You、被自己國家下毒還無法伸冤、阿根廷是納粹天堂？ 讀書會： CIA 洗腦計劃 Ch 3、4" = "blg00353"
"The KK Show - #83 美國小兒科醫生 - Dr. Leanne Wu" = "blg00352"
"（首播改5/17）0516 東京奧運的保險套在幹嘛？ 用麵包店的AI來找癌細胞、呱吉吃droppings" = "blg00345"
"回台灣一定要吃的滷肉飯（吃播？） 讀書會：蚵仔煎的身世 Part 1" = "blg00338"
"天地會=法輪功？ 金瓶梅到底露骨不露骨？ 讀書會 傀儡花：第七部 第八部 56章" = "blg00329"
"The KK Show - #67 AIT美國在台協會文化官 - Luke Martin （有CC字幕喔）" = "blg00307"
"老師在毒梟領地内要怎麽教小孩？開飛機運輸發大財 讀書會：毒家企業 Narconomics Ch1, 2, 3" = "blg00302"
"遊戲裏的末日避難所都是真的 (終)： 讀書會 宋氏三姐妹 Ch 22、23、24" = "blg00294"
"The KK Show - #53 @黃豪平" = "blg00268"
"與范琪斐聊讀書心得，左派媒體的失控與右派媒體的可信度" = "blg00255"
"0920 Bob Woodward 新書 Rage 心得、振華搜集你的個資不是給國家 澳洲記者可以作證、希臘難民營大火、Ken要對臺東道歉、 @ABAO阿爆_阿仍仍 演唱會" = "blg00245"
"推倒資本主義的高牆：免費教你如何做Podcast 05 : 軟體後製 ft. @NiceChord (好和弦)" = "blg00241"
"The KK Show - #41逃出疫區的紐約客 - Esther Chen" = "blg00232"
"The KK Show - #38 遇到凱莉就無法炫富的 @Joeman" = "blg00223"
"0626 拜登想跟中國和好？ 澳洲新政府想跟中國破冰、荷葉邊的威力" = "blg00532"
"0619 醒來了的AI、汽車保險有理賠HPV嗎、推薦劇：聽話的孩子：邪教的禱告與服從" = "blg00528"
"0529 凱莉錄嘻哈、美國德州小學槍擊事件、新疆警察檔案、推薦電影《捍衛戰士：獨行俠》" = "blg00516"
"The KK Show - #126 長壽的秘密 - 許翱麟教授" = "blg00484"
"The KK Show - #120 時代革命導演 - 周冠威" = "blg00465"
"0206 #谷愛凌 是超級間諜？ 紐西蘭爲什麽要開放旅遊了？ 閒聊Joe Rogan 後續 推薦電影:偶然與想像" = "blg00461"
"林獻堂的兒子們怎麽有辦法跟老爸旅遊這麽久不發瘋？ 讀書會：林獻堂環球遊記 End" = "blg00457"
"1017 普丁叫習近平要老實一點、紅海上有隨時會爆炸的油輪、推薦Podcast: Arirang Radio" = "blg00413"
"魷魚遊戲概念股帶韓國股市一起飛、共產黨弄了一個傀儡喇嘛、讀書會：吃佛 Eat The Buddha #01" = "blg00406"
"中國透過維基百科更改歷史、老闆去新竹向員工道歉、文科畢業生的重要性" = "blg00400"
"日本有東京變種新冠肺炎、#顔千鶴 女士是現代女性的好榜樣 、 員工比老闆早去看 #心理諮商 讀書會： 宮前町九十番地 05" = "blg00394"
"The KK Show - #95 馬來西亞自由的聲音 - 盧卡斯 @BBK Network" = "blg00390"
"0801 閒聊奧運第一週、難民選手救全船、美國國會山莊聽證會開始啦" = "blg00380"
"The KK Show - #91 葉耀元教授又來啦" = "blg00378"
"0725 手機被監控的總理們、 被詛咒的 #東京奧運 、 推薦劇： 漫才梅索太太（The Marvelous Mrs. Maisel）" = "blg00377"
"八角籠直播 EP1《熱愛祖國的中國人》" = "blg00369"
"0620 以色列變天了、打疫苗還是會染疫 尤其是科興、推薦：Inside by Bo Burnham" = "blg00360"
"以前的間諜訓練要帶SM面具？ 連續殺人魔有參與CIA的實驗計劃？ 讀書會：CIA的洗腦計劃：Ch 5、6" = "blg00356"
"肛門裡面的逃生手段、美國就是資源回收做的好 讀書會：CIA洗腦計劃 Ch 1、2" = "blg00350"
"The KK Show - #79 斯卡羅原著《傀儡花》作者 - 陳耀昌醫師" = "blg00343"
"0502 法國退將叫總統硬起來、經濟學人把一件全台灣人都知道的事情放封面、推薦書：黑森林的白玫瑰、爵士邊緣人" = "blg00339"
"0425 澳洲害中國生氣氣、北美珍奶奶要斷貨、凱莉愛曡字、推薦Podcast：敏迪散步、說故事的人、推薦電影：真人快打 Mortal Kombat 就是爽" = "blg00336"
"0418 被最好的朋友刺殺的非洲領袖、中國旅遊驚喜包、蛇編跟我們講解白沙屯媽祖進香" = "blg00333"
"The KK Show - #75 范雲" = "blg00331"
"0411 Dora We Love You、六千九百萬美金 WTF is NFT ? 被抛棄的北愛爾蘭保皇派、推薦書：The Giver" = "blg00330"
"The KK Show - #74 用科學打名嘴臉 - IORG" = "blg00328"
"0404 中國要美國學學中國的氣度、愛煮飯的Youtuber原來是黑手黨、推薦書：Eat The Buddha 噬佛" = "blg00327"
"斯卡羅真的比較帥 我們道歉、台南清朝就有蝦仁肉圓跟炒鱔魚意麵？ 讀書會：傀儡花 第三部 第四部" = "blg00323"
"鹿港遶境 0314 南韓願意提高保護費、PEACE 海底電纜是華爲的哦" = "blg00318"
"關於藻礁、Los Zetas黑幫蓋了自己的中華電信、Starboy Matt Bowden 讀書會：毒家企業 Ch 6、7" = "blg00311"
"The KK Show - #66 拉丁美洲專家 - 陳小雀教授" = "blg00304"
"0207 膝擊緬甸的蛋蛋、蓋亞那玩弄了台灣的蛋蛋、推薦Podcast：The Passenger List" = "blg00303"
"The KK Show - #63 兩岸關係 - 張五岳" = "blg00296"
"The KK Show - #62 笑話背後的故事 - 大可愛" = "blg00293"
"The KK Show - #60 過了一年變得有韻味 - Angel" = "blg00287"
"The KK Show - #56 相聲邊緣人 - 黃逸豪 （相聲界的博恩）" = "blg00277"
"The KK Show - #55 好想上班的立委 - 陳柏惟" = "blg00274"
"孫文其實是個假abc、Charlie Soong 失敗的異國戀情 : 讀書會 宋氏三姐妹 Ch1、2" = "blg00269"
"The KK Show - #52 Ken的私人診療室 - 唐綺陽" = "blg00265"
"1018 尋求父愛的路總是辛苦的：杭特拜登、泰王這麽爽會想要改革嗎、凱莉投票了" = "blg00256"
"The KK Show - #48 國民黨的邊緣人 - 于北辰將軍" = "blg00254"
"The KK Show - #46 新竹市長 - 林智堅" = "blg00248"
"The KK Show - #45 最偏激的Podcast平臺 - Firstory" = "blg00246"
"The KK Show - #44文化策展人 - 真蓉" = "blg00240"
"The KK Show - #43 - 報導者來了 - Jason" = "blg00238"
"The KK Show - #42 印度尤物 - 印度尤" = "blg00235"
"The KK Show - #37 婦產科流言終結者 － 烏烏醫生" = "blg00220"
"The KK Show - #36 熟了就會浮起來 - 3Q 陳柏惟" = "blg00217"
"The KK Show - #35 正面的攝影都驚呆了 - 黑嘉嘉" = "blg00214"
"The KK Show - #34 小粉紅殺手 - 沈伯洋（助理）教授" = "blg00211"
"The KK Show - #33 一言不合就Docking - 趙哥" = "blg00208"
"Born a crime 以母之名 第十八章（完）" = "blg00052"
"Born a crime 以母之名 第十七章" = "blg00048"
"Born a crime 以母之名 第十六章 Cheese Boys" = "blg00044"
"百靈果讀書會 - Born a crime 以母之名 第十五章 Go Hitler!" = "blg00040"
"The KK Show - #36 熟了就會浮起來 - @3Q陳柏惟" = "blg00217"
"The KK Show - #55 好想上班的立委 - @3Q陳柏惟" = "blg00274"
"The KK Show - #37 婦產科流言終結者－烏烏醫生" = "blg00220"
"The KK Show - #43 @報導者 The Reporter 來了 - Jason （小粉紅快來 我們有聊新疆）" = "blg00238"
"The KK Show - #03 2020的費玉清 - @黃豪平" = "blg00123"
"The KK Show - #04 外商藥頭喜劇人 - 艾董" = "blg00126"
"The KK Show - #05 廣播教主 - @歐馬克" = "blg00129"
"The KK Show - #06 幹話超多的健身教練 - Shao Yong" = "blg00133"
"The KK Show - #07 博恩夜夜秀真主角 - @賀瓏Hello" = "blg00137"
"The KK Show - #08 國際新聞扛霸子 - 范琪斐" = "blg00140"
"The KK Show - #09 這麽帥不去選立委可惜 - 顧立楷" = "blg00142"
"The KK Show - #10 巴賽隆納的傳教士 - Angel" = "blg00144"
"The KK Show - #11 排灣的Rihanna (自稱) - @ABAO阿爆_阿仍仍" = "blg00147"
"The KK Show - #11 阿爆 - Bonus Clip: 部落的同婚議題" = "extra00147"
"The KK Show - #12 脫口秀界的小隻馬 - 么么跟怡岑" = "blg00150"
"The KK Show - #13 與知識藍的對話 - Wolf" = "blg00152"
"The KK Show - #14 與皇民綠的對話 - 日文老師Ivan" = "blg00154"
"The KK Show - #15 會走路的翻譯機 - Howard" = "blg00156"
"The KK Show - #16 耳膜爆破之 #龍龍 與凱莉聊天 @龍龍LungLung" = "blg00158"
"The KK Show - #17 土耳其準媳婦 (?) - Feyza" = "blg00161"
"The KK Show - #18 台語講的比印度話好的 Angeli" = "blg00164"
"The KK Show - #19 害羞的開屏孔雀 - @酸酸脫口秀" = "blg00167"
"The KK Show - #20 豁達的女漢子 - Niki" = "blg00170"
"The KK Show - #21 來自苗栗國的山下智久 - @Gooaye 股癌" = "blg00171"
"The KK Show - #22 Eleven Sports 體育記者 - 莉婷" = "blg00173"
"（正成集團贊助）The KK Show - 吃播主ASMR Pom咩 ｜ Husky Podcast ASMR" = "blg00175"
"THE KK SHOW - #23 地獄來的喜劇演員 - Jim @JIM 程建評" = "blg00178"
"The KK Show - #24 范琪斐" = "blg00181"
"The KK Show - #25 @呱吉" = "extra00184"
"The KK Show - #25.1 @呱吉 （聲音調整＋ASMR＋一刀未剪版）" = "blg00184"
"The KK Show - #26 人妻啦啦隊 - 妍言" = "blg00186"
"The KK Show - #25.5? 與 @呱吉 直播 （2020.04.30 錄影）" = "extra00184"
"The KK Show - #27 斜槓破表的 - 邱grr" = "blg00189"
"The KK Show - #28 算盡天機可是手被夾到的算命師 - 簡少年" = "blg00192"
"THE KK SHOW - #29 國際級電視製作人 - Roger" = "blg00195"
"THE KK SHOW - #30 太陽花誕生出來的夥伴 - 法律白話文(法客電台)" = "blg00198"
"The KK Show - #31燃燒生命的棒球魂 - Hito大聯盟" = "blg00202"
"The KK SHOW - #32 吃豬肉的前穆斯林 - 阿秋" = "blg00205"
"The KK Show - #64 今天來賣票 - 博恩 @Stand up, Brian! 博恩站起來！" = "blg00298"
"The KK Show - #92 被排擠的國民黨將軍 - 于北辰將軍 @北極星說故事" = "blg00381"
"KK Show #預告片 黃秋生" = "extra00411"
"The KK Show - #103 博恩斬馬謖 - 老K @這是老K ThatsOldKay" = "blg00414"
"黃郁婷選手的行為是誰的錯 #人渣文本 | KK Show Clips" = "extra00469"
"谷愛凌的話術要怎麽破解 #人渣文本 | KK Show Clips" = "extra00469"
"疫情期間舞臺劇怎麽活 國家補助怎麽拿 #蕭東意 @嚎哮排演HaoxHsiaoTroupe | KK Show Clips" = "extra00472"
"沒看過舞臺劇新手要怎麽入門？ #蕭東意 @嚎哮排演HaoxHsiaoTroupe | KK Show Clips" = "extra00472"
"The KK Show - #123 Kimberley 陳芳語 @Kimberley Chen" = "blg00475"
"The KK Show - #125 公民記者 陳秋實 @秋实朋友圈 Qiushi Studio" = "blg00481"
"The KK Show - #131 吳淡如 @吳淡如人生實用商學院（Official官方唯一頻道）" = "blg00498"
"The KK Show - #134 炎上系Youtuber - Joeman @Joeman" = "blg00509"
"The KK Show - #135 聊聊新冠肺炎 - 陳零九 @陳零九 NINE CHEN" = "blg00513"
"The KK Show - #143 陳大天 @陳大天的蝦叔哈啦" = "blg00541"
"The KK Show - #144 樂樂法利 @LeLe Farley" = "blg00543"
"瑞典民眾攻擊警方事件｜KK Show 145 瑞典劉先生" = "extra00546"
"瑞典是脫離人際關係的天堂｜KK Show 145 瑞典劉先生" = "extra00546"
"在便利商店發生的遇到奇人｜KK Show 146 權樂" = "extra00549"
"創作時如何把感官放大的修煉方式｜KK Show 146 權樂" = "extra00549"
"疫情下的里長被里民跟中央政策夾在中間｜KK Show 147 里長" = "extra00552"
"里長的使用手冊｜KK Show 147 里長" = "extra00552"
"The KK Show - #148 青年韓粉？歷史哥：我不是！ @歷史哥HistoryBro" = "blg00555"
"何謂台派？國民黨精神分裂｜KK Show 148 青年韓粉？歷史哥：我不是！ @歷史哥HistoryBro" = "extra00555"
"台灣人可以自己決定自己的未來？｜KK Show 148 青年韓粉？歷史哥：我不是！ @歷史哥HistoryBro" = "extra00555"
"幫韓國瑜站台可是選輸後被檢討？｜KK Show 148 青年韓粉？歷史哥：我不是！ @歷史哥HistoryBro" = "extra00555"
"The KK Show - #174 半年賣破千萬的餃子推手 - 尚恩 @shawnlin365" = "blg00626"
