# Comedians/Stand Up comedy

["Atsuko Okatsuka"]
inclusive = ["Atsuko Okatsuka"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["瑞恩"]
inclusive = ["瑞恩"]
exclusive = []
category = ["喜劇演員"]

[Hector]
inclusive = ["Hector"]
exclusive = []
category = ["喜劇演員"]

["龍哥（喜劇）"]
inclusive = ["龍哥"]
exclusive = ["神很大"]
category = ["喜劇演員","老闆"]

["喬瑟夫"]
inclusive = ["喬瑟夫"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["樂樂法利"]
inclusive = ["樂樂法利","(11/24錄音)簡體中文反共圈的困境","How American sees Taiwan's election"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["Jason Cheny"]
inclusive = ["Jason Cheny"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["陳大天"]
inclusive = ["陳大天"]
exclusive = []
category = ["喜劇演員","藝人"]

["小歐"]
inclusive = ["小歐"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["老K"]
inclusive = ["老K"]
exclusive = []
category = ["喜劇演員"]

["妍霏"]
inclusive = ["妍霏"]
exclusive = []
category = ["喜劇演員"]

["學仁"]
inclusive = ["學仁"]
exclusive = []
category = ["喜劇演員"]

["天殘"]
inclusive = ["天殘"]
exclusive = []
category = ["喜劇演員"]

["佳諭"]
inclusive = ["佳諭"]
exclusive = []
category = ["喜劇演員"]

["品喬"]
inclusive = ["品喬"]
exclusive = []
category = ["喜劇演員"]

["不知火"]
inclusive = ["不知火"]
exclusive = []
category = ["喜劇演員"]

[Social]
inclusive = ["Social"]
exclusive = []
category = ["喜劇演員","老闆"]

["歐馬克"]
inclusive = ["歐馬克"]
exclusive = []
category = ["喜劇演員","廣播人","Podcaster"]

["微笑丹尼"]
inclusive = ["微笑丹尼"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["博恩"]
inclusive = ["博恩"]
exclusive = ["老K","夜夜秀真主角","百靈果NEWS"]
category = ["喜劇演員"]

["大可愛"]
inclusive = ["大可愛"]
exclusive = []
category = ["喜劇演員"]

["權樂"]
inclusive = ["權樂"]
exclusive = []
category = ["喜劇演員","演員","文藝"]

["巴斯"]
inclusive = ["巴斯"]
exclusive = []
category = ["喜劇演員","工程師","魔術師"]

["黃逸豪"]
inclusive = ["黃逸豪"]
exclusive = []
category = ["喜劇演員"]

["艾董"]
inclusive = ["艾董"]
exclusive = []
category = ["喜劇演員"]

["黃豪平"]
inclusive = ["黃豪平"]
exclusive = []
category = ["喜劇演員","廣播人","藝人","魔術師","Youtuber","Podcaster"]

["Tim Chen"]
inclusive = ["Tim Chen"]
exclusive = []
category = ["喜劇演員"]

["東區德"]
inclusive = ["東區德"]
exclusive = []
category = ["喜劇演員"]

["阿秋"]
inclusive = ["阿秋"]
exclusive = []
category = ["喜劇演員"]

["賀瓏"]
inclusive = ["賀瓏"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["么么"]
inclusive = ["么么"]
exclusive = []
category = ["喜劇演員"]

["怡岑"]
inclusive = ["怡岑"]
exclusive = []
category = ["喜劇演員"]

["酸酸"]
inclusive = ["酸酸"]
exclusive = []
category = ["喜劇演員","Youtuber","Podcaster"]

["涵冷娜"]
inclusive = ["許乃涵","涵冷娜"]
exclusive = []
category = ["喜劇演員","演員","文藝"]

["Esther Chen"]
inclusive = ["Esther Chen"]
exclusive = []
category = ["喜劇演員","演員","文藝"]

["Jamie"]
inclusive = ["喜劇演員 Jamie"]
exclusive = []
category = ["喜劇演員"]

["呱吉"]
inclusive = ["呱吉"]
exclusive = ["0516"]
category = ["喜劇演員","Youtuber","Podcaster","政治人物","老闆"]

["歐耶"]
inclusive = ["歐耶"]
exclusive = []
category = ["喜劇演員","Youtuber","老闆"]

[Jim]
inclusive = ["Jim"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["龍龍"]
inclusive = ["龍龍"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["Q毛"]
inclusive = ["Q毛"]
exclusive = []
category = ["喜劇演員","Youtuber"]

["壯壯"]
inclusive = ["壯壯"]
exclusive = []
category = ["喜劇演員","Youtuber"]

[Sam]
inclusive = ["Sam, An American chasing comedy dream in Taiwan"]
exclusive = []
category = ["喜劇演員"]

# Youtuber/Podcaster/音樂/色色

["視網膜"]
inclusive = ["視網膜曝原因"]
exclusive = []
category = ["時事","Youtuber"]

["動眼神經"]
inclusive = ["視網膜曝原因"]
exclusive = []
category = ["時事","Youtuber"]

["范琪斐"]
inclusive = ["范琪斐","敏迪炎上"]
exclusive = []
category = ["時事","Youtuber","Podcaster"]

["敏迪 @敏迪選讀"]
inclusive = ["敏迪選讀","敏迪、","敏迪炎上","0807 國外旅遊","1003 凱莉崩潰","關心一下隔離中的Mindy"]
exclusive = []
category = ["時事","Podcaster"]

["志祺 @志祺七七"]
inclusive = ["志祺","志祺七七"]
exclusive = []
category = ["Youtuber","Podcaster","老闆"]

["好和弦 @NiceChord"]
inclusive = ["好和弦"]
exclusive = []
category = ["Youtuber","Podcaster"]

["蕾拉"]
inclusive = ["蕾拉"]
exclusive = []
category = ["Youtuber","Podcaster"]

["Ms Puiyi"]
inclusive = ["Ms Puiyi"]
exclusive = []
category = ["Youtuber","Instagramer"]

["阿滴"]
inclusive = ["阿滴"]
exclusive = []
category = ["Youtuber","老闆"]

[Joeman]
inclusive = ["Joeman"]
exclusive = []
category = ["Youtuber","老闆"]

["Ted @35線上賞屋"]
inclusive = ["& Ted"]
exclusive = []
category = ["Youtuber","老闆"]

["蔡阿嘎"]
inclusive = ["蔡阿嘎"]
exclusive = []
category = ["Youtuber","Podcaster"]

["黃大謙"]
inclusive = ["黃大謙"]
exclusive = []
category = ["Youtuber"]

["China Mac"]
inclusive = ["China Mac"]
exclusive = []
category = ["Youtuber"]

["Cheap"]
inclusive = ["Cheap"]
exclusive = []
category = ["Youtuber"]

["邱 grr"]
inclusive = ["邱grr","邱Grrr"]
exclusive = []
category = ["Youtuber","老闆","運動","健力"]

["泥泥學姐"]
inclusive = ["泥泥學姐"]
exclusive = []
category = ["Youtuber"]

["Alma & 小妖"]
inclusive = ["Alma & 小妖"]
exclusive = []
category = ["Youtuber"]

["Lucas @BBK Network"]
inclusive = ["盧卡斯","BBK Network","馬來西亞的眼球中央電視台"]
exclusive = []
category = ["Youtuber"]

["嘉雯 @BBK Network"]
inclusive = ["馬來西亞的眼球中央電視台"]
exclusive = []
category = ["Youtuber"]

["Eric @The DoDo Men"]
inclusive = ["Dodo Men","DoDo Men","dodo Men","Dodo men","DoDo men","dodo men"]
exclusive = []
category = ["Youtuber","Podcaster","喜劇演員"]

["Ian @The DoDo Men"]
inclusive = ["Dodo Men","DoDo Men","dodo Men","Dodo men","DoDo men","dodo men"]
exclusive = ["The KK Show - 253"]
category = ["Youtuber","Podcaster"]

["有特色的帥哥"]
inclusive = ["有特色的帥哥"]
exclusive = []
category = ["Youtuber","Instagramer"]

["陳老師來了"]
inclusive = ["陳老師來了"]
exclusive = []
category = ["Youtuber"]

["鍾佳播"]
inclusive = ["鍾佳播"]
exclusive = []
category = ["Youtuber"]

["椅人 Leo"]
inclusive = ["椅人 Leo"]
exclusive = []
category = ["Youtuber"]

["歷史哥"]
inclusive = ["歷史哥"]
exclusive = []
category = ["Youtuber"]

["嗩吶 @好機車"]
inclusive = ["嗩吶"]
exclusive = []
category = ["時事","Youtuber"]

["街頭有派對"]
inclusive = ["街頭有派對"]
exclusive = []
category = ["時事","Youtuber"]

["黃明志"]
inclusive = ["黃明志"]
exclusive = []
category = ["音樂","Youtuber"]

["Peggy"]
inclusive = ["Peggy","Catching up", "Catching Up"]
exclusive = ["Sam, An American chasing comedy dream in Taiwan"]
category = ["媒體人","Youtuber","Podcaster"]

["阿爆"]
inclusive = ["阿爆"]
exclusive = ["阿爆演唱會"]
category = ["音樂","原住民","朋友"]

["阿拉斯"]
inclusive = ["阿拉斯"]
exclusive = []
category = ["Youtuber","音樂","原住民"]

["巴大雄 @東南美娛樂"]
inclusive = ["巴大雄"]
exclusive = []
category = ["Youtuber","音樂","原住民"]

["賈培德"]
inclusive = ["賈培德"]
exclusive = []
category = ["Youtuber","文藝","廣播人"]

["中指通"]
inclusive = ["中指通"]
exclusive = []
category = ["Youtuber","色色"]

["小澤瑪利亞"]
inclusive = ["小澤瑪莉雅","小澤瑪利亞"]
exclusive = []
category = ["色色","老闆"]

["社畜"]
inclusive = ["社畜"]
exclusive = []
category = ["色色"]

["娃娃"]
inclusive = ["娃娃"]
exclusive = []
category = ["色色"]

["石巴朝"]
inclusive = ["石巴朝"]
exclusive = []
category = ["色色"]

["加藤鷹"]
inclusive = ["加藤鷹"]
exclusive = []
category = ["色色"]

[Niki]
inclusive = ["Niki"]
exclusive = []
category = ["色色"]

["手槍女王"]
inclusive = ["手槍女王"]
exclusive = []
category = ["色色"]

["陳零九"]
inclusive = ["陳零九"]
exclusive = []
category = ["音樂"]

["Kimberley陳芳語"]
inclusive = ["Kimberley","陳芳語"]
exclusive = []
category = ["音樂"]

["MATZKA"]
inclusive = ["MATZKA"]
exclusive = []
category = ["音樂"]

["王彩樺"]
inclusive = ["王彩樺"]
exclusive = []
category = ["藝人","音樂"]

["趙詠華"]
inclusive = ["趙詠華"]
exclusive = []
category = ["藝人","音樂","Podcaster"]

["林俊逸"]
inclusive = ["林俊逸"]
exclusive = []
category = ["藝人","音樂","Podcaster"]

["禁藥王 & 栗子"]
inclusive = ["禁藥王 & 栗子"]
exclusive = []
category = ["藝人","音樂"]

["大霈"]
inclusive = ["大霈","百靈果對公視國際台TaiwanPlus頻道大暴走"]
exclusive = []
category = ["藝人","音樂"]

["Musa 明馬丁"]
inclusive = ["Musa 明馬丁"]
exclusive = []
category = ["音樂"]

["桃子 A1J"]
inclusive = ["桃子A1J"]
exclusive = []
category = ["音樂"]

["珂拉琪 Collage"]
inclusive = ["珂拉琪Collage"]
exclusive = []
category = ["音樂"]

["POPO J"]
inclusive = ["POPO J"]
exclusive = []
category = ["音樂","警察"]

["李心潔"]
inclusive = ["李心潔"]
exclusive = []
category = ["演員","文藝","音樂"]

["Chapman 杜汶澤"]
inclusive = ["Chapman","杜汶澤"]
exclusive = []
category = ["演員","老闆","文藝"]

["黃秋生"]
inclusive = ["黃秋生"]
exclusive = []
category = ["演員","文藝"]

["小酷人 路易"]
inclusive = ["小酷人"]
exclusive = []
category = ["演員","文藝"]

["陽靚"]
inclusive = ["陽靚"]
exclusive = []
category = ["演員","文藝"]

["大牙"]
inclusive = ["大牙"]
exclusive = []
category = ["演員","文藝","藝人"]

["林倩"]
inclusive = ["林倩"]
exclusive = []
category = ["攝影","Instagramer"]

# 舞台劇/策展

["台南人劇團"]
inclusive = ["台南人劇團"]
exclusive = []
category = ["文藝","劇場"]

["蕭東意"]
inclusive = ["蕭東意"]
exclusive = []
category = ["文藝","演員","劇場","喜劇演員"]

["布拉瑞揚 @布拉瑞揚舞團"]
inclusive = ["布拉瑞揚"]
exclusive = []
category = ["文藝","舞蹈","原住民"]

["磊勒丹"]
inclusive = ["磊勒丹"]
exclusive = []
category = ["文藝","原住民"]

["孫翠鳳"]
inclusive = ["孫翠鳳"]
exclusive = []
category = ["文藝"]

["陳昭賢"]
inclusive = ["陳昭賢"]
exclusive = []
category = ["文藝"]

["陳亞蘭"]
inclusive = ["陳亞蘭"]
exclusive = []
category = ["文藝"]

["真蓉"]
inclusive = ["真蓉"]
exclusive = []
category = ["文藝"]

# 電影/電視劇/電視節目/廣播/Podcaster

["劉珞亦 @法律白話文"]
inclusive = ["法律白話文"]
exclusive = []
category = ["Podcaster","律師"]

["楊貴智 @法律白話文"]
inclusive = ["法律白話文","找律師"]
exclusive = []
category = ["Podcaster","律師"]

["大麻律師 李菁琪 @大麻煩不煩"]
inclusive = ["李菁琪"]
exclusive = []
category = ["Podcaster","律師"]

["唐綺陽"]
inclusive = ["唐綺陽"]
exclusive = []
category = ["Youtuber","Podcaster"]

["簡少年"]
inclusive = ["簡少年"]
exclusive = []
category = ["Youtuber","Podcaster"]

["台灣通勤第一品牌"]
inclusive = ["台灣通勤第一品牌"]
exclusive = ["推薦Podcast"]
category = ["Podcaster"]

["股癌"]
inclusive = ["股癌"]
exclusive = ["推薦Podcast"]
category = ["Podcaster"]

["瑞典劉先生"]
inclusive = ["瑞典劉先生"]
exclusive = []
category = ["時事","Podcaster"]

[Firstory]
inclusive = ["Firstory"]
exclusive = []
category = ["Podcaster"]

["馬力歐"]
inclusive = ["馬力歐"]
exclusive = []
category = ["Podcaster"]

["周冠威"]
inclusive = ["周冠威"]
exclusive = []
category = ["導演","文藝"]

["阮鳳儀"]
inclusive = ["阮鳳儀"]
exclusive = []
category = ["導演","文藝"]

["吳念真"]
inclusive = ["吳念真"]
exclusive = []
category = ["導演","影視製作","演員","文藝"]

# 製作人

["汪怡昕"]
inclusive = ["汪怡昕"]
exclusive = []
category = ["製作人","影視製作"]

["龍哥（影視）"]
inclusive = ["龍哥"]
exclusive = ["做喜劇"]
category = ["製作人","影視製作"]

["Roger"]
inclusive = ["Roger"]
exclusive = []
category = ["製作人","影視製作"]

["小聶"]
inclusive = ["小聶"]
exclusive = []
category = ["製作人","影視製作","Podcaster"]

[Mego]
inclusive = ["Mego"]
exclusive = []
category = ["影視製作"]

[Nick]
inclusive = ["做的好就好像沒做事 - Nick"]
exclusive = []
category = ["影視製作"]

[Stephen]
inclusive = ["Stephen"]
exclusive = []
category = ["影視製作","百靈果員工"]

["導演 Leo"]
inclusive = ["金門導演"]
exclusive = []
category = ["影視製作","導演"]

["李律"]
inclusive = ["李律"]
exclusive = []
category = ["廣播人"]

["邵大倫"]
inclusive = ["邵大倫"]
exclusive = []
category = ["廣播人"]

["小潘"]
inclusive = ["小潘"]
exclusive = []
category = ["廣播人"]

["寶拉"]
inclusive = ["寶拉"]
exclusive = []
category = ["廣播人"]

["吳淡如"]
inclusive = ["吳淡如"]
exclusive = []
category = ["廣播人","媒體人","Podcaster"]

["李四端"]
inclusive = ["李四端"]
exclusive = ["跟李四端道歉"]
category = ["媒體人"]
