# 事件備註（測試中）

["2022台灣地方選舉"]
inclusive = ["台灣選舉結果","網路操作翻車事件","周江杰","聊聊選舉 - 人渣文本"]
exclusive = []
category = ["#事件備註（測試中）"]

["日本遶境"]
inclusive = ["0731 裴洛西","我們要去日本辦活動啦","日本錄KKShow！","凱莉去日本牛郎店圓夢"]
exclusive = []
category = ["#事件備註（測試中）"]

["裴洛西訪台事件"]
inclusive = ["0731 裴洛西","What do TAIWANESE","Pelosi 來台灣","0807 國外旅遊"]
exclusive = []
category = ["#事件備註（測試中）"]

["國傳司事件"]
inclusive = ["Bonus：國傳司"]
exclusive = []
category = ["#事件備註（測試中）"]

["紐時集資事件"]
inclusive = ["你知道紐約時報其實很親中嗎？"]
exclusive = []
category = ["#事件備註（測試中）"]

["五月天事件"]
inclusive = ["直接槓上五月天","找律師 vs #五月天","凱莉是真五迷"]
exclusive = []
category = ["#事件備註（測試中）"]

["《還有第七人》宣傳"]
inclusive = ["線上算命的真相","凱莉懷孕還是工作狂"]
exclusive = []
category = ["#事件備註（測試中）"]

["百靈果立院事件"]
inclusive = ["引火自焚聊立院","聊聊立法院後續","離開立法院後"]
exclusive = []
category = ["#事件備註（測試中）"]
