inf00001 = ["valuen"]
inf00002 = ["valuen"]
inf00003 = ["valuen"]
inf00004 = ["valuen"]
inf00005 = ["valuen"]
inf00006 = ["valuen"]
inf00007 = ["valuen"]
inf00008 = ["valuen"]
inf00009 = ["valuen"]
inf00010 = ["valuen"]
inf00011 = ["valuen"]
inf00012 = ["valuen"]
inf00013 = ["valuen"]
inf00014 = ["valuen"]
inf00015 = ["valuen"]
inf00016 = ["valuen"]
inf00017 = ["valuen"]
inf00018 = ["valuen"]
inf00019 = ["valuen"]
inf00020 = ["valuen"]
inf00021 = ["valuen"]
inf00022 = ["valuen"]
inf00023 = ["valuen"]
inf00024 = ["valuen"]
inf00025 = ["valuen"]
inf00026 = ["valuen"]
inf00027 = ["valuen"]
inf00028 = ["valuen"]
inf00029 = ["valuen"]
inf00030 = ["valuen"]
inf00031 = ["valuen"]
inf00032 = ["valuen"]
inf00033 = ["valuen"]
inf00034 = ["valuen"]
inf00035 = ["valuen"]
inf00036 = ["valuen"]
inf00037 = ["valuen"]
inf00038 = ["valuen"]
inf00039 = ["valuen"]
inf00040 = ["valuen"]
inf00041 = ["valuen"]
inf00042 = ["valuen"]
inf00043 = ["valuen"]
inf00044 = ["valuen"]
inf00045 = ["valuen"]
