["S1怪新聞"]
inclusive = ["S1怪新聞"]
exclusive = []
category = ["#節目系列"]

["S2怪新聞"]
inclusive = ["S2怪新聞"]
exclusive = []
category = ["#節目系列"]

["S3怪新聞"]
inclusive = ["S3怪新聞"]
exclusive = []
category = ["#節目系列"]

["S4怪新聞"]
inclusive = ["S4怪新聞"]
exclusive = []
category = ["#節目系列"]

["S5怪新聞"]
inclusive = ["S5怪新聞"]
exclusive = []
category = ["#節目系列"]

["S6怪新聞"]
inclusive = ["S6怪新聞"]
exclusive = []
category = ["#節目系列"]
