[spotify]
"新聞聊三小 EP3｜珍奶不是台灣的？劉思慕批：文化挪用" = "https://open.spotify.com/episode/7uJXG6w3ko1ExHGvdlVJ2Q"
"S6怪新聞#4｜澳洲獄警的祖先托夢，買兇殺女兒卻僱到她男友！" = "https://open.spotify.com/episode/3Y1Z5TppxtuFvWVY4k47Li"
"S6三尼聊#1｜澳洲真的有種族歧視嗎？惟元新工作分享、紹平搬家日記與一點點女同樓！" = "https://open.spotify.com/episode/3cDadoixoXZHWHhJqCM32Z"
"新聞聊三小 EP2｜郭雪芙戀情首度曝光，對象是捲髮外國帥哥！" = "https://open.spotify.com/episode/5ALmZ7qyqn3svTs688gfIz"
"新聞聊三小 EP1｜中國國慶日，遊客睡廁所！？" = "https://open.spotify.com/episode/64GlmnoDF6ZHpzZ9yadDLZ"
"新聞聊三小EP1｜中國國慶日，遊客睡廁所！？" = "https://open.spotify.com/episode/64GlmnoDF6ZHpzZ9yadDLZ"
"S6怪新聞#3｜中國女子跟猴子一起吃肯德基全家桶！" = "https://open.spotify.com/episode/3gQP4ZmmjfxpdPQzzPXkEW"
"S6怪新聞#2｜藍寶堅尼騙局，牛媽媽做愛生出狗兒子！" = "https://open.spotify.com/episode/1IXUY82fJowS1GuZiawlgx"
"S6三尼聊【見面會專屬】｜你還記得這些獨家記憶嗎？" = "https://open.spotify.com/episode/7BMrfyn0ByBCsVJT383Xi2"
"S6怪新聞#1｜墨爾本大猩猩踩到化石，招財貓出來汪汪叫！" = "https://open.spotify.com/episode/5rfWmLHeXM338F0CTpeI58"
"S5怪新聞【見面會特輯】｜小鯊魚嫁給艾菲爾鐵塔，愛愛後生殖器紅腫！" = "https://open.spotify.com/episode/6N8k6xozy2OXM925a2TRll"
"S5三尼聊 #24｜極樂的狂荒派對！謝謝尼們！惟元出國前最後的心聲！" = "https://open.spotify.com/episode/3KktxXsOaURDtKNnxGNn0P"
"S5怪新聞#58｜異常大鵰？13隻烏龜＋土撥鼠＋金屬棒塞滿滿！" = "https://open.spotify.com/episode/3qQ1LCLTFvEqmXB0WzHmvY"
"S5怪新聞#57｜新娘單身趴趴趴，爆炒鮮鮑塞牙刷？" = "https://open.spotify.com/episode/6mrJzmv8FbHZI4tsEB1N2c"
"S5怪新聞#56｜怪阿姨全裸問好兄弟：可以跟你握手嗎？" = "https://open.spotify.com/episode/5bmdhV5peNNSUwGAJunLb0"
"S5怪新聞#55｜巴黎奧運集氣！眼鏡蛇尬舞團登場！" = "https://open.spotify.com/episode/5tiZPJ9GVX0Fm7cqVdkvFh"
"S5怪新聞#54｜得到上天的啟示，保全買票穿淺拖仔看表演！" = "https://open.spotify.com/episode/6QWwy3AewPeG2NPu1qev10"
"S5怪新聞#53｜徒步念經到澳洲，人生的最後你會說什摸？" = "https://open.spotify.com/episode/7zoAjnD9VBIx8tFielaxbF"
"S5怪新聞#52｜這集節目會得葛萊美獎！ft.蕭煌奇" = "https://open.spotify.com/episode/7LOjyWAKUaoiIhGi2OUDhe"
"S5怪新聞#51｜迎接暑假！短褲妹打遊戲暈船，跳車抓三百隻蟲！" = "https://open.spotify.com/episode/4j6mflNmwTO7nL3JkogsvM"
"S5怪新聞#50｜李聖傑在美國開唱前遇到兇狠女人暴打計程車司機！（他本人就在車上）" = "https://open.spotify.com/episode/1h0F7obAMqBv8o2XErnGrz"
"S5三尼聊 #23｜真心話大告白！那些你害羞不敢講又好想講的都幫你講出來！" = "https://open.spotify.com/episode/796Nz0Rxe0wbFUopsi9oSF"
"S5三尼聊 #22｜畢業快樂！跌撞後長成了現在的我們☺️" = "https://open.spotify.com/episode/4LlThVr2cQuuVmFKWAJioQ"
"S5怪新聞#49｜公主夢遊中，機場脫衣暴走！" = "https://open.spotify.com/episode/4KqoEBqiG7HMuSjhu62see"
"S5怪新聞#48｜端午節端出什麼怪新聞？馬桶水洗粽葉？男子cos屈原跳河！" = "https://open.spotify.com/episode/7EbtVNbyC4y8VOLoEoU8Zp"
"S5怪新聞#47｜舅舅生日送花圈求婚，外甥女巧克力淋全身！ft. 烘焙師小羅" = "https://open.spotify.com/episode/1LBC71LHO3SuI758o56s9O"
"S5三尼聊 #21｜泰國潑水節超好玩卻發生性騷擾事件！幸好有美麗泰服照療癒～" = "https://open.spotify.com/episode/2RfAThYmKrwLT1Fw2HukWE"
"S5怪新聞#46｜生日帶睪丸進棺材，玩具車意外墮胎！ft. 廖文強" = "https://open.spotify.com/episode/4WunpG36OxMgtM877FYSGv"
"S5三尼聊 #20｜泰國最美沙美島這樣玩！度假到一半發生大麻 煩？" = "https://open.spotify.com/episode/0UwI65ecOZ6loMedyLiFFE"
"S5怪新聞#45｜萬物叫春！春天來了小心桃花癲，販賣機給你好姻緣！" = "https://open.spotify.com/episode/4xvZpbdBOuBy7Q7j2Fb7Ot"
"S5三尼聊#19｜前列腺高潮的爽有多爽？約到雷炮還要演得像金馬影后？ ft. 紅犀牛 Jessie" = "https://open.spotify.com/episode/4bFdlGGVZoNDbYNyBWn9lY"
"S5怪新聞#44｜清明節卡陰破解方法一次聽！聊到後面快吵起來><" = "https://open.spotify.com/episode/2AODKL2Ppz6ukmZSIF606e"
"S5怪新聞#43｜163隻活螞蟻搭乘粉紅超跑喝星巴克！" = "https://open.spotify.com/episode/277AfDxbTojCY7doAzsAse"
"S5三尼聊#18｜泰會拉！智慧哥的Thailand變成Lalaland" = "https://open.spotify.com/episode/2eF4v5oRVSGqlcmZb7FGQ8"
"S5三尼聊#17｜性愛小教室上課囉！塞跳蛋逛賣場的羞恥play？口交、按摩棒、3P技巧大公開！ ft. 紅犀牛 Jessie" = "https://open.spotify.com/episode/07vqWkrp4SLAnumxSczPiM"
"S5怪新聞#42｜乞丐嘴含蟑螂想吃牢飯，菩薩比OK！ft.許淨淳" = "https://open.spotify.com/episode/13BtwMObXHDbCHXopPqIFs"
"S5三尼聊#16｜無法下標的一集。" = "https://open.spotify.com/episode/27qn1o7qsoIJFVrXTAKNNC"
"S5怪新聞#41｜爛臉人妻按摩吃薯條，與聰明狗狗開戰94屌！ft. Jocelyn9.4.0" = "https://open.spotify.com/episode/3jK5OC7vmNkykSYqjnh1q8"
"S5怪新聞#40｜過年特輯：龍重歡迎林森北路紅牌，脫衣洗澡樣樣來！ft. 金曲歌王許富凱" = "https://open.spotify.com/episode/5h1fyaDTSM2g9sJdXFrX56"
"S5怪新聞#39｜半熟GG！麵包超人舔腳趾，想和空服員搞曖昧？ft. 理想混蛋" = "https://open.spotify.com/episode/6D2wPKuwRzRNafFVmSbTId"
"S5怪新聞#38｜天氣冷冷缺溫暖，三尼給你三溫暖♨️" = "https://open.spotify.com/episode/4ZRxY9Ic8isAEzei8VqTKh"
"S5怪新聞#37｜生死擂台賽：水行俠、哥吉拉、咒術迴戰大亂鬥！ft. 你所不知道的守夜人" = "https://open.spotify.com/episode/0E5XcngvClFkYWa5iskgLK"
"S5三尼聊#15｜2024三尼許願池：聽完發大財，桃花朵朵開！" = "https://open.spotify.com/episode/3JFCfj9wLDrJQuIQY0o6jl"
"S5怪新聞#36｜矽膠娃娃伸舌舔路燈，慘遭小鳥電鍋燙！ft.蓋兒Gail" = "https://open.spotify.com/episode/2JARKyc6orJqKyuFLy74OH"
"S5怪新聞#35｜2023最終集！興奮聖誕老婆婆和同事偷吃後，罹患金屬怪病！" = "https://open.spotify.com/episode/7pHg2ATgi6XxjL7BmCn0kO"
"S5三尼聊#14｜單飛不解散の日本行：奇聞逸事＋不藏私推薦＋花費大公開！" = "https://open.spotify.com/episode/6YPodY8QLM4sVptLWnIwZG"
"S5三尼聊#13｜當兵也要很有智慧！智慧哥的大兵日記來囉！" = "https://open.spotify.com/episode/1Ne4Tchswq8OTcp8fTVHAn"
"S5怪新聞#34｜雨傘怪獸吃吐司穿婚鞋，進行氣球葬！ft.苗博雅" = "https://open.spotify.com/episode/38gMlxMdJ6MgcMwlv0rpW2"
"S5怪新聞#33｜CHAT GPT新功能，呼呼各位感冒的人！" = "https://open.spotify.com/episode/0P4vaD1zvXiADp9SyiZlrf"
"S5怪新聞#32｜魔鏡啊魔鏡，網紅女巫用黑魔法詛咒前男友的小黃瓜！" = "https://open.spotify.com/episode/3AkHqLqolRqStBuW9hDEqX"
"S5怪新聞#31｜秋天米其林啾啾啾，小三車震好害羞！" = "https://open.spotify.com/episode/3LKhJdpzcRAH4aUdLX34bE"
"S5三尼聊#12｜秋意濃濃感情多，混亂情緒聽尼說～" = "https://open.spotify.com/episode/6XEQcfhOCg9Hzuh8k6RfgA"
"S5三尼聊#11｜藍帶甜點師、超級紅娘專家！來聽聽身障創業家的翻轉故事！" = "https://open.spotify.com/episode/3xiovHSxZOsiup2N6xb77v"
"S5怪新聞#30｜瘋！渣男為愛揮霍、全村斷電 ，狂飆半個台中被趕下車！ft. 李佳歡、蔡恩雨" = "https://open.spotify.com/episode/1PAVf0EbpLHfQN8shQvZqq"
"S5怪新聞#29｜洗衣怪客邊游泳邊脫褲， 鯊魚海豚笑稱：一無是處！ft. K6劉家凱" = "https://open.spotify.com/episode/6Cw7yeACxLBxrXSOIEZRDx"
"S5怪新聞#28｜雙十節開運妙招快來試試！挪威國慶高中生最愛在圓環＿ ＿？" = "https://open.spotify.com/episode/1Y4NvWZPmCAep55MJuNMLz"
"S5三尼聊#10｜台灣美國文化差很大？交往前要先約ＯＯ！ft.Ivy、明昉" = "https://open.spotify.com/episode/4RtBWKfF9EfGTkgAjR4hxf"
"S5怪新聞#27｜水溝蓋冒出詭異人髮，男子單身60年獲得搞笑諾貝爾獎！" = "https://open.spotify.com/episode/44nhWMeTWOFuXxRvi7iBdC"
"S5怪新聞#26｜驚奇！乳房開洞戴雞戒指，大媽的南瓜深不可測！" = "https://open.spotify.com/episode/7j1JkebLFHW3VUmOrf270O"
