[spotify]
"娛人的喜劇日常 EP.23｜工作時最討厭遇到的奧客 #陌生訊息" = "https://open.spotify.com/episode/0NucSAtT1f5WbNCXTS8Uqp"
"娛人喜劇日常 EP.22｜現場喜劇的後台秘辛！丹利演出中大笑場" = "https://open.spotify.com/episode/7ngTVKUAsilZ2PwksBNNVn"
"娛人喜劇日常EP.21｜最怕遇到的旅遊地雷！品妤回娘家抱怨" = "https://open.spotify.com/episode/2MzHIBpVgIgqgQYuliXc4O"
"娛人的喜劇日常EP.20｜木星分手17年男友內幕公開！" = "https://open.spotify.com/episode/04AplgmrUQrVG2bPHwB9zr"
"娛人的喜劇日常 EP.19｜丹利跟尼尚曾經一起睡過雞舍 #陌生訊息" = "https://open.spotify.com/episode/2yRcaxFUAxPc20TQjjBdw0"
"娛人的喜劇日常 EP.18｜娛人的憂憂、阿焦是誰呢？怒怒竟然是ＸＸ！" = "https://open.spotify.com/episode/6rkLgLjTOPZgrlMU7ONuzN"
"娛人的喜劇日常 EP.17｜娛人Podcast第100集！娛人觀看紀錄都是什麼？" = "https://open.spotify.com/episode/3sAp5f7Xbv5iIAmij4JauY"
"娛人的喜劇日常 EP.16｜男生為什麼容易早死？奇怪直男遊戲 feat. 菜冠雙頭 冠冠" = "https://open.spotify.com/episode/2sy9GBfdznDHS0x9IwjKix"
"娛人的喜劇日常EP.15｜娛人情書大公開，丹利以前叫ＸＸ？靖兒竟是校草！" = "https://open.spotify.com/episode/5F6UAEAI8OHIRbvWm4uC4x"
"娛人的喜劇日常EP.14｜娛人的性愛自修室 feat. 紅犀牛Jessie" = "https://open.spotify.com/episode/7MetFwE287Fdyh6thPhdwk"
"娛人的喜劇日常EP.13｜已有閨？活網？現在高中生流行什麼！娛人懂嗎？" = "https://open.spotify.com/episode/1A2RK36ABocWSxug2w2W2g"
"娛人的喜劇日常EP.12｜董仔說交往前試車很重要！海力化解這群人的公關危機？" = "https://open.spotify.com/episode/1bEV92laz6jfBcGYUZjewu"
"娛人的喜劇日常EP.11｜一起快樂聊聊老闆的靠X事 #靖止進入" = "https://open.spotify.com/episode/6yGjURGFDuvdfN08dlKMvB"
"娛人的喜劇日常EP.10｜室友手機相簿裡，滿滿的是他偷拍我的XX。陌生訊息" = "https://open.spotify.com/episode/60i9UuBgjM5n7ewoRXfTzA"
"娛人的喜劇日常EP.9｜小蓉包希望爸爸是無尊？喜劇演員的爸爸一定要好笑吧！" = "https://open.spotify.com/episode/5LYuwFNw6D6ALjF8kOvD8c"
"娛人的喜劇日常EP.8｜愛情總是難解，娛人絕非正解！" = "https://open.spotify.com/episode/2pbbEyWoYGMsTX8B1RusQ0"
"娛人的喜劇日常EP.7｜丹利被詐騙十萬（真人真事不改編）「馬哩咻」真實意思大公開！" = "https://open.spotify.com/episode/0LdjkdfmCLNzP6meO8bXmi"
"娛人的喜劇日常EP.6｜丹利十年未見沒分手的女友！靖兒參加婚禮遇到前女友？" = "https://open.spotify.com/episode/2tmfSVoPk026ru8v09Xi5b"
"娛人的喜劇日常EP.5｜娛人都會玩的泡泡浴？這集是我們最不想聊的主題！" = "https://open.spotify.com/episode/6yJs5pl48z7N4bmK36wxFK"
"娛人的喜劇日常EP.4｜奇葩室友！被室友打斷做愛，該怎麼辦？" = "https://open.spotify.com/episode/41TrWLdHuo67SRPS4bGglu"
"娛人的喜劇日常EP.3｜問男友：我今天心情不好買了麵包。娛人們的MBTI" = "https://open.spotify.com/episode/6MGQ4FYKyu0L0JeczW84xe"
"娛人的喜劇日常EP.2｜靖兒去算命與娛人的前世今生" = "https://open.spotify.com/episode/1gm1nJjLRNuUulyDZYH7Wa"
"娛人的喜劇日常EP.1｜電影《莎莉》導演來啦！喜德的交友軟體鬼故事" = "https://open.spotify.com/episode/50NosC0NDymujpZC6PIhpF"
"娛人的喜劇日常 Live Podcast｜靖兒喜歡品妤？尼尚愛過ＸＸ！【建議看影片完整版】" = "https://open.spotify.com/episode/6brkTaFjflBeKKR1Qw6OA0"
"娛人的喜劇日常 回歸特別篇｜我們回來了！" = "https://open.spotify.com/episode/3ssRBoaB53X5XnepU0kl6L"
"喜劇日常EP50｜最終集，再見！娛人愛你們！" = "https://open.spotify.com/episode/0CrPBfV2RYwNyy388IZQh9"
"喜劇日常EP49｜平價團長VS奢華團長ft.董軒" = "https://open.spotify.com/episode/4MesNd1igWB1jsjniSz7MT"
"喜劇日常EP48｜我完全沒有遺傳到他？" = "https://open.spotify.com/episode/5qerAqCQ1R0xkbt2xHFreP"
"愚新聞EP30｜最後一集還是要抓出愚新聞吧！" = "https://open.spotify.com/episode/1YsFRGT359oJNUiaIQ8hsd"
"喜劇日常EP47｜中文不好發生的糗事ft.三木" = "https://open.spotify.com/episode/4WPGdJPbvvYFsBhVeU3gTR"
"愚新聞EP29｜八件海洋你不知道的事" = "https://open.spotify.com/episode/5B5ebYORjp6oOSUQzF5vDY"
"喜劇日常EP46｜這次真的受傷了" = "https://open.spotify.com/episode/11NsrqKG6Eo1hB4A9UUuFz"
"愚新聞EP28｜竟然有這種習俗？" = "https://open.spotify.com/episode/1zfmIWhwf23d7TE18SpffP"
"喜劇日常EP45｜台灣人多沒禮貌？ft.太田" = "https://open.spotify.com/episode/6mtwP5LNcu1vXWZnCux89F"
"愚新聞EP27｜直男新聞夜" = "https://open.spotify.com/episode/1XmaWGcJiyOvFPL2hbGTha"
"喜劇日常EP44｜送禮學分及格了嗎？" = "https://open.spotify.com/episode/5D072IZwGNMAKF2Yl38NgA"
"愚新聞EP26｜世界上還有這種俱樂部" = "https://open.spotify.com/episode/6WnTAbkZCaFhCpZqeyaqqU"
"喜劇日常EP43｜確診時代，公主演出幕後篇ft. 劉向" = "https://open.spotify.com/episode/6geUTJ7Z7bYCuWl3JnQsBY"
"愚新聞EP25｜你不知道的偉人故事" = "https://open.spotify.com/episode/0keTzj6POv5icMdyBWCz9A"
"喜劇日常EP42｜娛人團遊去澎湖找外婆" = "https://open.spotify.com/episode/5WrGHzngMkeXaEHcqd7K37"
"喜劇日常EP41｜浪漫Luck ft.傻孩子Luke" = "https://open.spotify.com/episode/7o5UEM1AreXF8HJmZ8Hyei"
"愚新聞EP24｜監獄娛風雲" = "https://open.spotify.com/episode/7jpWqKkRoiGj54kf442uY8"
"喜劇日常EP40｜我就雞X，最會拒絕人！" = "https://open.spotify.com/episode/63Yn6ScxIrgmOafO6rChKf"
"愚新聞EP23｜假新聞真爆笑" = "https://open.spotify.com/episode/5PlSYyrfAMZHFttOGl8Xvs"
"喜劇日常EP39｜驚喜驚嚇！大吃一ㄐㄧㄥ" = "https://open.spotify.com/episode/7LG0wUG6AHJ0bEvn7t8Tyt"
"喜劇日常EP38｜貓派、狗派、烏龜派？" = "https://open.spotify.com/episode/1U6Shfzb4W0EKfJqRVKfhT"
"愚新聞EP22｜正港台灣人你不知道的事" = "https://open.spotify.com/episode/0sdwcgjK6Pckd5Z4Lv8TDz"
"喜劇日常EP37｜台灣AV真實拍攝現場 ft.哈姆" = "https://open.spotify.com/episode/6yxHdgxz70HfndIQ8XErn8"
"愚新聞EP21｜夏天來點冷知識" = "https://open.spotify.com/episode/36ns7SlRLHZS6piGpjjzMX"
"喜劇日常EP36｜ 你做夢！全面啟動娛人版" = "https://open.spotify.com/episode/37qmo1PpMn7oLeqJAe0Sk6"
