[spotify]
"【呱吉直播】呱吉電台EP189：臭就是救" = "https://open.spotify.com/episode/6tofHCBsi1nUcT8Q1XNwB2"
"【呱吉】新資料夾(201)：️Are you 受到委屈？" = "https://open.spotify.com/episode/7JTT9wZ0Iurz9chiegJbXz"
"【呱吉直播】陪你睡覺EP10：諾亞方舟" = "https://open.spotify.com/episode/1t0uVAHzn0J9U56gkkhsjl"
"【新資料夾】黑歷史特輯EP4：起立，立正，敬禮！" = "https://open.spotify.com/episode/44juu9XKveaSQ0d8HG6cTG"
"【呱吉】新資料夾(200)：️重錄之神降臨" = "https://open.spotify.com/episode/3a8xS5bmRLDfLkYr7rTMJN"
"【呱吉電台】EP188：一定是因為想吃澳洲牛奶公司" = "https://open.spotify.com/episode/2hd8AN3faKFk5muKt9ebOL"
"【新資料夾】黑歷史特輯EP3：烏魚子安全網" = "https://open.spotify.com/episode/0AqqPyAdEY2jz40YqzCD8w"
"【呱吉】新資料夾(199)：️從糟糕變成難以理解" = "https://open.spotify.com/episode/6ozOoYJLsASBhVqggWJTrT"
"【呱吉直播】他的播放清單EP8：I wannasleep 你行不行" = "https://open.spotify.com/episode/0GbbQXbLA8PBeFrLCd5oAT"
"【呱吉】新資料夾(198)：️有sense的節目" = "https://open.spotify.com/episode/66qy2Qn185UkGbx8dlVfNU"
"【新資料夾訪談】八「嘎」鴨肉，蔡桑！（來賓：蔡阿嘎、二伯）" = "https://open.spotify.com/episode/65IH5TSaPs5vMhJ3mlrPmK"
"【呱吉】新資料夾(197)：️愛雞成翅" = "https://open.spotify.com/episode/2PuYnhAn6k75FwwyaaPnD8"
"【呱吉直播】呱吉電台EP185：卡啦永遠OK" = "https://open.spotify.com/episode/6bW4FvCeNmPYdhjdjxO4dH"
"【呱吉】新資料夾(196)：️今天我負能量" = "https://open.spotify.com/episode/2aaQQdmRzGb4GrO9yrCRmD"
"【呱吉直播】週末電視指南EP7：大衛芬奇一定沒問題的吧" = "https://open.spotify.com/episode/7LdeZ4ASIG52Ee2CriCfTb"
"【呱吉】新資料夾(195)：️人生要有點缺憾" = "https://open.spotify.com/episode/3A1YGOHY8XW410XRkOhM5Y"
"【呱吉直播】陪你過颱風EP1：阿公叫你看電視（夏夜怪談EP4）" = "https://open.spotify.com/episode/2AAoW0Y6PIZ5MpEw6bOyAL"
"【呱吉】新資料夾(194)：️背後原因令人暖心" = "https://open.spotify.com/episode/3JddwxLEyAmYk9qvXV51Yx"
"【呱吉】新資料夾(193)：️無聊的老男人" = "https://open.spotify.com/episode/1z3rizT1j2XZnJ6tWiAptp"
"【呱吉直播】呱吉電台EP183：北極公路終點的幸運兒" = "https://open.spotify.com/episode/213rYvDIcdpezdMsKlf1cD"
"【呱吉】新資料夾(192)：️不要給我騙" = "https://open.spotify.com/episode/2kylysPxUf7Tzbk3VWgeKK"
"【呱吉】新資料夾(191)：️我叫你笑" = "https://open.spotify.com/episode/7Gi9abAsrsShwFYauyUkuv"
"【新資料夾】黑歷史特輯EP2：飲水300CC，喝水！" = "https://open.spotify.com/episode/4MzLaixsJ9IrthrWMTf2gL"
"【呱吉直播】呱吉電台EP182：你老闆怎麼那麼有錢？" = "https://open.spotify.com/episode/65prXQDJ8eDb7vKeMISUuX"
"【新資料夾】黑歷史特輯EP1：死屁孩視訊愛愛" = "https://open.spotify.com/episode/2fXpASMGEHFn4iTJvwyPCT"
"【呱吉直播】那些遺落在2023年的秘密#2：抱歉了培根" = "https://open.spotify.com/episode/3UJjmj8ey06X5hug7jYrhy"
"【呱采訪談】2024.06.24，徐漢強來上節目了。" = "https://open.spotify.com/episode/0RyC2igceik7qgdf5DEM5i"
"【呱吉】新資料夾(190)：️真的很點點點" = "https://open.spotify.com/episode/3wYf0zAszhcDkXWPaedwD5"
"【呱吉直播】呱吉電台EP181：健身人沒時間看影片" = "https://open.spotify.com/episode/2Pu3creIvLqmFnZpDULlY4"
"【呱吉】新資料夾(189)：️調皮屌蛋" = "https://open.spotify.com/episode/6Vm7kbR4l1uPr5LZAUicEW"
"【呱吉】新資料夾(188)：️月經常掛在天上" = "https://open.spotify.com/episode/2NjlOcKlgxXUSgav6g46KC"
"【呱吉】新資料夾(187)：️夢遺落的新聞" = "https://open.spotify.com/episode/2uPfgoAzx79M6MXzGbiYRK"
"【呱吉】新資料夾(186)：️單身犯法" = "https://open.spotify.com/episode/3yTYmHB5qDY5LplQf7QYvj"
"【呱吉直播】呱吉電台EP180：你把大哥吹死啦！" = "https://open.spotify.com/episode/0QBModFlxbJY9HUNkQJVVp"
"【呱吉】新資料夾(185)：️生氣不可到日落" = "https://open.spotify.com/episode/2o0yjtsNFgwwEUCmz0hrP1"
"【呱吉直播】呱吉電台EP179：台灣金卡戴珊" = "https://open.spotify.com/episode/6XfFFaGsTkGp23iB8MD9h5"
"【呱吉】新資料夾(184)：️大人帝國的反擊" = "https://open.spotify.com/episode/1XG9eEETEtthxIDaNDTD6y"
"【呱吉直播】呱吉電台EP178：全身名牌的前議員" = "https://open.spotify.com/episode/5Hjgqjs5jTz31CfXq2Twph"
"【呱吉Podcast】新資料夾(183)：️笑死過時了????" = "https://open.spotify.com/episode/4nA4lYLpempDu6zO7e20MJ"
"【呱吉Podcast】我是混蛋嗎EP7：️褲友難題" = "https://open.spotify.com/episode/2nFqvuLplU7vEIp8B2k61A"
"【呱吉直播】呱吉電台EP177：苗上人度化精怪 重修金身" = "https://open.spotify.com/episode/4wQu2v9bDRbj5zAa3gm1T1"
"【呱吉Podcast】新資料夾(182)：️毒資料夾" = "https://open.spotify.com/episode/4JiH0jYVu26yl7kvdFLY9l"
"【呱吉直播】呱吉電台EP176：你知道你是最藍的嗎？" = "https://open.spotify.com/episode/7oETPyJdNj5VpGDbcAQo1i"
"【呱吉Podcast】新資料夾(181)：️2070年你幾歲？" = "https://open.spotify.com/episode/0PrECNp5cJOi6fNQpHoUEr"
"【呱吉直播】呱吉電台EP175：目前可知食物中毒高機率為食物引起" = "https://open.spotify.com/episode/3VGwq42ZKibldoqNhYGjk6"
"【呱吉Podcast】新資料夾(180)：️船過水有痕" = "https://open.spotify.com/episode/0WpaJIcFqr58l5YmbeSqCU"
"【呱吉直播】呱吉電台EP174：大聯盟愛情故事" = "https://open.spotify.com/episode/2XlxnseuhyvcRrh89fdmIO"
"【呱吉Podcast】新資料夾(179)：️Ye" = "https://open.spotify.com/episode/4Q0a3YrtRFi220aLBS9EVl"
"【呱吉直播】呱吉電台EP173：性高潮後疾病症候群" = "https://open.spotify.com/episode/2RaTEdurdW1ZEdPCi1Yyl9"
"【呱吉Podcast】新資料夾(178)：️毛豬萬歲！" = "https://open.spotify.com/episode/0MvEfrpZa83qyyDkcVshZl"
"【呱吉直播】呱吉電台EP172：你知道那個誰誰誰是我捧紅的嗎？" = "https://open.spotify.com/episode/6uu6I45yjUbmbcYwrhctph"
"【呱吉Podcast】新資料夾(177)：️鉛筆恐怖故事" = "https://open.spotify.com/episode/1pqtGEf4CVhdHUazfVbDjB"
"【呱吉直播】呱吉電台EP171：你四年前八年前十二年前的今天在幹嘛" = "https://open.spotify.com/episode/5eUNdHogbJQ7V2pxMMHoAP"
