"EP82｜火的魔法 ft.江江老師" = "Jun 2024"
"EP81｜紫色火焰2.0" = "May 2024"
"EP80｜讓艾莉絲來教你生命靈數" = "May 2024"
"EP79｜芳香療法天后來了 ft.GINA 許怡蘭" = "May 2024"
"EP78｜閒聊黃金紀元" = "May 2024"
"靜心頌缽 ft. 頌缽療癒師 Ashley 愛希" = "May 2024"
"EP77｜頌缽師 ft. 頌缽療癒師 Ashley 愛希" = "May 2024"
"EP76｜開悟七脈輪" = "Apr 2024"
"EP75｜不想長大的人" = "Apr 2024"
"EP74｜跟母娘們請安" = "Apr 2024"
"EP73｜閒聊雞湯" = "Apr 2024"
"EP72｜財神續集" = "Mar 2024"
"EP71｜姻緣還看業力平衡?!" = "Mar 2024"
"EP70｜命運設計系主任來了 feat.簡少年" = "Mar 2024"
"EP69｜我們去寵物溝通了！ft.金妮、小胖" = "Mar 2024"
"EP68｜靈魂表演課 ft.朱宏章老師" = "Mar 2024"
"EP67｜聖塔庫瑪拉" = "Feb 2024"
"EP66｜好面相 ft.里民服務中心" = "Feb 2024"
"EP65｜除夕特別節目 ft.善嵐慶女" = "Feb 2024"
"EP64｜批量生產の貴人" = "Feb 2024"
"EP63｜神仙雜貨殿" = "Jan 2024"
"EP62｜東方靈數" = "Jan 2024"
"EP61｜套房臥室風水" = "Jan 2024"
"EP60｜2024 你想聽什麼主題呢？" = "Jan 2024"
"EP59｜催眠 ft.莫彼" = "Dec 2023"
"EP58｜丹公解夢完結" = "Dec 2023"
"EP57｜人類圖 feat.路嘉怡" = "Dec 2023"
"EP56｜丹公解夢 4" = "Dec 2023"
"EP55｜高我2.0 feat.一咪" = "Dec 2023"
"EP54｜風水問答集" = "Nov 2023"
"EP53｜客廳風水" = "Nov 2023"
"EP52｜靈性周歲｜神仙補習班一歲了！" = "Nov 2023"
"EP51｜校園暴徒！" = "Nov 2023"
"EP50｜揚升囉！" = "Oct 2023"
"EP49｜靈擺敲門班" = "Oct 2023"
"EP48｜奇蹟來敲門" = "Oct 2023"
"EP47｜丹公解夢三" = "Oct 2023"
"EP46｜擴大療癒法 ft.瓦遇" = "Sep 2023"
"EP45｜靈擺幼幼班" = "Sep 2023"
"EP44｜WHY?! 丹公解夢第二集" = "Sep 2023"
"EP43｜次元維度 x 平行宇宙 " = "Sep 2023"
"EP42｜分離感 ft.小光" = "Sep 2023"
"EP41｜雙生火焰" = "Aug 2023"
"EP40｜WHY?! 丹公解夢第一集" = "Aug 2023"
"EP39｜鬼月 ft.謝寶" = "Aug 2023"
"EP38｜守護天使 4ni？！" = "Aug 2023"
"EP37｜不專業塔羅自學之術 ft. ReRe" = "Jul 2023"
"EP36｜五行補課 ft. ReRe" = "Jul 2023"
"EP35｜丹丹去學寵物溝通！ft.金妮、小胖" = "Jul 2023"
"EP34｜星座不準？太陽月亮上升怎麼看！" = "Jul 2023"
"EP33｜生命靈數" = "Jun 2023"
"EP32｜童年 貳" = "Jun 2023"
"EP31｜五行求職信" = "Jun 2023"
"EP30｜我們一起靈性出櫃吧！Ft.阿寶" = "Jun 2023"
"本週運勢｜6/5 - 6/11" = "Jun 2023"
"EP29｜靈魂契約" = "Jun 2023"
"本週運勢｜5/29 - 6/4" = "May 2023"
"EP28｜直男你說阿 ft.邱搞、黃洄" = "May 2023"
"本週運勢｜5/22 - 5/28" = "May 2023"
"Meditation｜The Great Soul Sync. （無教學版）" = "May 2023"
"EP27｜早安，透過冥想開啟新的小宇宙⭐" = "May 2023"
"本週運勢｜5/15 - 5/21" = "May 2023"
"EP26｜命會不會越算越差呢？" = "May 2023"
"本週運勢｜5/8 - 5/14" = "May 2023"
"EP25｜鬼故事笑話冠軍🏆 ft.廖原慶" = "May 2023"
"本週運勢｜5/1 - 5/7" = "May 2023"
"EP24｜十年前把機會留給依霖的貴人 ft.廖原慶" = "Apr 2023"
"Meditation｜The Great Soul Sync. 來自印度的靈魂同步靜心冥想♥️" = "Apr 2023"
"本週運勢｜4/24 - 4/30 " = "Apr 2023"
"EP23｜夢" = "Apr 2023"
"本週運勢｜4/17 - 4/23" = "Apr 2023"
"Ep22｜聽不爛的愛情故事，戀愛桃花運遇見對的人🌹" = "Apr 2023"
"本週運勢｜4/10 - 4/16" = "Apr 2023"
"EP21｜高我的得力助手指導靈 ft.黃香" = "Apr 2023"
"本週運勢｜4/03 - 4/9 " = "Apr 2023"
"EP20｜財神駕到教你補財庫招財運" = "Mar 2023"
"本週運勢｜3/27 - 4/02" = "Mar 2023"
"EP19｜生命靈數九宮格-人際關係連連看" = "Mar 2023"
"Meditation｜擴展你光的管道 feat. 『紫色火焰』詔令💜🔥" = "Mar 2023"
"本週運勢｜3/20 - 3/26 " = "Mar 2023"
"EP18｜高我的最強搭配『紫色火焰』ft.小我皇后" = "Mar 2023"
"本週運勢｜03/13-03/19" = "Mar 2023"
"Ep17｜「擴療 賽斯 希塔 馬雅 靈氣」身心靈基礎養成入門攻略" = "Mar 2023"
"本週運勢｜03/06-03/12" = "Mar 2023"
"EP16｜能量風水 v.s 傳統風水 ft.小我皇后" = "Mar 2023"
"本週運勢｜02/27-03/05🎎🧝‍♀️🍀" = "Feb 2023"
"EP15｜黃金世紀來臨啦啦啦啦啦啦！！！" = "Feb 2023"
"本週運勢｜02/20-02/26 🔯" = "Feb 2023"
"EP14｜萬用處方籤『高我』ft.黃香" = "Feb 2023"
"本週運勢｜02/13-02/19  ♈ ♉ ♊" = "Feb 2023"
"EP13｜跨國婚姻真正的婆媳問題！ft.黃香" = "Feb 2023"
"本週運勢｜02/06-02/12🍀🍀🍀" = "Feb 2023"
"EP12｜星座補習班誰要被當掉夫妻當場開嗆" = "Feb 2023"
"本週運勢｜1/30-2/5 🧨🧨🧨" = "Jan 2023"
"EP11｜老師您賣水晶嗎？ Feat.老陳" = "Jan 2023"
"本週運勢｜1/23-1/29 🎉🎉🎉" = "Jan 2023"
"Meditation｜簡單粗暴之財富冥想篇" = "Jan 2023"
"EP10｜兔年快樂，新年無敵刷善緣法請小心服用！" = "Jan 2023"
"本週運勢｜1/16-1/22 🎉🎉🎉" = "Jan 2023"
"EP09｜喝孟婆湯也忘不了的前世記憶" = "Jan 2023"
"本週運勢｜1月9日到1月15日" = "Jan 2023"
"EP08｜森77脈輪" = "Jan 2023"
"本週運勢｜1月2日到1月8日🎉🎉🎉" = "Jan 2023"
"Ｍeditation｜Aura Cleansing 氛圍轉化" = "Jan 2023"
"EP07｜2023怎麼許願啦🙏🙏🙏🙏🙏" = "Dec 2022"
"本週運勢｜12/26-1/2 🎉🎉🎉" = "Dec 2022"
"EP06｜聽聖誕小故事順便上一堂紅酒課" = "Dec 2022"
"EP05｜退散！影響你童年的壞蛋！" = "Dec 2022"
"EP04｜靠北老闆之仙姑的辛酸，升官加爵，秘方傳授！" = "Dec 2022"
"EP03 | 月老你不要笑好嗎奇門遁甲招桃花之術！" = "Dec 2022"
"EP02 | 世足不負責預測之老師484數學天才？" = "Nov 2022"
"EP01 | 神仙補習班到底在補什麼？" = "Nov 2022"
