"EP82｜火的魔法 ft.江江老師" = "https://open.spotify.com/episode/53E6XbUnDVgJp31Pb4myzK"
"EP81｜紫色火焰2.0" = "https://open.spotify.com/episode/71fbwvVY2aRWZGYXoX0pCX"
"EP80｜讓艾莉絲來教你生命靈數" = "https://open.spotify.com/episode/39uoCooT3PFFpdnOJNGEsW"
"EP79｜芳香療法天后來了 ft.GINA 許怡蘭" = "https://open.spotify.com/episode/5YxFrHuxFo2Gtj3nkjkX7r"
"EP78｜閒聊黃金紀元" = "https://open.spotify.com/episode/4DJUzYKxwKYzAfHmMi28AX"
"靜心頌缽 ft. 頌缽療癒師 Ashley 愛希" = "https://open.spotify.com/episode/18fjV63djYen1lGfJJ3K0e"
"EP77｜頌缽師 ft. 頌缽療癒師 Ashley 愛希" = "https://open.spotify.com/episode/7BDny3gik3vspm68FLeLMR"
"EP77｜頌缽師 ft.Ashley" = "https://open.spotify.com/episode/7BDny3gik3vspm68FLeLMR"
"EP76｜開悟七脈輪" = "https://open.spotify.com/episode/0IzfQc9Sa2135U0Cvzk4aq"
"EP75｜不想長大的人" = "https://open.spotify.com/episode/5HlyGp7V7M4wTGTLXXqKv2"
"EP74｜跟母娘們請安" = "https://open.spotify.com/episode/7lLUnzf37bvjsnt1vi23xb"
"EP73｜閒聊雞湯" = "https://open.spotify.com/episode/5UTY6jprGilr0ceDFxMFPk"
"EP72｜財神續集" = "https://open.spotify.com/episode/7pClMuB3hHfTf3A6dBNwkC"
"EP71｜姻緣還看業力平衡?!" = "https://open.spotify.com/episode/5xgtg1mlfEsZNaM0pkqb3A"
"EP70｜命運設計系主任來了 feat.簡少年" = "https://open.spotify.com/episode/6DlXCPEUtx5FBqIuVJWvMC"
"EP69｜我們去寵物溝通了！ft.金妮、小胖" = "https://open.spotify.com/episode/3WRd8AbMLur459Fu3TZmbP"
"EP68｜靈魂表演課 ft.朱宏章老師" = "https://open.spotify.com/episode/6Fmw4FILBNE3F9Bn9f82Wh"
"EP67｜聖塔庫瑪拉" = "https://open.spotify.com/episode/4xgeFhAIj2Ivt0oxihtSQt"
"EP66｜好面相 ft.里民服務中心" = "https://open.spotify.com/episode/7HaUzpSJldQGbCEd31VX5w"
"EP65｜除夕特別節目 ft.善嵐慶女" = "https://open.spotify.com/episode/52kTj0iUdRZ9FvPMRjduDD"
"EP64｜批量生產の貴人" = "https://open.spotify.com/episode/5IvlYXySYhrUOTg3BvIibr"
"EP63｜神仙雜貨殿" = "https://open.spotify.com/episode/3U7sCh1Ka9zVOCwmRTBV7B"
"EP62｜東方靈數" = "https://open.spotify.com/episode/5QUxWXYFv3mqmpBRtOblWu"
"EP61｜套房臥室風水" = "https://open.spotify.com/episode/2kkhqJadJiVdzZNl285aOU"
"EP60｜2024 你想聽什麼主題呢？" = "https://open.spotify.com/episode/3Qi3TpL1VGj19z235GZWPG"
"EP59｜催眠 ft.莫彼" = "https://open.spotify.com/episode/2DPwGfUTVEWCiZ2rDUSoFB"
"EP58｜丹公解夢完結" = "https://open.spotify.com/episode/2mB79dipI0lws9z85mNKFj"
"EP57｜人類圖 feat.路嘉怡" = "https://open.spotify.com/episode/5FqaSyZiLOIVFUCvLCvLDK"
"EP56｜丹公解夢 4" = "https://open.spotify.com/episode/6oxzmBiazmbtg3TH3PpOIc"
"EP55｜高我2.0 feat.一咪" = "https://open.spotify.com/episode/0qDCQW9SiWoQziFDYblCjc"
"EP54｜風水問答集" = "https://open.spotify.com/episode/65c4iOyJFWbMXN3W4P78gu"
"EP53｜客廳風水" = "https://open.spotify.com/episode/1fwx86z8QOWNBrTis7Wmrk"
"EP52｜靈性周歲｜神仙補習班一歲了！" = "https://open.spotify.com/episode/4QV7DjEx6VtPZejQRhYSZD"
"EP51｜校園暴徒！" = "https://open.spotify.com/episode/526ftJr4d6C3UuWK3fqj1I"
"EP50｜揚升囉！" = "https://open.spotify.com/episode/7zuW62A3izYnklS2XPLKRu"
"EP49｜靈擺敲門班" = "https://open.spotify.com/episode/7tkFn2TImaZJyF4yh4Ga5d"
"EP48｜奇蹟來敲門" = "https://open.spotify.com/episode/0O5UbjMNrpCFwPkS5yLe5V"
"EP47｜丹公解夢三" = "https://open.spotify.com/episode/3YOs3MjpownSkeJVM1A3yf"
"EP46｜擴大療癒法 ft.瓦遇" = "https://open.spotify.com/episode/60cYCzYiW2PRCtNbnfb5Fy"
"EP45｜靈擺幼幼班" = "https://open.spotify.com/episode/0iINl2lIghRYt0AN9jS6ut"
"EP44｜WHY?! 丹公解夢第二集" = "https://open.spotify.com/episode/2ITjroLLFxdIW6fxC8lozn"
"EP43｜次元維度 x 平行宇宙" = "https://open.spotify.com/episode/0hvZTTSFDwUoHNr8DN577K"
"EP42｜分離感 ft.小光" = "https://open.spotify.com/episode/6f1VNeOiLjJyGVEfMllNbR"
"EP41｜雙生火焰" = "https://open.spotify.com/episode/5qEB6RyBx0e1jsGAupXaHa"
"EP40｜WHY?! 丹公解夢第一集" = "https://open.spotify.com/episode/1iKkrMtuf8WjpXk1H6w7tS"
"EP39｜鬼月 ft.謝寶" = "https://open.spotify.com/episode/3JZbvWZR8wBuAbC9fV0eUo"
"EP38｜守護天使 4ni？！" = "https://open.spotify.com/episode/7fwQ3G1L5GAwiXCUCoyfq6"
"EP37｜不專業塔羅自學之術 ft. ReRe" = "https://open.spotify.com/episode/7bjH8S4eqrdkgrNi2NOU7i"
"EP36｜五行補課 ft. ReRe" = "https://open.spotify.com/episode/2gxjgMsTRBq1YLt4rFmTIz"
"EP35｜丹丹去學寵物溝通！ft.金妮、小胖" = "https://open.spotify.com/episode/7g5tS8zgfBVdAsxcZPU0x3"
"EP34｜星座不準？太陽月亮上升怎麼看！" = "https://open.spotify.com/episode/3xUF3pM1Rt4MRsoKIZdBtH"
"EP33｜生命靈數" = "https://open.spotify.com/episode/5QB60mhAyP9uStDrI89dKf"
"EP32｜童年 貳" = "https://open.spotify.com/episode/1dBoNARjvSa2imCQwwy21v"
"EP31｜五行求職信" = "https://open.spotify.com/episode/65YM7WitH7SPorYPMTdYF4"
"EP30｜我們一起靈性出櫃吧！Ft.阿寶" = "https://open.spotify.com/episode/54It4UHF387WmH4Xt6YqF6"
"本週運勢｜6/5 - 6/11" = "https://open.spotify.com/episode/05usGeaAycfoRdr4PdvRDV"
"EP29｜靈魂契約" = "https://open.spotify.com/episode/1fbUwknT4HCGHocJkNMY5w"
"本週運勢｜5/29 - 6/4" = "https://open.spotify.com/episode/7nRUZEwGNxPvwGDa3d0Zu4"
"EP28｜直男你說阿 ft.邱搞、黃洄" = "https://open.spotify.com/episode/0JRCUtfg2CUdiBnKJcqDmo"
"本週運勢｜5/22 - 5/28" = "https://open.spotify.com/episode/0cXI3pySAcjlH0SHbNHYfb"
"Meditation｜The Great Soul Sync. （無教學版）" = "https://open.spotify.com/episode/5Tv8lCtWSwVQxenB8tATqo"
