"【四月運勢】一起進入火的世界 #2025" = "extra"
"4/14-4/20｜星座運勢週報｜唐綺陽" = "extra"
"以後就請丁老師來幫我代班拍週報了😂？#丁噹 #你為什麼說謊" = "extra"
"【唐陽雞酒屋】跟自己長很像的人ft.丁噹" = "extra"
"12星座的拖延症秘密👀 拖延症原因竟是太有把握？" = "extra"
"4/21-4/27｜星座運勢週報｜唐綺陽" = "extra"
"希望今晚帶給你們一些療癒 2025/4/22" = "extra"
"4/28-5/4｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜命運之輪轉動的五月｜五月運勢" = "extra"
"【唐陽雞酒屋】靈媒所看見的未來ft.靈媒媽媽 @Ruowen" = "extra"
"5/5-5/11｜星座運勢週報｜唐綺陽" = "extra"
"【五月運勢】冥王星逆行 清掉你的卡關能量 #2025" = "extra"
"5/12-5/18｜星座運勢週報｜唐綺陽" = "extra"
"心靈充電時間到了 2025/5/13" = "extra"
"5/19-5/25｜星座運勢週報｜唐綺陽" = "extra"
"5/26-6/1｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜神奇的六月｜六月運勢" = "extra"
"6/2-6/8｜星座運勢週報｜唐綺陽" = "extra"
"6/9-6/15｜星座運勢週報｜唐綺陽" = "extra"
"【六月運勢】你這邊有反轉的劇情發生嗎？ #2025" = "extra"
"【唐陽雞酒屋】善良真的會有好事 ft.周蕙" = "extra"
"6/16-6/22｜星座運勢週報｜唐綺陽" = "extra"
"6/23-6/29｜星座運勢週報｜唐綺陽" = "extra"
"【聊聊最近大家擔心的事】2025.6.18 LINE VOOM直播完整版" = "extra"
"2025下半年氛圍｜ 2025/6/26直播" = "extra"
"6/30-7/6｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜沒有末日，好好活著｜七月運勢" = "extra"
"勇敢去做就對了，你沒有錯! #水星 #開創星座 #2025" = "extra"
"2025獅子座｜下半年運勢｜唐綺陽｜Leo forecast for the second half of 2025" = "extra"
"2025雙魚座｜下半年運勢｜唐綺陽｜Pisces forecast for the second half of 2025" = "extra"
"2025雙子座｜下半年運勢｜唐綺陽｜Gemini forecast for the second half of 2025" = "extra"
"2025水瓶座｜下半年運勢｜唐綺陽｜Aquarius forecast for the second half of 2025" = "extra"
"2025牡羊座｜下半年運勢｜唐綺陽｜Aries forecast for the second half of 2025" = "extra"
"2025巨蟹座｜下半年運勢｜唐綺陽｜Cancer forecast for the second half of 2025" = "extra"
"2025魔羯座｜下半年運勢｜唐綺陽｜Capricorn forecast for the second half of 2025" = "extra"
"2025處女座｜下半年運勢｜唐綺陽｜Virgo forecast for the second half of 2025" = "extra"
"2025金牛座｜下半年運勢｜唐綺陽｜Taurus forecast for the second half of 2025" = "extra"
"2025天蠍座｜下半年運勢｜唐綺陽｜Scorpio forecast for the second half of 2025" = "extra"
"2025天秤座｜下半年運勢｜唐綺陽｜Libra forecast for the second half of 2025" = "extra"
"2025射手座｜下半年運勢｜唐綺陽｜Sagittarius forecast for the second half of 2025" = "extra"
"7/7-7/13｜星座運勢週報｜唐綺陽" = "extra"
"【七月運勢】能量場轉換，很多神奇的事會發生 #2025" = "extra"
"2025下半年一起用精神力改變世界💪🏻 #2025" = "extra"
"水逆對分，12星座最近的糾結｜ 2025/7/10直播" = "extra"
"7/14-7/20｜星座運勢週報｜唐綺陽" = "extra"
"巨蟹VS天蠍到底誰會贏？🔥 #巨蟹 #天蠍" = "extra"
"7/21-7/27｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】內耗仔其實潛力很高 ft.周慕姿" = "extra"
"7/28-8/3｜星座運勢週報｜唐綺陽" = "extra"
"你以為是自我反省，但其實是內耗🎧441 #內耗 #周慕姿" = "extra"
"唐綺陽直播｜療癒自己的八月｜八月運勢" = "extra"
"8/4-8/10｜星座運勢週報｜唐綺陽" = "extra"
"【八月運勢】沒有什麼事情是永遠的 #2025" = "extra"
"8/11-8/17｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜沒有什麼事情是永遠的八月｜八月運勢" = "extra"
"水逆後，12星座該收拾的殘局在哪？｜ 2025/8/14直播" = "extra"
"8/18-8/24｜星座運勢週報｜唐綺陽" = "extra"
"被輾碎才能造就全新的你，12星座被輾碎的地方｜ 2025/8/21直播" = "extra"
"8/25-8/31｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】不是聰明就夠了ft.侯文詠" = "extra"
"9/1-9/7｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜發現新可能性的九月｜九月運勢" = "extra"
"唐綺陽直播｜發現新可能性的九月｜2025 9月運勢" = "extra"
"【九月運勢】新世界已經打開，該往前走了 #2025" = "extra"
"9/8-9/14｜星座運勢週報｜唐綺陽" = "extra"
"最近心比較亂，一起找回安定的心｜ 2025/9/11直播" = "extra"
"【唐陽雞酒屋】當個混蛋才能保護人ft.博恩 @StandupBrian" = "extra"
"9/15-9/21｜星座運勢週報｜唐綺陽" = "extra"
"9/22-9/28｜星座運勢週報｜唐綺陽" = "extra"
"9/29-10/5｜星座運勢週報｜唐綺陽" = "extra"
