"海王星，給你大好或大壞" = "extra"
"EP319 占星冷知識 (水瓶的淚腺?" = "extra"
"EP352月亮星座，你藏最深的脆弱面(下)" = "extra"
"EP328 戀愛都市傳說7 你的愛情模式" = "extra"
"EP345 冥王星，充滿誘惑的重生之路(下)" = "extra"
"Ep350 天底星座，影響你巨大的根源" = "extra"
"EP353天底星座（下），影響你巨大的根源" = "extra"
"EP361 原來12星座這樣算討厭你😳" = "extra"
"EP361 12星座怎樣算討厭你😳" = "extra"
"【本週提醒】珍惜木星給的勇氣💪🏼" = "extra"
"EP373 還是要相信愛情啦ft. 影后導演嚴藝文、詹懷雲" = "extra"
"EP376 火星帶來的傷害性🔥" = "extra"
"什麼！魔羯座也會哭？12星座，想哭的時候" = "extra"
"12星座想哭的時候💦 #唐綺陽xVogue" = "extra"
"3/18-3/24｜星座運勢週報｜唐綺陽" = "extra"
"3/25-3/31｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】感情不順都是肝的問題？ft.簡少年" = "extra"
"各位小心肝，請小心肝。" = "extra"
"唐綺陽直播｜水逆的四月｜四月運勢" = "extra"
"4/1-4/7｜星座運勢週報｜唐綺陽" = "extra"
"今早6點正式水逆啦！#占星 #水逆 #星座" = "extra"
"4/8-4/14｜星座運勢週報｜唐綺陽" = "extra"
"【風象星座篇】水逆的四月 #四月運勢" = "extra"
"【火象星座篇】水逆的四月 #四月運勢" = "extra"
"【水象星座篇】水逆的四月 #四月運勢" = "extra"
"【土象星座篇】水逆的四月 #四月運勢" = "extra"
"焦慮代表你靈魂挺有野心的🎧EP310 #30歲 #長大 #壓力 #焦慮" = "extra"
"4/15-4/21｜星座運勢週報｜唐綺陽" = "extra"
"最難追星座男，好好先生都上榜了🤪" = "extra"
"你心目中最難追的星座是…？ #唐綺陽xVogue #星座#難追 #感情" = "extra"
"【唐陽雞酒屋】道理我都懂，啊又做不到ft.周慕姿" = "extra"
"4/22-4/28｜星座運勢週報｜唐綺陽" = "extra"
"社恐I人，會社交，但電池量過低🪫🤪#MBTI #16型人格 #占星" = "extra"
"【唐陽雞酒屋】向宇宙下訂單的體質 ft.蔡健雅" = "extra"
"4/29-5/5｜星座運勢週報｜唐綺陽" = "extra"
"天註定？不一定 #運勢 #占星 #命運" = "extra"
"你是改寫命運的導演 #運勢 #占星 #命運" = "extra"
"週報又被分到累的？其實不用怕😌 #週報 #累 #占星" = "extra"
"唐綺陽直播｜可以勇敢改變的五月｜五月運勢" = "extra"
"5/6-5/12｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】一定要勇敢改變的五月 #五月運勢" = "extra"
"【唐陽雞酒屋】用視覺系保護自己的Eko、對未來很擔憂的Sandra ft. @amazingtalkershow" = "extra"
"5/13-5/19｜星座運勢週報｜唐綺陽" = "extra"
"你不想遇到什麼星座的主管？#主管 #二選一 #處女座 #天秤座" = "extra"
"12星座該如何放下執著？｜2024/5/14直播" = "extra"
"【唐陽雞酒屋】好看的劇本都是不幸福時寫的ft.徐譽庭" = "extra"
"5/20-5/26｜星座運勢週報｜唐綺陽" = "extra"
"你所不知的12星座隱藏人脈！" = "extra"
"你的隱藏人脈在哪？#唐綺陽xVogue #星座#人脈" = "extra"
"5/27-6/2｜星座運勢週報｜唐綺陽" = "extra"
"金牛請選擇🪄 賺大錢 v.s江邊釣魚 🎧324 #金牛 #星座 #占星 #taurus #starsign #astrology" = "extra"
"唐綺陽直播｜如何在亂流中站穩的六月｜六月運勢" = "extra"
"6/3-6/9｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】粉紅泡泡是真的ft.靈能者小湛" = "extra"
"12星座該如何迎來新的能量場？｜2024/6/6直播" = "extra"
"6/10-6/16｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】如何在亂流中站穩的六月 #六月運勢" = "extra"
"6/17-6/23｜星座運勢週報｜唐綺陽" = "extra"
"12星座優質前任，那些分手後口碑還在的星座🥰" = "extra"
"你的前任是個好前任嗎？#唐綺陽xVogue #星座#前任" = "extra"
"6/24-6/30｜星座運勢週報｜唐綺陽" = "extra"
"2024下半年，壞事可能是好事？| 2024/6/20直播" = "extra"
"【唐陽雞酒屋】獅子座就是不肯靠顏值 ft.許瑋甯" = "extra"
"2024天秤座｜下半年運勢｜唐綺陽｜Libra forecast for the second half of 2024" = "extra"
"2024射手座｜下半年運勢｜唐綺陽｜Sagittarius forecast for the second half of 2024" = "extra"
"2024牡羊座｜下半年運勢｜唐綺陽｜Aries forecast for the second half of 2024" = "extra"
"2024天蠍座｜下半年運勢｜唐綺陽｜Scorpio forecast for the second half of 2024" = "extra"
"2024魔羯座｜下半年運勢｜唐綺陽｜Capricorn forecast for the second half of 2024" = "extra"
"2024水瓶座｜下半年運勢｜唐綺陽｜Aquarius forecast for the second half of 2024" = "extra"
"2024雙魚座｜下半年運勢｜唐綺陽｜Pisces forecast for the second half of 2024" = "extra"
"2024雙子座｜下半年運勢｜唐綺陽｜Gemini forecast for the second half of 2024" = "extra"
"2024巨蟹座｜下半年運勢｜唐綺陽｜Cancer forecast for the second half of 2024" = "extra"
"2024金牛座｜下半年運勢｜唐綺陽｜Taurus forecast for the second half of 2024" = "extra"
"2024處女座｜下半年運勢｜唐綺陽｜Virgo forecast for the second half of 2024" = "extra"
"2024獅子座｜下半年運勢｜唐綺陽｜Leo forecast for the second half of 2024" = "extra"
"7/1-7/7｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜好好發揮並小心收斂的七月｜七月運勢" = "extra"
"￼真相大白，12星座的疏通法| 2024/7/4直播" = "extra"
"7/8-7/14｜星座運勢週報｜唐綺陽" = "extra"
"真相大白，12星座該丟哪種直球| 2024/7/4直播" = "extra"
"【唐陽雞酒屋】遲早創業的星盤長怎樣 ft.艾莉絲" = "extra"
"【每月運勢】好好發揮並小心收斂的七月 #七月運勢" = "extra"
"7/15-7/21｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】差點要演男老大獅子座的自信跟自卑 ft.百白" = "extra"
"水星星座，看你怎麼說話！" = "extra"
"看水星，就知道你是怎麼溝通的🗣️ #唐綺陽xVogue #星座#水星" = "extra"
"火星進雙子，12星座場面大在哪| 2024/7/18直播" = "extra"
"7/22-7/28｜星座運勢週報｜唐綺陽" = "extra"
"7/29-8/4｜星座運勢週報｜唐綺陽" = "extra"
"【精簡版】第100堂｜土星的轉化-8｜2024/7/8 直播" = "extra"
"8/5-8/11｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜有逆行 也有逆轉的八月｜八月運勢" = "extra"
"【每月運勢】有逆行 也有逆轉的八月 #八月運勢" = "extra"
"【唐陽雞酒屋】創作鬼才的星盤ft.導演徐漢強 張榕容" = "extra"
"8/12-8/18｜星座運勢週報｜唐綺陽" = "extra"
"如何說服12星座？用對方法很重要" = "extra"
"【唐陽雞酒屋】魔羯座到底好不好笑? ft.黃豪平" = "extra"
"水逆回獅子，對12星座的影響| 2024/8/15直播" = "extra"
"8/19-8/25｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】練就幸運的能力ft #陳月卿" = "extra"
"【唐陽雞酒屋】練就幸運的能力ft 戀愛腦的榜樣 #陳月卿" = "extra"
"太陽進處女，12星座的新計畫在哪？| 2024/8/22直播" = "extra"
"8/26-9/1｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】居然有深情款雙子座ft. Jeffrey" = "extra"
"唐綺陽直播｜真相大白又刺激的九月｜九月運勢" = "extra"
"9/2-9/8｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】真相大白又刺激的九月 #九月運勢" = "extra"
"9/9-9/15｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】當星座遇上MBTI ，唐老師的MBTI是?ft.雪力 @sherrysnotesofficial" = "extra"
"9/16-9/22｜星座運勢週報｜唐綺陽" = "extra"
"看似好相處，其實超龜毛的星座…那些毛很多的星座" = "extra"
"看似好相處，其實超龜毛…那些毛很多的星座" = "extra"
"平常看不出來的龜毛王（處女座沒上榜）#唐綺陽xVogue #星座#龜毛" = "extra"
"看起來很隨興，骨子裡很龜毛的星座#唐綺陽xVogue #星座#龜毛" = "extra"
"9/23-9/29｜星座運勢週報｜唐綺陽" = "extra"
"9/30-10/6｜星座運勢週報｜唐綺陽" = "extra"
"你的靈魂在提醒你時，要聽啊！🎧359 #內耗 #星座 #占星" = "extra"
"你的靈魂在提醒你時，要聽啊！｜不安を感じるとき🎧359 #內耗 #星座 #占星" = "extra"
"唐綺陽直播｜懂人性，就會順一半的十月｜十月運勢" = "extra"
"10/7-10/13｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】懂人性，就會順一半的十月 #十月運勢" = "extra"
"李愛德華原來有獅子座的部分🎧363 #黑白大廚#巨蟹#獅子#金牛#흑백요리사: 요리 계급 전쟁#Culinary Class Wars" = "extra"
"10/14-10/20｜星座運勢週報｜唐綺陽" = "extra"
"李愛德華原來有獅子座的部分🎧363 #黑白大廚#巨蟹#獅子#金牛#흑백요리사: 요리 계급 전쟁#CulinaryClassWars" = "extra"
"12星座高階之路， 每個人都可以從低階變高階！" = "extra"
"想通了，12星座該在哪裡放下執念| 2024/10/16直播" = "extra"
"12星座該在哪個領域轉彎？| 2024/10/16直播" = "extra"
"每個人都可以從低階變高階喔！#唐綺陽xVogue #星座#高階#低階" = "extra"
"10/21-10/27｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】在韓國要紅有多難 ft.10CM #權正烈 #권정열" = "extra"
"火象星座，就是forever young🤭｜화성궁 별자리 그야말로 forever young #10CM" = "extra"
"10/28-11/3｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】人設是很好的工具 ft.蔡康永" = "extra"
"人設也可以是很好的工具🎧369#蔡康永#人設#面具" = "extra"
"11/4-11/10｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜很累，但會有收穫的十一月｜十一月運勢" = "extra"
"我眼中的2025| 2024/11/7直播" = "extra"
"我眼中的2025 | 2024/11/07直播" = "extra"
"我眼中的明年大趨勢 ｜ 2024/11/07直播" = "extra"
"11/11-11/17｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】很累，但會有收穫的十一月 #十一月運勢" = "extra"
"【唐陽雞酒屋】接通了潛意識有多強 ft.鄧惠文" = "extra"
"11/18-11/24｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】還是要相信愛情啦ft. 影后導演嚴藝文、詹懷雲" = "extra"
"火星星座，看你的性魅力❤️‍🔥" = "extra"
"11/25-12/1｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】穩定發脾氣的金牛 ft. 視網膜" = "extra"
"12/2-12/8｜星座運勢週報｜唐綺陽" = "extra"
"唐綺陽直播｜必須好好照顧自己的十二月｜十二月運勢" = "extra"
"12/9-12/15｜星座運勢週報｜唐綺陽" = "extra"
