"海王星，給你大好或大壞" = "extra"
"EP319 占星冷知識 (水瓶的淚腺?" = "extra"
"EP352月亮星座，你藏最深的脆弱面(下)" = "extra"
"什麼！魔羯座也會哭？12星座，想哭的時候" = "extra"
"12星座想哭的時候💦 #唐綺陽xVogue" = "extra"
"3/18-3/24｜星座運勢週報｜唐綺陽" = "extra"
"3/25-3/31｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】感情不順都是肝的問題？ft.簡少年" = "extra"
"各位小心肝，請小心肝。" = "extra"
"唐綺陽直播｜水逆的四月｜四月運勢" = "extra"
"4/1-4/7｜星座運勢週報｜唐綺陽" = "extra"
"今早6點正式水逆啦！#占星 #水逆 #星座" = "extra"
"4/8-4/14｜星座運勢週報｜唐綺陽" = "extra"
"【風象星座篇】水逆的四月 #四月運勢" = "extra"
"【火象星座篇】水逆的四月 #四月運勢" = "extra"
"【水象星座篇】水逆的四月 #四月運勢" = "extra"
"【土象星座篇】水逆的四月 #四月運勢" = "extra"
"焦慮代表你靈魂挺有野心的🎧EP310 #30歲 #長大 #壓力 #焦慮" = "extra"
"4/15-4/21｜星座運勢週報｜唐綺陽" = "extra"
"最難追星座男，好好先生都上榜了🤪" = "extra"
"你心目中最難追的星座是…？ #唐綺陽xVogue #星座#難追 #感情" = "extra"
"【唐陽雞酒屋】道理我都懂，啊又做不到ft.周慕姿" = "extra"
"4/22-4/28｜星座運勢週報｜唐綺陽" = "extra"
"社恐I人，會社交，但電池量過低🪫🤪#MBTI #16型人格 #占星" = "extra"
"【唐陽雞酒屋】向宇宙下訂單的體質 ft.蔡健雅" = "extra"
"4/29-5/5｜星座運勢週報｜唐綺陽" = "extra"
"天註定？不一定 #運勢 #占星 #命運" = "extra"
"你是改寫命運的導演 #運勢 #占星 #命運" = "extra"
"週報又被分到累的？其實不用怕😌 #週報 #累 #占星" = "extra"
"唐綺陽直播｜可以勇敢改變的五月｜五月運勢" = "extra"
"5/6-5/12｜星座運勢週報｜唐綺陽" = "extra"
"【每月運勢】一定要勇敢改變的五月 #五月運勢" = "extra"
"【唐陽雞酒屋】用視覺系保護自己的Eko、對未來很擔憂的Sandra ft. @amazingtalkershow" = "extra"
"5/13-5/19｜星座運勢週報｜唐綺陽" = "extra"
"你不想遇到什麼星座的主管？#主管 #二選一 #處女座 #天秤座" = "extra"
"12星座該如何放下執著？｜2024/5/14直播" = "extra"
"【唐陽雞酒屋】好看的劇本都是不幸福時寫的ft.徐譽庭" = "extra"
"5/20-5/26｜星座運勢週報｜唐綺陽" = "extra"
"你所不知的12星座隱藏人脈！" = "extra"
"你的隱藏人脈在哪？#唐綺陽xVogue #星座#人脈" = "extra"
"5/27-6/2｜星座運勢週報｜唐綺陽" = "extra"
"金牛請選擇🪄 賺大錢 v.s江邊釣魚 🎧324 #金牛 #星座 #占星 #taurus #starsign #astrology" = "extra"
"唐綺陽直播｜如何在亂流中站穩的六月｜六月運勢" = "extra"
"6/3-6/9｜星座運勢週報｜唐綺陽" = "extra"
"【唐陽雞酒屋】粉紅泡泡是真的ft.靈能者小湛" = "extra"
"12星座該如何迎來新的能量場？｜2024/6/6直播" = "extra"
"6/10-6/16｜星座運勢週報｜唐綺陽" = "extra"
