["本週運勢"]
inclusive = ["本週運勢"]
exclusive = []
category = ["#節目"]

[Meditation]
inclusive = ["Meditation"]
exclusive = []
category = ["#節目"]

["丹公解夢"]
inclusive = ["丹公解夢"]
exclusive = []
category = ["#節目"]

["冥想"]
inclusive = ["冥想", "Meditation"]
exclusive = []
category = ["方法"]

["水晶"]
inclusive = ["水晶"]
exclusive = []
category = ["方法"]

["靈魂契約"]
inclusive = ["靈魂契約"]
exclusive = []
category = ["方法"]

["許願"]
inclusive = ["許願"]
exclusive = []
category = ["方法"]

["生命靈數"]
inclusive = ["生命靈數"]
exclusive = []
category = ["方法"]

["星座"]
inclusive = ["星座"]
exclusive = []
category = ["方法"]

["五行"]
inclusive = ["五行"]
exclusive = []
category = ["方法"]

["塔羅牌"]
inclusive = ["塔羅"]
exclusive = []
category = ["方法"]

["守護天使"]
inclusive = ["守護天使"]
exclusive = []
category = ["靈體"]

["雙生火焰"]
inclusive = ["雙生火焰"]
exclusive = []
category = ["方法"]

["擴大療癒法"]
inclusive = ["擴大療癒法", "擴療"]
exclusive = []
category = ["方法"]

["奇蹟"]
inclusive = ["奇蹟"]
exclusive = []
category = ["方法"]

["寵物溝通"]
inclusive = ["寵物溝通"]
exclusive = []
category = ["方法"]

["靈擺"]
inclusive = ["靈擺"]
exclusive = []
category = ["方法"]

["揚升"]
inclusive = ["揚升"]
exclusive = []
category = ["方法"]

["指導靈"]
inclusive = ["指導靈"]
exclusive = []
category = ["靈體"]

["高我"]
inclusive = ["高我"]
exclusive = []
category = ["靈體"]

["人類圖"]
inclusive = ["人類圖"]
exclusive = []
category = ["方法"]

["夢"]
inclusive = ["夢"]
exclusive = []
category = ["方法"]

["催眠"]
inclusive = ["催眠"]
exclusive = []
category = ["方法"]

["風水"]
inclusive = ["風水"]
exclusive = []
category = ["方法"]

["東方靈數"]
inclusive = ["東方靈數"]
exclusive = []
category = ["方法"]

["神仙雜貨殿"]
inclusive = ["神仙雜貨殿"]
exclusive = []
category = ["神仙雜貨殿"]

["算命"]
inclusive = ["命會不會越算越差"]
exclusive = []
category = ["方法"]

["桃花"]
inclusive = ["桃花"]
exclusive = []
category = ["關係"]

["姻緣"]
inclusive = ["姻緣"]
exclusive = []
category = ["關係"]

["財神"]
inclusive = ["財神"]
exclusive = []
category = ["靈體"]

["女神"]
inclusive = ["母娘"]
exclusive = []
category = ["靈體"]

["脈輪"]
inclusive = ["七脈輪", "7脈輪"]
exclusive = []
category = ["方法"]

["黃金紀元"]
inclusive = ["黃金紀元", "黃金世紀"]
exclusive = []
category = ["方法"]

["紫色火焰"]
inclusive = ["紫色火焰"]
exclusive = []
category = ["方法"]

["黃香"]
inclusive = ["黃香", "小我皇后"]
exclusive = []
category = ["來賓"]

["老陳"]
inclusive = ["老陳"]
exclusive = []
category = ["來賓"]

["黃洄"]
inclusive = ["黃洄"]
exclusive = []
category = ["來賓"]

["阿寶"]
inclusive = ["阿寶"]
exclusive = []
category = ["來賓"]

[ReRe]
inclusive = ["ReRe"]
exclusive = []
category = ["來賓"]

["謝寶"]
inclusive = ["謝寶"]
exclusive = []
category = ["來賓"]

["小光"]
inclusive = ["小光"]
exclusive = []
category = ["來賓"]

["一咪"]
inclusive = ["一咪"]
exclusive = []
category = ["來賓"]

["路嘉怡"]
inclusive = ["路嘉怡"]
exclusive = []
category = ["來賓"]

["莫彼"]
inclusive = ["莫彼"]
exclusive = []
category = ["來賓"]

["廖原慶 @善嵐慶女"]
inclusive = ["廖原慶", "善嵐慶女"]
exclusive = []
category = ["來賓"]

["善嵐慶女"]
inclusive = ["善嵐慶女"]
exclusive = []
category = ["來賓"]

["其圭 @里民服務中心"]
inclusive = ["里民服務中心"]
exclusive = []
category = ["來賓"]

["蘿拉 @里民服務中心"]
inclusive = ["里民服務中心"]
exclusive = []
category = ["來賓"]

["朱宏章老師"]
inclusive = ["朱宏章老師"]
exclusive = []
category = ["來賓"]

["金妮"]
inclusive = ["金妮"]
exclusive = []
category = ["來賓"]

["小胖"]
inclusive = ["小胖"]
exclusive = []
category = ["來賓"]

["簡少年"]
inclusive = ["簡少年"]
exclusive = []
category = ["來賓"]

["Ashley 愛希"]
inclusive = ["Ashley 愛希"]
exclusive = []
category = ["來賓"]

["GINA 許怡蘭"]
inclusive = ["GINA 許怡蘭"]
exclusive = []
category = ["來賓"]

["江江老師"]
inclusive = ["江江老師"]
exclusive = []
category = ["來賓"]
