asc00001 = ["valuen"]
asc00002 = ["valuen"]
asc00003 = ["valuen"]
asc00004 = ["valuen"]
asc00005 = ["valuen"]
asc00006 = ["valuen"]
asc00007 = ["valuen"]
asc00008 = ["valuen"]
asc00009 = ["valuen"]
asc00010 = ["valuen"]
asc00011 = ["valuen"]
asc00012 = ["valuen"]
asc00013 = ["valuen"]
asc00014 = ["valuen"]
asc00015 = ["valuen"]
asc00016 = ["valuen"]
asc00017 = ["valuen"]
asc00018 = ["valuen"]
asc00019 = ["valuen"]
asc00020 = ["valuen"]
asc00021 = ["valuen"]
asc00022 = ["valuen"]
asc00023 = ["valuen"]
asc00024 = ["valuen"]
asc00025 = ["valuen"]
asc00026 = ["valuen"]
asc00027 = ["valuen"]
asc00028 = ["valuen"]
asc00029 = ["valuen"]
asc00030 = ["valuen"]
asc00031 = ["valuen"]
asc00032 = ["valuen"]
asc00033 = ["valuen"]
asc00034 = ["valuen"]
asc00035 = ["valuen"]
asc00036 = ["valuen"]
asc00037 = ["valuen"]
asc00038 = ["valuen"]
asc00039 = ["valuen"]
asc00040 = ["valuen"]
asc00041 = ["valuen"]
asc00042 = ["valuen"]
asc00043 = ["valuen"]
asc00044 = ["valuen"]
asc00045 = ["valuen"]
asc00046 = ["valuen"]
asc00047 = ["valuen"]
asc00048 = ["valuen"]
asc00049 = ["valuen"]
asc00050 = ["valuen"]
asc00051 = ["valuen"]
asc00052 = ["valuen"]
asc00053 = ["valuen"]
asc00054 = ["valuen"]
asc00055 = ["valuen"]
asc00056 = ["valuen"]
asc00057 = ["valuen"]
asc00058 = ["valuen"]
asc00059 = ["valuen"]
asc00060 = ["valuen"]
asc00061 = ["valuen"]
asc00062 = ["valuen"]
asc00063 = ["valuen"]
asc00064 = ["valuen"]
asc00065 = ["valuen"]
asc00066 = ["valuen"]
asc00067 = ["valuen"]
asc00068 = ["valuen"]
asc00069 = ["valuen"]
asc00070 = ["valuen"]
asc00071 = ["valuen"]
asc00072 = ["valuen"]
asc00073 = ["valuen"]
asc00074 = ["valuen"]
asc00075 = ["valuen"]
asc00076 = ["valuen"]
asc00077 = ["valuen"]
asc00078 = ["valuen"]
asc00079 = ["valuen"]
asc00080 = ["valuen"]
asc00081 = ["valuen"]
asc00082 = ["valuen"]
asc00083 = ["valuen"]
asc00084 = ["valuen"]
asc00085 = ["valuen"]
asc00086 = ["valuen"]
asc00087 = ["valuen"]
asc00088 = ["valuen"]
asc00089 = ["valuen"]
asc00090 = ["valuen"]
asc00091 = ["valuen"]
asc00092 = ["valuen"]
asc00093 = ["valuen"]
asc00094 = ["valuen"]
asc00095 = ["valuen"]
asc00096 = ["valuen"]
asc00097 = ["valuen"]
asc00098 = ["valuen"]
asc00099 = ["valuen"]
asc00100 = ["valuen"]
asc00101 = ["valuen"]
asc00102 = ["valuen"]
asc00103 = ["valuen"]
asc00104 = ["valuen"]
asc00105 = ["valuen"]
asc00106 = ["valuen"]
asc00107 = ["valuen"]
asc00108 = ["valuen"]
asc00109 = ["valuen"]
asc00110 = ["valuen"]
asc00111 = ["valuen"]
asc00112 = ["valuen"]
asc00113 = ["valuen"]
asc00114 = ["valuen"]
asc00115 = ["valuen"]
asc00116 = ["valuen"]
asc00117 = ["valuen"]
asc00118 = ["valuen"]
asc00119 = ["valuen"]
asc00120 = ["valuen"]
asc00121 = ["valuen"]
asc00122 = ["valuen"]
asc00123 = ["valuen"]
asc00124 = ["valuen"]
asc00125 = ["valuen"]
asc00126 = ["valuen"]
asc00127 = ["valuen"]
asc00128 = ["valuen"]
asc00129 = ["valuen"]
asc00130 = ["valuen"]
asc00131 = ["valuen"]
asc00132 = ["valuen"]
asc00133 = ["valuen"]
asc00134 = ["valuen"]
asc00135 = ["valuen"]
asc00136 = ["valuen"]
asc00137 = ["valuen"]
asc00138 = ["valuen"]
asc00139 = ["valuen"]
asc00140 = ["valuen"]
asc00141 = ["valuen"]
asc00142 = ["valuen"]
asc00143 = ["valuen"]
asc00144 = ["valuen"]
asc00145 = ["valuen"]
asc00146 = ["valuen"]
asc00147 = ["valuen"]
asc00148 = ["valuen"]
asc00149 = ["valuen"]
asc00150 = ["valuen"]
asc00151 = ["valuen"]
asc00152 = ["valuen"]
asc00153 = ["valuen"]
asc00154 = ["valuen"]
asc00155 = ["valuen"]
asc00156 = ["valuen"]
asc00157 = ["valuen"]
asc00158 = ["valuen"]
asc00173 = ["valuen"]
asc00179 = ["valuen"]
