"EP327 粉紅泡泡是真的ft.靈能者小湛" = "Jun 2024"
"EP326 木星進雙子的機智生活" = "Jun 2024"
"【本週提醒】多把力氣用在不會受傷的地方！" = "Jun 2024"
"EP325月亮星座，你藏最深的脆弱面(下)" = "May 2024"
"EP324 有星系列(金牛)：持久力的配置" = "May 2024"
"【本週提醒】人心難測，不要太快一廂情願喔" = "May 2024"
"EP323 12星座的高階發展" = "May 2024"
"EP322 月亮星座，你藏最深的脆弱面" = "May 2024"
"【本週提醒】不要怕，沒有危機，就沒有突破" = "May 2024"
"EP321好看的劇本都是不幸福時寫的ft.徐譽庭" = "May 2024"
"EP320 占星冷知識 (水瓶的淚腺?" = "May 2024"
"【本週提醒】水星進金牛，揭露你對自己滿不滿意" = "May 2024"
"EP319 真的沒曖昧過ft. 驚奇玩起來Eko、Sandra" = "May 2024"
"EP318 有星系列(牡羊)：獨特的配置" = "May 2024"
"【本週提醒】找回生活秩序吧！" = "May 2024"
"EP317 海王星(下)，給你大好或大壞" = "May 2024"
"EP316 喊我就爛的人其實超努力" = "May 2024"
"【本週提醒】記得把焦點放回自己身上👀" = "Apr 2024"
"EP315 向宇宙下訂單的體質 ft.蔡健雅" = "Apr 2024"
"EP314 九宮飛星，星盤中藏不住的幸運(下)" = "Apr 2024"
"【本週提醒】比起自我欺騙，不如好好修補錯誤🔧" = "Apr 2024"
"EP313 海王星，給你大好或大壞" = "Apr 2024"
"EP312 道理我都懂，啊又做不到ft.周慕姿" = "Apr 2024"
"【本週提醒】覺得不對勁的事情，可以開始改變了" = "Apr 2024"
"EP311 九宮飛星，星盤中藏不住的幸運" = "Apr 2024"
"EP310 保持焦慮是有野心的表現？" = "Apr 2024"
"【本週提醒】主動迎來改變吧！" = "Apr 2024"
"EP309 金星進牡羊，你的水逆救生圈" = "Apr 2024"
"【本週提醒】讓子彈飛一會，不要太快反應⚡️" = "Mar 2024"
"EP308 感情不順都是肝的問題？ft.簡少年" = "Mar 2024"
"EP307 12星座男的戀愛空間" = "Mar 2024"
"【本週提醒】驟變也有可能是變好喔！" = "Mar 2024"
"EP306 相位：星盤中的禮物或挑戰" = "Mar 2024"
"EP305 2024桃花神攻略" = "Mar 2024"
"【本週提醒】春分來了，新的開始來了⚡️" = "Mar 2024"
"EP304  攻略系列：曖昧當面試的魔羯男" = "Mar 2024"
"EP303 當月亮同星座住在一起(下)" = "Mar 2024"
"【本週提醒】把握那些靈光乍現的奇蹟時刻🤩" = "Mar 2024"
"EP302  12星座PUA自救法" = "Mar 2024"
"EP301 當月亮同星座住在一起" = "Mar 2024"
"【本週提醒】原本排斥的，現在可以接受了⋯" = "Mar 2024"
"EP300 先揍你再給糖吃，土星(下)" = "Mar 2024"
"EP299 水星進雙魚的讀空氣指南" = "Feb 2024"
"【本週提醒】用心感受雙魚能量滿滿的一週" = "Feb 2024"
"EP298 有星系列(水瓶)：前瞻性的配置" = "Feb 2024"
"EP297 先揍你再給糖吃，土星" = "Feb 2024"
"【本週提醒】努力讓生活恢復正常" = "Feb 2024"
"EP296 12星座獨特忍功" = "Feb 2024"
"EP295 跟12星座相處的各種不要" = "Feb 2024"
"【本週提醒】這個年關，頗有壓力" = "Feb 2024"
"EP294 星盤缺元素＝你最突出的地方" = "Feb 2024"
"EP293 有星系列(魔羯)：菁英的配置" = "Jan 2024"
"【本週提醒】所有的不正常，也許都是正常" = "Jan 2024"
"EP292 火象星座攻略守則（獅子男）" = "Jan 2024"
"EP291 12宮飛星，你帶天命的地方(下)" = "Jan 2024"
"【本週提醒】什麼叫做苦的很甘願？" = "Jan 2024"
"EP290 12宮飛星，你帶天命的地方" = "Jan 2024"
"EP289 戀愛腦星座" = "Jan 2024"
"【本週提醒】收拾好情緒，觀察身邊的變化" = "Jan 2024"
"EP288 火星進魔羯的抗壓指南" = "Jan 2024"
"EP287 12星座小祕密" = "Jan 2024"
"【本週提醒】感受一下又魔幻 又粗暴的能量" = "Jan 2024"
"EP286水星火象也是可以好好溝通啦ft.郎祖筠" = "Jan 2024"
"EP285 12星座不改變來不及的事" = "Jan 2024"
"【本週提醒】新年快樂" = "Dec 2023"
"EP284 含金量高的運勢問答來啦" = "Dec 2023"
"EP283此生不會好的傷，凱龍星" = "Dec 2023"
"【本週提醒】好好感受2023的最後一週" = "Dec 2023"
"EP282 單身勝利組" = "Dec 2023"
"EP281 火星，你的達標力(下)💣" = "Dec 2023"
"【本週提醒】變數很多的一週，冬至嘛" = "Dec 2023"
"EP280 月老廟的月老團隊ft.Misc" = "Dec 2023"
"EP279  有星系列(射手)：幸運的配置" = "Dec 2023"
"【本週提醒】錢の大躍進" = "Dec 2023"
"EP278 星座戀愛都市傳說6 情路不順破解法" = "Dec 2023"
"EP277 火星，你的達標力 💣" = "Dec 2023"
"【本週提醒】金星點名，皮要繃緊❤️" = "Dec 2023"
"EP276 第一次見面如何猜星座?" = "Dec 2023"
"EP275 11宮飛星，你最受歡迎的地方(下)" = "Nov 2023"
"【本週提醒】你設定的目標達成了多少呢？" = "Nov 2023"
"EP274 火象星座攻略守則（牡羊男）" = "Nov 2023"
"EP273 11宮飛星，你最受歡迎的地方" = "Nov 2023"
"【本週提醒】犯錯被檢討，也不是壞事啦..." = "Nov 2023"
"EP272 滿血復活的星座" = "Nov 2023"
"EP.271金星，你最堅持的地方(下)" = "Nov 2023"
"【本週提醒】任何奇怪的人都有可能是貴人喔" = "Nov 2023"
"EP270喜歡折磨自己的宮位ft.邵雨薇" = "Nov 2023"
"EP269下降星座，你的伴侶(下)" = "Nov 2023"
"【本週提醒】💕桃花滿天飛💕" = "Nov 2023"
"EP268 月亮星座看你愛情盲點" = "Nov 2023"
"【本週提醒】悶很久了嗎？這週試著動起來看看" = "Oct 2023"
"EP.267金星，你最堅持的地方" = "Oct 2023"
"EP266 12星座的超現實比較" = "Oct 2023"
"【本週提醒】什麼該結束？什麼該重新開始？可以想想喔" = "Oct 2023"
"EP265下降星座，你的伴侶" = "Oct 2023"
"EP264 火星進天蠍的突破指南" = "Oct 2023"
"【本週提醒】錢包很有感覺，不確定是好是壞..." = "Oct 2023"
"EP263奇怪欸土象星座ft.又仁、LuLu" = "Oct 2023"
"EP262 十宮飛星(下)，累但會成功的地方🤩" = "Oct 2023"
"【本週提醒】細節王站出來" = "Oct 2023"
"EP261 十宮飛星，累但會成功的地方🤩" = "Oct 2023"
"EP260 12星座第一名" = "Oct 2023"
"【本週提醒】小心在感情上衝動的行為啊！" = "Oct 2023"
"EP259 火象星座攻略守則（射手男）" = "Sep 2023"
"EP258五宮飛星，你亮晶晶的地方(下)" = "Sep 2023"
"【本週提醒】不是找到神隊友，就是拆夥" = "Sep 2023"
"EP257 正義感爆棚的五宮人 ft.欸你這週要幹嘛" = "Sep 2023"
"EP256五宮飛星，你亮晶晶的地方" = "Sep 2023"
"【本週提醒】蠢蠢欲動想戀愛的感覺，正常正常" = "Sep 2023"
"EP255 看不出來的細節控星座" = "Sep 2023"
"EP254 正確許願法" = "Sep 2023"
"【本週提醒】請學著跟人合作，不要太自我" = "Sep 2023"
"EP253 如果明天是你生命的最後一天？ ft.小冬瓜" = "Sep 2023"
"EP252 太陽跟上升星座的差別(下)" = "Sep 2023"
"【本週提醒】人的問題，才是大問題🔥" = "Sep 2023"
"EP251 太陽跟上升星座的差別" = "Sep 2023"
"EP250 火星進天秤的人緣指南" = "Aug 2023"
"【本週提醒】做一點天王星的事吧！" = "Aug 2023"
"EP249 月亮星座合有多重要ft.許茹芸" = "Aug 2023"
"EP248 水象星座攻略守則（雙魚男）" = "Aug 2023"
"【本週提醒】默默努力的人出頭天" = "Aug 2023"
"EP247 七夕衝刺：找真愛看月亮(下)" = "Aug 2023"
"EP246 七夕衝刺：找真愛看月亮" = "Aug 2023"
"【本週提醒】避免在週末做重大決定！" = "Aug 2023"
"EP245 12星座之謎" = "Aug 2023"
"EP244 人生中的奧客(6宮飛星下集)" = "Aug 2023"
"【本週提醒】小心用電＆用火💥" = "Aug 2023"
"EP243自帶運氣的星座(星盤裡的幸運點)" = "Aug 2023"
"EP242 人生中的奧客(6宮飛星)" = "Aug 2023"
"【本週提醒】講話直接，但結果可能是好的" = "Jul 2023"
"EP241最難算計的星座" = "Jul 2023"
"EP240 水星進處女的效率指南" = "Jul 2023"
"【本週提醒】朝高智商人類邁進" = "Jul 2023"
"EP239 水象星座攻略守則（巨蟹男水很深）" = "Jul 2023"
"EP238 2宮飛星(下)，你的強項在哪裡？" = "Jul 2023"
"【本週提醒】被檢討的事情雖小，但也很重要" = "Jul 2023"
"EP237 火星移位的做事指南" = "Jul 2023"
"EP236 後天努力型選手 ft.鄧惠文" = "Jul 2023"
"【本週提醒】好好學學怎麼當處女座" = "Jul 2023"
"EP235 2宮飛星，你的強項在哪裡？" = "Jul 2023"
"EP234 感情上，可能過度付出的星座" = "Jul 2023"
"【本週提醒】一起面對已經撕開的真相吧！" = "Jul 2023"
"EP233 水象星座攻略守則（天蠍男）" = "Jun 2023"
"EP232 土海逆雙魚，「新‧做人指南」" = "Jun 2023"
"【本週提醒】真相雖然讓人不舒服，但我們還是要溫柔一點喔！" = "Jun 2023"
"EP231 星盤中有星逆行會怎樣" = "Jun 2023"
"【本週提醒】不肯改變的人，可能會被冥王星粉碎喔" = "Jun 2023"
"EP230星盤中的考驗區&休息區(聊度數)" = "Jun 2023"
"EP229水星，不得罪人說話法(下)" = "Jun 2023"
"【本週提醒】不見光的事情慢慢湧出，一起清理心靈的垃圾" = "Jun 2023"
"EP228水星，不得罪人說話法" = "Jun 2023"
"EP227懂看月亮日=幫自己算命" = "Jun 2023"
"【本週提醒】戀愛的心情大大增加💘" = "Jun 2023"
"EP226 史上最難搶的那個男人來了 ft.陳耀訓" = "Jun 2023"
"EP225 風象星座攻略守則（雙子男）" = "May 2023"
"【本週提醒】固定能量強，這週宜吃好睡好Zzz" = "May 2023"
"EP224 表面隨和，其實超愛面子的星座" = "May 2023"
"EP223 聽der俱樂部，活動番外篇" = "May 2023"
"【本週提醒】桃花能量已開" = "May 2023"
"EP222 木星進金牛的幸運指南（機會來了）" = "May 2023"
"EP221 怎麼找宮位守護星？" = "May 2023"
"【本週提醒】穩住腳步，不要亂下決定喔！" = "May 2023"
"EP220月亮星座看你有哪款媽(下)" = "May 2023"
"EP219 月亮星座看你有哪款媽" = "May 2023"
"【本週提醒】拿出改變的決心跟行動力！不要等改變自己找上門比較好" = "May 2023"
"EP218 外表硬漢內心少女 ft.黃健瑋" = "May 2023"
"EP217 水喔 ft.陳君潔" = "May 2023"
"【本週提醒】冥王星逆行，他洗牌了你什麼呢？" = "Apr 2023"
"EP216 忍者星座，請了解吐苦水的重要" = "Apr 2023"
"EP215 當一個課本裡的活人ft.吳念真" = "Apr 2023"
"【本週提醒】水逆來了，準備要來顛覆那些「自以為」的東西" = "Apr 2023"
"EP214 同星座不同月份，差很大？" = "Apr 2023"
"EP213 我看你就很親切 ft.陳竹昇" = "Apr 2023"
"【本週提醒】太陽要進金牛了，好好評估什麼是對自己重要的！" = "Apr 2023"
"EP212 風象星座攻略守則（天秤男）" = "Apr 2023"
"EP211最近很哭…火星巨蟹時期的情緒指南" = "Apr 2023"
"【本週提醒】有沒有「奇怪的事一直在發生」的感覺？" = "Apr 2023"
"EP210 XX座為什麼半夜不回家？" = "Apr 2023"
"【本週提醒】頂著不舒服的壓力，卻是新契機" = "Apr 2023"
"EP209 愛賺錢但不愛錢的二宮人 ft.台通誠誠" = "Mar 2023"
"EP208 風象星座攻略守則（水瓶男）" = "Mar 2023"
"【本週提醒】火星進巨蟹的鬼片，小心情緒化的自己" = "Mar 2023"
"EP207 越親近對你越嚴格的星座(怕)" = "Mar 2023"
"EP206 星盤中影響最大的兩顆星" = "Mar 2023"
"【本週提醒】春天來了，你真的該動起來了！" = "Mar 2023"
"EP205太陽五宮的追愛人生ft.三毛姪女 陳天慈" = "Mar 2023"
"EP204 單身還想怪星盤？單身取暖特集" = "Mar 2023"
"【本週提醒】多去看看本來看不見的部分" = "Mar 2023"
"EP203 當你有星在雙魚（下）" = "Mar 2023"
"EP202 當你有星在雙魚（上）" = "Mar 2023"
"【本週提醒】如常的每天，在星象詮釋下，卻又顯得那麼不凡" = "Mar 2023"
"EP201 星座職場都市傳說1 尋找神隊友" = "Mar 2023"
"EP.200 金星進牡羊時的做人指南(還有桃花)" = "Mar 2023"
"【本週提醒】金星進牡羊的桃花飛舞🌟" = "Feb 2023"
"EP199 12星座の原則(要小心)" = "Feb 2023"
"EP198 你太XX座了喔，是啥意思？（下）" = "Feb 2023"
"【本週提醒】越有行動力，越容易被看見" = "Feb 2023"
"EP197 人生轉折-土星回歸、七年之癢、中年危機" = "Feb 2023"
"EP196 你太XX座了喔，是啥意思？（中）" = "Feb 2023"
"【本週提醒】站起來，遇到驟變就好好接招吧！" = "Feb 2023"
"EP195 雲門舞集跟八方雲集的關係ft.林懷民" = "Feb 2023"
"EP194 星座戀愛都市傳說5 虐戀破解法" = "Feb 2023"
"【本週提醒】想變美，讓自己好好休息" = "Feb 2023"
"EP193 你太XX座了喔，是啥意思？（上）" = "Feb 2023"
"EP192 上升星座Ⅳ，你未來的方向(上升水象)" = "Jan 2023"
"【本週提醒】金星雙魚，爭取時間多睡一下吧zzz" = "Jan 2023"
"EP191 2023上半年桃花神攻略" = "Jan 2023"
"【本週提醒】比起忍耐，應該學學怎麼表達喔" = "Jan 2023"
"EP190 上升星座Ⅲ，你未來的方向(上升風象)" = "Jan 2023"
"【本週提醒】投機取巧請小心" = "Jan 2023"
"EP189 火星射手有多不怕死？ft.隋棠" = "Jan 2023"
"EP188 上升星座Ⅱ，你未來的方向(上升土象)" = "Jan 2023"
"【本週提醒】搞怪請讓專業的來" = "Jan 2023"
"EP187 木星讓你多幸運(下)-宮位篇" = "Dec 2022"
"EP186 土星，有苦也有成功Ⅲ(學會踩煞車)" = "Dec 2022"
"【本週提醒】專業人士站出來" = "Dec 2022"
"EP185 讓人難忘的水象星座" = "Dec 2022"
"EP184 上升星座，你未來的方向(上升火象)" = "Dec 2022"
"【本週提醒】年關將近，我們的處境也劇烈變化中" = "Dec 2022"
"EP183 土星，有苦也有成功Ⅱ(意外驚喜)" = "Dec 2022"
"EP182 最難忘的星座男" = "Dec 2022"
"【本週提醒】被人針對也記得要保持風度喔！" = "Dec 2022"
"EP181 土星，有苦也有成功（晚年有成就）" = "Dec 2022"
"EP180 木星讓你多幸運(上)-宮位篇" = "Dec 2022"
"【本週提醒】很多事情吵了才發現，跟想像中不一樣" = "Dec 2022"
"EP179 星座防爆守則" = "Dec 2022"
"EP178 五宮，絕不安分守己Ⅲ（臉皮薄）" = "Nov 2022"
"【本週提醒】看命運又出何招？要相信「一切是最好安排」" = "Nov 2022"
"EP177 12星座進化史(下)" = "Nov 2022"
"EP176 五宮，絕不安分守己Ⅱ（藏不住的才華）" = "Nov 2022"
"【本週提醒】抓住正能量，冒險一點沒關係" = "Nov 2022"
"EP175 12星座進化史(上)" = "Nov 2022"
"EP174 水星看你會不會說話Ⅲ(最自豪的)" = "Nov 2022"
"【本週提醒】趁著這週好好的療癒自己" = "Nov 2022"
"EP173 月亮星座：情緒的老大" = "Nov 2022"
"EP172 五宮，絕不安分守己（自帶光環）" = "Nov 2022"
"【本週提醒】不要對「變」感到不安" = "Nov 2022"
"EP171 水星看你會不會說話Ⅱ(怪)" = "Nov 2022"
"EP170 12宮人，一吵架就消失  ft. 安溥" = "Nov 2022"
"【本週提醒】情緒被放大，感覺那個久違了的自己" = "Oct 2022"
"EP169 前世的缺點在這世更正ft.靈媒媽媽" = "Oct 2022"
"EP168 十二宮，天選之人IV（無法想像的高標）" = "Oct 2022"
"【本週提醒】有發光發熱，或展現自我的機會" = "Oct 2022"
"EP167 要算命還是看心理諮商 feat.周慕姿" = "Oct 2022"
"【本週提醒】又忙又累，苦中作樂的一週" = "Oct 2022"
"EP166 十二宮，天選之人Ⅲ（不訴苦）" = "Oct 2022"
"【本週提醒】冥王星順行，代表大改變的開始" = "Oct 2022"
"EP165 12星座愛情中最笨的地方" = "Oct 2022"
"【本週提醒】對方太囂張，無法視而不見" = "Oct 2022"
"EP164 十二宮，天選之人Ⅱ（相信就會被接住）" = "Sep 2022"
"【本週提醒】你心中的公平是什麼呢" = "Sep 2022"
"EP163 你討厭自己哪些點？請好好說" = "Sep 2022"
"EP162 太陽星座，你重視的地方" = "Sep 2022"
"【本週提醒】有貴人出現，要好好求教" = "Sep 2022"
"EP161 十二宮，天選之人（超乎常人的抗壓）" = "Sep 2022"
"EP160 金星，桃花超旺但不一定爽Ⅲ" = "Sep 2022"
"【本週提醒】檢討別人的同時，記得檢討自己" = "Sep 2022"
"EP159 金星，桃花超旺但不一定爽Ⅱ" = "Sep 2022"
"【本週提醒】默默努力的人有福了！" = "Sep 2022"
"EP158. 12星座都有病" = "Sep 2022"
"EP157 為什麼直男都不談心事 ft.梁正群、陳家逵" = "Aug 2022"
"【本週提醒】懷舊氛圍重，可能對前任有感..." = "Aug 2022"
"EP156.十一宮，江湖兒女Ⅲ（在團體中叛逆）" = "Aug 2022"
"EP155 金星，桃花超旺但不一定爽" = "Aug 2022"
"【本週提醒】理財踩剎車，檢視人生規劃的好時機" = "Aug 2022"
"EP154十一宮，江湖兒女Ⅱ（讓人頭痛的能力）" = "Aug 2022"
"EP153 當大家都變成雙子座的時候" = "Aug 2022"
"【本週提醒】要克制喔，尤其是自己都知道的毛病" = "Aug 2022"
"EP152 射手座通靈師ft.Misc" = "Aug 2022"
"EP151 2022鬼月徵稿：比鬼可怕的東西" = "Aug 2022"
"【本週提醒】沒法視而不見，也無法假裝有耐性了嗎" = "Aug 2022"
"EP150 加一點點直男的12星座告白法ft.台通家倫" = "Aug 2022"
"EP149 十一宮，江湖兒女（眾人之事是我事）" = "Aug 2022"
"【本週提醒】提升自我競爭力的好時機來囉" = "Jul 2022"
"EP148 那些形成星座刻板印象的原因…" = "Jul 2022"
"EP147 十宮人，你太認真了啦 ft.9m88的十萬個為什麼" = "Jul 2022"
"【本週提醒】感受一下我們哪裡需要煞車、轉折" = "Jul 2022"
"EP146 我也有過工作兩週就放棄" = "Jul 2022"
"EP145 通靈人在想什麼 ft.大寶、分多奇" = "Jul 2022"
"【本週提醒】要小心情緒爆衝，試著理解情緒" = "Jul 2022"
"EP144  木星，很幸運但不知道" = "Jul 2022"
"EP143 月亮星座之最（你的安全感）" = "Jul 2022"
"【本週提醒】把人推離舒適圈的挑戰來了" = "Jul 2022"
"EP142 星座戀愛都市傳說4 收服大全" = "Jul 2022"
"EP141 2022下半年運勢小秘密" = "Jul 2022"
"【本週提醒】每個人都有機會看清，以為親近的人，的另一種面目" = "Jul 2022"
"EP140 水星看你會不會說話" = "Jun 2022"
"【本週提醒】火能量衝刺中，小心踩到地雷喔" = "Jun 2022"
"EP139 十宮Ⅲ，人生資優生（失速也慢速）" = "Jun 2022"
"EP138 星盤看你的菜在哪" = "Jun 2022"
"【本週提醒】想宣洩的情緒就宣洩吧" = "Jun 2022"
"EP137 十宮Ⅱ，人生資優生（早熟到你會怕）" = "Jun 2022"
"EP136 神秘能量開最大的一集ft.張之愷" = "Jun 2022"
"【本週提醒】重新出發，好好整頓自己" = "Jun 2022"
"EP135 十宮，人生資優生（稱讚可以當飯吃）" = "Jun 2022"
"EP134 12星座曖昧地雷" = "Jun 2022"
"【本週提醒】說出心裡話，替自己奮戰是好事喔" = "Jun 2022"
"EP133 走過霸凌的八宮人 ft.阿翰" = "Jun 2022"
"EP132 12星座最讓人受不了的point" = "May 2022"
"【本週提醒】擔責任是好事，只是方式對了嗎？" = "May 2022"
"EP131 對宮星座，最像又最不合Ⅱ" = "May 2022"
"EP130 發脾氣，也要看火星Ⅱ" = "May 2022"
"【本週提醒】還是要注意火能量，不要忘了也要享受生活喔" = "May 2022"
"EP129 對宮星座，最像又最不合" = "May 2022"
"EP128 發脾氣，也要看火星" = "May 2022"
"【本週提醒】這段時間，一定要小心說話啊！" = "May 2022"
"EP127 易燃易爆炸的星座" = "May 2022"
"EP126 八宮Ⅳ，砍掉重練（站在懸崖邊）" = "May 2022"
"【本週提醒】水逆是有意義的，不要只看到不好的地方喔" = "May 2022"
"EP125 雙魚能量生存之道：示弱" = "May 2022"
"EP124 八宮Ⅲ，砍掉重練（怎麼能少了性）" = "May 2022"
"【本週提醒】有什麼非做不可的事？不要想，就去做吧！" = "May 2022"
"EP123 人生苦短，有事要說！" = "Apr 2022"
"【本週提醒】善良一點，好事會發生的" = "Apr 2022"
"EP122 八宮Ⅱ，砍掉重練（精的跟鬼一樣）" = "Apr 2022"
"EP 121 我爽就好的一宮人 ft.台通何A、誠誠" = "Apr 2022"
"【本週提醒】試著打破自己，去做以前不想做的事！" = "Apr 2022"
"EP120 八宮，砍掉重練（幹大事）" = "Apr 2022"
"EP119 前衛也老派的土星九宮 ft.郎祖筠" = "Apr 2022"
"【本週提醒】好好面對自己的內在，宇宙會幫助你" = "Apr 2022"
"EP.118 星盤看你聰明在哪Ⅱ" = "Apr 2022"
"【本週提醒】不要太就事論事，背後可能有其他原因喔！" = "Apr 2022"
"EP.117 自斬桃花的星盤(哭啊)" = "Apr 2022"
"EP.116 一宮Ⅲ，極度自我（找別人麻煩）" = "Mar 2022"
"【本週提醒】有一點自我感覺不良好，不需要責備自己啦！" = "Mar 2022"
"EP.115 星盤看你聰明在哪Ⅰ" = "Mar 2022"
"EP.114 一宮Ⅱ，極度自我（自找麻煩）" = "Mar 2022"
"【本週提醒】溝通，不一定要靠言語" = "Mar 2022"
"EP.113 桃花旺的星盤長怎樣Ⅱ" = "Mar 2022"
"EP.112 一宮，極度自我（孤獨也沒關係）" = "Mar 2022"
"【本週提醒】在亂糟糟的能量場中，找出做事的方式" = "Mar 2022"
"EP.111 要溝通啦" = "Mar 2022"
"EP.110 金火移動的戀愛指南" = "Mar 2022"
"EP.109 七宮Ⅲ，人生照妖鏡（小心被操控）" = "Mar 2022"
"EP.108 七宮Ⅱ，人生照妖鏡（讓人壓力大）" = "Mar 2022"
"【本週提醒】有極端能量，不要衝動做決定喔！" = "Feb 2022"
"EP.107 全公司都OO座" = "Feb 2022"
"EP.106 桃花旺的星盤長怎樣" = "Feb 2022"
"【本週提醒】想談戀愛的感覺很強烈♥因為想改變關係" = "Feb 2022"
"EP.105 七宮Ⅰ，人生照妖鏡（互相奇怪）" = "Feb 2022"
"EP.104 木星Ⅳ，你幸運的地方（越機車越幸運？）" = "Feb 2022"
"【本週提醒】聽聽潛意識想表達什麼" = "Feb 2022"
"EP. 103 難搞星座，覺得自己會上榜嗎？" = "Feb 2022"
"EP.102 木星Ⅲ，你幸運的地方（越衝動越幸運）" = "Feb 2022"
"EP.101 當個死小孩也不錯 ft. 《美國女孩》導演阮鳳儀" = "Jan 2022"
"EP.100 四宮Ⅲ，看不見的痛（隱性驕傲）" = "Jan 2022"
"EP.99 把挫折當飯吃 ft.百靈果" = "Jan 2022"
"EP.98 四宮Ⅱ，看不見的痛（懂得示弱）" = "Jan 2022"
"【本週提醒】迅雷不及掩耳的天王星能量，是改變的好時機" = "Jan 2022"
"【月運直播】保持善良的1月- 火象星座" = "Jan 2022"
"【月運直播】保持善良的1月- 土象星座" = "Jan 2022"
"【月運直播】保持善良的1月- 風象星座" = "Jan 2022"
"【月運直播】保持善良的1月- 水象星座" = "Jan 2022"
"EP.97 相信的力量是有用滴，美輪明宏之亂" = "Jan 2022"
"EP.96 木星Ⅱ，你幸運的地方(很苦也是幸運）" = "Jan 2022"
"【本週提醒】過年前來個逆轉勝，機會很大唷" = "Jan 2022"
"EP.95 當你被情緒淹沒時" = "Jan 2022"
"EP.94 四宮Ⅰ，看不見的痛(要長大)" = "Jan 2022"
"【本週提醒】水星進水瓶了，水瓶式的社交生活展開" = "Jan 2022"
"EP.93 年末大拷問：星座之最" = "Dec 2021"
"EP.92九宮，神的宮位四(有天線)" = "Dec 2021"
"【本週提醒】好好攤開自己的弱點，也許不是壞事喔！" = "Dec 2021"
"EP.91 星座戀愛都市傳說3 犧牲奉獻的愛" = "Dec 2021"
"EP.90 有些星座想脫單，但是難啊…" = "Dec 2021"
"【本週提醒】金逆，生涯交叉點來了" = "Dec 2021"
"EP.89九宮，神的宮位 Ⅲ(找死?)" = "Dec 2021"
"EP. 88 木星Ⅰ，你幸運的地方(不幸也是)？" = "Dec 2021"
"【本週提醒】一直很努力，但結果如何呢？" = "Dec 2021"
"【直播】12月運勢- 風象星座" = "Dec 2021"
"【直播】12月運勢- 火象星座" = "Dec 2021"
"【直播】12月運勢- 土象星座" = "Dec 2021"
"【直播】12月運勢- 水象星座" = "Dec 2021"
"EP.87 星象壞壞，趁現在當9宮人(有人想嗎)" = "Dec 2021"
"EP.86 九宮，神的宮位 Ⅱ(滋事份子)" = "Dec 2021"
"【本週提醒】有委屈感湧上心頭嗎？" = "Dec 2021"
"EP.85 星座爆氣王 怕.jpg" = "Dec 2021"
"EP.84 九宮，神的宮位Ⅰ（跩屁）" = "Nov 2021"
"【本週提醒】如夢初醒，逃避很久的事情，也許該面對了" = "Nov 2021"
"EP.83 暗黑特調：加拿大買兇弒親案Jennifer Pan" = "Nov 2021"
"EP.82 星座戀愛都市傳說2 致命吸引力" = "Nov 2021"
"【本週提醒】要小心自己的說話態度喔！" = "Nov 2021"
"【直播】怪事年年有，最近特別多，你被火天攻擊了嗎" = "Nov 2021"
"EP.81 徵稿：今年最扯的事(都是月亮惹的禍?)" = "Nov 2021"
"【本週提醒】永遠要記得，你是值得的" = "Nov 2021"
"EP. 80 六宮，職場菁英Ⅲ（壯士們）" = "Nov 2021"
"EP.79 星座戀愛都市傳說" = "Nov 2021"
"【直播】11月運勢- 風象星座" = "Nov 2021"
"【直播】11月運勢- 火象星座" = "Nov 2021"
"【直播】11月運勢- 水象星座" = "Nov 2021"
"【直播】11月運勢- 土象星座" = "Nov 2021"
"【本週提醒】努力的人會被看見" = "Nov 2021"
"EP. 78 交往十年，單身八年 ft. 簡莉穎.王安琪" = "Nov 2021"
"EP. 77六宮，職場菁英Ⅱ(勞碌命X）" = "Nov 2021"
"【本週提醒】傷人的話不要說" = "Oct 2021"
"EP. 76 暗黑特調：電影魔警-徐步高" = "Oct 2021"
"EP. 75 金星，你漂亮的地方Ⅲ" = "Oct 2021"
"【本週提醒】趁現在好好修補人際關係" = "Oct 2021"
"EP. 74 變壞的成本太高了 ft.敏迪" = "Oct 2021"
"EP. 73 六宮，職場菁英(眼神死）" = "Oct 2021"
"【本週提醒】你到底是神隊友還豬隊友？" = "Oct 2021"
"EP. 72 你還是不要說話好了" = "Oct 2021"
"EP. 71  暗黑特調：北大弒母案-別讓自己成魔，也不逼人成魔" = "Oct 2021"
"【本週提醒】休息夠了，該是往前走的時候囉！" = "Oct 2021"
"EP. 70  三宮趴三，一定幸運" = "Oct 2021"
"EP.69 金星，你漂亮的地方Ⅱ" = "Oct 2021"
"【本週提醒】逆行是在提醒我們過去犯的失誤喔！" = "Oct 2021"
"EP.68 金魚腦了" = "Oct 2021"
"EP.67 好好相處很難嗎" = "Sep 2021"
"【本週提醒】彼此的合作是值得的嗎？效果顯現" = "Sep 2021"
"EP.66 三宮趴兔，晚年的學霸" = "Sep 2021"
"EP.65 人生就是鬆緊之間" = "Sep 2021"
"【本週提醒】激烈的溝通是難免的，不要擔心。" = "Sep 2021"
"EP.64 暗黑特調：邪教系列-天堂之門" = "Sep 2021"
"EP.63 三宮，學霸的宮位" = "Sep 2021"
"【本週提醒】想翻舊帳就翻吧！" = "Sep 2021"
"EP.62 金星，你漂亮的地方" = "Sep 2021"
"EP.61 腹黑之王是誰？請接下帽子" = "Sep 2021"
"【本週提醒】你過勞了嗎？" = "Sep 2021"
"EP.60 第一次總會特別痛 ft.理科太太" = "Sep 2021"
"EP.59 珍愛生命，請遠離......." = "Aug 2021"
"【本週提醒】不要小看愛與和平的力量" = "Aug 2021"
"EP.58 靈異體質的人鬼月都在幹嘛 ft.李函" = "Aug 2021"
"EP.57 二宮趴三，沒有偏財運的人" = "Aug 2021"
"【本週提醒】很焦慮嗎？那是因為你沒行動起來！" = "Aug 2021"
"EP.56 最近我們都變處女座了" = "Aug 2021"
"【本週提醒】遇到脾氣不好的人，請誇獎他" = "Aug 2021"
"EP. 55 鬼月特輯：娃娃很感謝你" = "Aug 2021"
"EP.54 二宮趴兔，越老越有錢" = "Aug 2021"
"【本週提醒】如何讓生活歸位呢？" = "Aug 2021"
"EP.53 與神對話" = "Aug 2021"
"EP.52 跨世紀的對話" = "Aug 2021"
"【本週提醒】還能比現在更正能量爆棚嗎？" = "Aug 2021"
"EP.51 當爸的求生意志有多強  ft.台通" = "Jul 2021"
"EP.50 二宮，你的賺錢說明書" = "Jul 2021"
"【本週提醒】回魂囉，慢慢回歸正軌囉！" = "Jul 2021"
"EP.49 哪個星座是職場寵兒？請支援輸贏！" = "Jul 2021"
"【本週提醒】不得不轉型，不要被恐懼綁架了～" = "Jul 2021"
"EP.48 我要公開一個秘密..." = "Jul 2021"
"EP.47 生氣其實沒那麼難" = "Jul 2021"
"【本週提醒】任何跟家有關的事浮上檯面，家庭關係如何呢？" = "Jul 2021"
"EP.46 火星星座最終回：難搞的都在這裡了" = "Jul 2021"
"EP.45 選擇障礙的人請進" = "Jul 2021"
"【本週提醒】那個討厭的人，也可能是你的導師喔" = "Jul 2021"
"【直播】五宮沒星的人莫慌，我來安慰你們了" = "Jul 2021"
"EP.44  五宮，天生我材一定會被看見的星" = "Jun 2021"
"【本週提醒】生活上的對立可能會浮上檯面，好好整理人生吧…" = "Jun 2021"
"EP.43 假裝專心" = "Jun 2021"
"EP.42 火星星座趴兔：這集的都好高調啊！" = "Jun 2021"
"【本週提醒】水象能量強的現在，可以多照顧自己內在喔！" = "Jun 2021"
"EP.41 討厭某個星座，越吸引那個星座…" = "Jun 2021"
"【本週提醒】過度樂觀的後遺症可能爆發喔！" = "Jun 2021"
"EP.40 靈活的犯罪者唐老師" = "Jun 2021"
"EP.39 大家差點要沒有唐老師" = "Jun 2021"
"【本週提醒】火能量高張，大家撐住！" = "Jun 2021"
"EP.38 火星讓你如此迷人" = "Jun 2021"
"【本週提醒】對照顧自己的人特別有感，桃花就這樣來了..." = "May 2021"
"EP.37 我也想娶新垣結衣" = "May 2021"
"EP.36 怪的潛力" = "May 2021"
"【本週提醒】離職、生涯規劃改變，變數很多的一週" = "May 2021"
"EP.35 我們是座小島也是艘大船" = "May 2021"
"EP.34 月亮星座趴三：不要逞強" = "May 2021"
"【本週提醒】容易被迷惑，小心騙子！！" = "May 2021"
"EP.33 壞份子，牧師界的異端？ft.陳思豪" = "May 2021"
"【本週提醒】跟人溝通時，不要用壓制的方式喔！" = "May 2021"
"【直播】不想努力了，其實是一個危險的想法" = "May 2021"
"EP.32 月亮星座趴兔：月亮才是自己的大boss" = "May 2021"
"【本週提醒】整理關係的好時機" = "May 2021"
"EP.31 好好療傷很難嗎？" = "Apr 2021"
"【本週提醒】情緒化，處理自己黑暗面的好時機" = "Apr 2021"
"EP.30 唐老師也是有在跑趴的" = "Apr 2021"
"【本週提醒】太正常不行，怪怪的東西崛起了！" = "Apr 2021"
"EP.29 月亮星座：找到你的命定工作" = "Apr 2021"
"【本週提醒】金星進金牛，值得用美食療癒自己" = "Apr 2021"
"EP.28 脫韁的魔羯男 ft.鳳梨鼠薯" = "Apr 2021"
"【本週提醒】不要害怕吵架！" = "Apr 2021"
"EP.27 for年輕人跟焦慮的人" = "Apr 2021"
"EP26. 有些星座就是會碰碰撞撞 ft.瑞瑪席丹" = "Mar 2021"
"【本週提醒】以為努力就能獲得的事情，可能要換個方式喔！" = "Mar 2021"
"EP25. 雙子座除了帥哥還有出宅男 ft.志祺77" = "Mar 2021"
"【本週提醒】會比較沒耐心，謊言也比較容易被戳穿" = "Mar 2021"
"EP. 24 星座小祕密：雙魚比處女更愛碎碎念" = "Mar 2021"
"【本週提醒】春分了，想做的，可以去做了" = "Mar 2021"
"EP.23 好好說話很難嗎？" = "Mar 2021"
"【本週提醒】可以多看展～促進思想活絡喔！" = "Mar 2021"
"EP.22 上升星座趴兔，還真的有長相空洞的上升星座" = "Mar 2021"
"【本週提醒】很多事情，以退為進是比較聰明的做法" = "Feb 2021"
"EP.21 生存之道：不要跟女生聊減肥ft.阿滴" = "Feb 2021"
"【本週提醒】水逆終於結束了！！" = "Feb 2021"
"EP.20 射手座有大屁股也是跌倒王 feat.甯甯" = "Feb 2021"
"【本週提醒】土天四分，你的理財觀念一定會改變" = "Feb 2021"
"EP.19 金牌回來了！" = "Feb 2021"
"EP.18 50萬的棺材vs.5萬的液晶電視" = "Feb 2021"
"【本週提醒】新年快樂！需要大量溝通的一週" = "Feb 2021"
"EP.17  上升星座，看你是長相空靈還空洞" = "Feb 2021"
"【本週提醒】小心黑歷史被挖出來喔!!" = "Jan 2021"
"EP.16 各種星座犯罪者：雙字輩星座都是天使與惡魔" = "Jan 2021"
"EP.15 水逆讓你想念前任QQ" = "Jan 2021"
"【本週提醒】壓力疊加，大家都忙爆了吧？" = "Jan 2021"
"EP.14 光頭抽到髮香水，就像我抽到衛生棉" = "Jan 2021"
"【本週提醒】以為彎腰撿東西沒事，結果就扭傷了…" = "Jan 2021"
"EP.13 交友軟體上的小綿羊：唐老師" = "Jan 2021"
"【本週提醒】水星準備做亂，備份起來！！" = "Jan 2021"
"Ep.12 伴侶跟你同星座，也許是你很自戀…" = "Jan 2021"
"【本週提醒】火能量太大，小心一言不合就吵架…" = "Jan 2021"
"Ep.11  炎上系偶像?炎亞綸來了！" = "Dec 2020"
"Ep.10醒酒湯：勇敢奇怪吧！" = "Dec 2020"
"Ep.9  聊星座：天王星金牛到底是什麼啦？feat. 倫倫/ 一點點誠誠" = "Dec 2020"
"EP.8 和最不相信星座的人聊天 feat.台通" = "Dec 2020"
"EP.7  時代真的不一樣了：唐老師老了嗎？" = "Dec 2020"
"EP.6 最少根筋的事：本集再次得罪處女座" = "Nov 2020"
"EP.5 你為什麼不信星座？ feat. 直男代表Kirk" = "Nov 2020"
"EP.4  難以理解的事：50公斤的唐老師" = "Nov 2020"
"EP.3 好的場面話保你一生平安 feat.小編卡蘿                                      " = "Nov 2020"
"EP.2 喝醉酒後的蠢事：合法ㄎㄧㄤ掉的方法" = "Oct 2020"
"EP.1 你不為人知的怪癖：性幻想時會打噴嚏？feat. 天秤座經紀人" = "Oct 2020"
