"EP327 粉紅泡泡是真的ft.靈能者小湛" = "https://open.spotify.com/episode/4sttV3J12Vw0nBf1VBP1P7"
"EP326 木星進雙子的機智生活" = "https://open.spotify.com/episode/18OO4KJOnGmna1ZrnedIS8"
"【本週提醒】多把力氣用在不會受傷的地方！" = "https://open.spotify.com/episode/1jsDXPLBDLabpyDBPPB6cY"
"EP325月亮星座，你藏最深的脆弱面(下)" = "https://open.spotify.com/episode/2IdZ2Rvvvngf4uqe8SvzHd"
"EP352月亮星座，你藏最深的脆弱面(下)" = "https://open.spotify.com/episode/2IdZ2Rvvvngf4uqe8SvzHd"
"EP324 有星系列(金牛)：持久力的配置" = "https://open.spotify.com/episode/4ZuOMJJCHzjLppiEolQUmx"
"【本週提醒】人心難測，不要太快一廂情願喔" = "https://open.spotify.com/episode/3r5SurP7alyktvHveenGDR"
"EP323 12星座的高階發展" = "https://open.spotify.com/episode/3uxe40riFyooiwgQAv4Z7X"
"EP322 月亮星座，你藏最深的脆弱面" = "https://open.spotify.com/episode/6X3EfuqqwSjkttwaf9UkhO"
"【本週提醒】不要怕，沒有危機，就沒有突破" = "https://open.spotify.com/episode/1oWso8GkCDrRHj4TH7NTiE"
"EP321好看的劇本都是不幸福時寫的ft.徐譽庭" = "https://open.spotify.com/episode/7HF6vgjIE4YhSYBJRDgrEP"
"EP320 占星冷知識 (水瓶的淚腺?" = "https://open.spotify.com/episode/60LM4w15aKZGenMO01uBND"
"EP319 占星冷知識 (水瓶的淚腺?" = "https://open.spotify.com/episode/60LM4w15aKZGenMO01uBND"
"【本週提醒】水星進金牛，揭露你對自己滿不滿意" = "https://open.spotify.com/episode/2Dku230aizINCCO2iANOVY"
"EP319 真的沒曖昧過ft. 驚奇玩起來Eko、Sandra" = "https://open.spotify.com/episode/7pRnUFLzUTpiKCGF5PYjNx"
"EP318 有星系列(牡羊)：獨特的配置" = "https://open.spotify.com/episode/0FiyP6UeNAqmfvgJ8WuYJV"
"【本週提醒】找回生活秩序吧！" = "https://open.spotify.com/episode/0Pvw5BnevdL8UEq3F2chMx"
"EP317 海王星(下)，給你大好或大壞" = "https://open.spotify.com/episode/3JOHUgecqEh5lY2RFTR62N"
"EP316 喊我就爛的人其實超努力" = "https://open.spotify.com/episode/79V8UApUBAeylRL5xuCMC2"
"【本週提醒】記得把焦點放回自己身上👀" = "https://open.spotify.com/episode/1yWoqvoU4JVuskDbvzVOac"
"EP315 向宇宙下訂單的體質 ft.蔡健雅" = "https://open.spotify.com/episode/2qynfmaULm1aWxmshY0Usx"
"EP314 九宮飛星，星盤中藏不住的幸運(下)" = "https://open.spotify.com/episode/0JZRXlhyBCtXaseiAjMoge"
"【本週提醒】比起自我欺騙，不如好好修補錯誤🔧" = "https://open.spotify.com/episode/0lh33qOgHkUojT2WBXHtMb"
"EP313 海王星，給你大好或大壞" = "https://open.spotify.com/episode/6WvZCdAKZNwxtAPhMl0Rgt"
"海王星，給你大好或大壞" = "https://open.spotify.com/episode/6WvZCdAKZNwxtAPhMl0Rgt"
"EP312 道理我都懂，啊又做不到ft.周慕姿" = "https://open.spotify.com/episode/1LTfVsFl2v9vuvT2F0ehsR"
"【本週提醒】覺得不對勁的事情，可以開始改變了" = "https://open.spotify.com/episode/4bK2wj3OcMj1LaAlTqDwQQ"
"EP311 九宮飛星，星盤中藏不住的幸運" = "https://open.spotify.com/episode/09MWIbJR2GodXtiVV26kXp"
"EP310 保持焦慮是有野心的表現？" = "https://open.spotify.com/episode/146nk3vQjDAAmbidXkB99P"
"【本週提醒】主動迎來改變吧！" = "https://open.spotify.com/episode/5hVA6DgUk9Nhbg4jrGhZTm"
"EP309 金星進牡羊，你的水逆救生圈" = "https://open.spotify.com/episode/7eoIGBGecA9lGJbEhVAwlS"
"【本週提醒】讓子彈飛一會，不要太快反應⚡️" = "https://open.spotify.com/episode/1fr5xM2KypVbE73rsqdMci"
"EP308 感情不順都是肝的問題？ft.簡少年" = "https://open.spotify.com/episode/13fLQwBdcYMEzdwl1yBFSH"
"EP307 12星座男的戀愛空間" = "https://open.spotify.com/episode/0HKleXlWZFW6WoInhPC2mz"
"【本週提醒】驟變也有可能是變好喔！" = "https://open.spotify.com/episode/4wMxFvnUlZ8jDfyRrayDRN"
"EP306 相位：星盤中的禮物或挑戰" = "https://open.spotify.com/episode/4jps5Fa5MOM2GqDx4nzaRj"
"EP305 2024桃花神攻略" = "https://open.spotify.com/episode/3VnKPusihXXNSKMFyFsqhC"
"【本週提醒】春分來了，新的開始來了⚡️" = "https://open.spotify.com/episode/7mYBAxDNpHrTY8NOE1lQqO"
"EP304 攻略系列：曖昧當面試的魔羯男" = "https://open.spotify.com/episode/5QJmH24qI4GY6RmCTYL7Jr"
"EP303 當月亮同星座住在一起(下)" = "https://open.spotify.com/episode/35FCCtHMzb5suxPwdWShs9"
"【本週提醒】把握那些靈光乍現的奇蹟時刻🤩" = "https://open.spotify.com/episode/57IMt6XfXUNnmr96E8CHFV"
"EP302 12星座PUA自救法" = "https://open.spotify.com/episode/2jyXRYoCwjDopMKSEgNmaX"
"EP301 當月亮同星座住在一起" = "https://open.spotify.com/episode/7r3bdn7z4qAFfMMOinjd7O"
"【本週提醒】原本排斥的，現在可以接受了⋯" = "https://open.spotify.com/episode/1RBaZMpHtPwuuCywXGgXsl"
"EP300 先揍你再給糖吃，土星(下)" = "https://open.spotify.com/episode/39VWLFVhF0G4Klqf59wS8V"
"EP299 水星進雙魚的讀空氣指南" = "https://open.spotify.com/episode/2V8rolzwK88czSjO9oYhUi"
"【本週提醒】用心感受雙魚能量滿滿的一週" = "https://open.spotify.com/episode/3BKmKox7NM2hO8zJO5AsEO"
"EP298 有星系列(水瓶)：前瞻性的配置" = "https://open.spotify.com/episode/3kRtUvHkAA9NVChXk4dT8U"
"EP297 先揍你再給糖吃，土星" = "https://open.spotify.com/episode/1stjauhgk6QZkzQ8oxnl4U"
"【本週提醒】努力讓生活恢復正常" = "https://open.spotify.com/episode/49E72OPS9ned3uxTE3ablW"
"EP296 12星座獨特忍功" = "https://open.spotify.com/episode/16P2B9fbq5fINMqtkLIgjn"
"EP295 跟12星座相處的各種不要" = "https://open.spotify.com/episode/2Gug7Tly7g7Yx3jpCK2WXn"
"【本週提醒】這個年關，頗有壓力" = "https://open.spotify.com/episode/7MlZzFlgJ4G07lI14iDyMi"
"EP294 星盤缺元素＝你最突出的地方" = "https://open.spotify.com/episode/7uCasNLhJottEzHv301XHF"
"EP293 有星系列(魔羯)：菁英的配置" = "https://open.spotify.com/episode/4LROOxpgCPBq2hpwCiOSTj"
"【本週提醒】所有的不正常，也許都是正常" = "https://open.spotify.com/episode/72LqM2xdeonEP2nZNLtzX7"
"EP292 火象星座攻略守則（獅子男）" = "https://open.spotify.com/episode/4a0BxOWjG8z35PtycwBbvy"
"EP291 12宮飛星，你帶天命的地方(下)" = "https://open.spotify.com/episode/47gEShB5v3lYMpl8Hni3J0"
"【本週提醒】什麼叫做苦的很甘願？" = "https://open.spotify.com/episode/4ZChaE9M2tLWsnSasrFJ1M"
"EP290 12宮飛星，你帶天命的地方" = "https://open.spotify.com/episode/6J8V8TrDThO15tdk8fkvRK"
"EP289 戀愛腦星座" = "https://open.spotify.com/episode/1SRrHzaMWNs2NjLorcdgXB"
"【本週提醒】收拾好情緒，觀察身邊的變化" = "https://open.spotify.com/episode/1lWA6QBJkkyKgOWvrt0IqC"
"EP288 火星進魔羯的抗壓指南" = "https://open.spotify.com/episode/7qEgkwXyYaqV0kudZUehkr"
"EP287 12星座小祕密" = "https://open.spotify.com/episode/6vm79pqLSrMLuEqfv6VS0P"
"【本週提醒】感受一下又魔幻 又粗暴的能量" = "https://open.spotify.com/episode/3uMEPx8AN6A9bKy8YqFGu7"
"EP286水星火象也是可以好好溝通啦ft.郎祖筠" = "https://open.spotify.com/episode/3lktNxxKU5oP5okAz4PJ1U"
"EP285 12星座不改變來不及的事" = "https://open.spotify.com/episode/6bXIVF2tU3M4cLDVtUEiCn"
"【本週提醒】新年快樂" = "https://open.spotify.com/episode/1xMPwnkgfQR96xki8EMLdI"
"EP284 含金量高的運勢問答來啦" = "https://open.spotify.com/episode/09HiOv9YJZPg0O9phzB0T6"
"EP283此生不會好的傷，凱龍星" = "https://open.spotify.com/episode/0dGUOdgL79s1EZ6HW2C3gZ"
"【本週提醒】好好感受2023的最後一週" = "https://open.spotify.com/episode/5hUntsWjEBb12wiuP1BrUT"
"EP282 單身勝利組" = "https://open.spotify.com/episode/5ydsaXlCVg3cwJ4yAXy1En"
"EP281 火星，你的達標力(下)💣" = "https://open.spotify.com/episode/4nzxQnccgnOKwlknDj365Z"
"【本週提醒】變數很多的一週，冬至嘛" = "https://open.spotify.com/episode/61lsGPrg1QLceGgjMSHoP0"
"EP280 月老廟的月老團隊ft.Misc" = "https://open.spotify.com/episode/0CPnyOIqPYx4dd8FiG4zrf"
"EP279 有星系列(射手)：幸運的配置" = "https://open.spotify.com/episode/7Hoq3VftvAdS3X3CA4ppkE"
"【本週提醒】錢の大躍進" = "https://open.spotify.com/episode/06JwVIVXVbZ3JnzyyWFR6Y"
"EP278 星座戀愛都市傳說6 情路不順破解法" = "https://open.spotify.com/episode/7sRHujk0RDZRqIrt5wm9ZR"
