"EP77｜頌缽師 ft.Ashley" = "extra"
"講話好好講M3 #ep66 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"當影片掌握在老公手上時😎 #ep70 #簡少年 #現代命運設計課 #低於六折 #現省4000元起 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"老師講話要小心內 #ep66 #里民服務中心 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"很像怪獸電力公司的門 #ep68 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"我愛大家❤️ #ep67 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"突然開發一個齊耳眉型 #ep66 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"喜怒無常😘🤬 #ep67 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"欸不可能這麼好騙吧🫲 #神仙補習班ep69 #謝依霖 #陳品豐 #丹丹老師 #shorts" = "extra"
"差點把小胖逼到絕路🐒 #神仙補習班ep69 #謝依霖 #陳品豐 #丹丹老師 #shorts" = "extra"
"錄一整天還真只有這場畫質出問題🙈 #神仙補習班ep70 #謝依霖 #陳品豐 #丹丹老師 #shorts" = "extra"
"沒事不用買，卡住買就通？ #神仙補習班ep70 #謝依霖 #陳品豐 #丹丹老師 #shorts" = "extra"
"EP73｜雞湯閒聊" = "extra"
"靜心頌缽-Ashley" = "extra"
"EP77｜頌缽師 ft.頌缽愛希 Ashley" = "extra"
"靜心頌缽-Ashley 頌缽愛希" = "extra"
"都是業障呀😭 #ep71 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"三寶基因序列已上線#ep71 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"恭喜發財 #ep72 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"我看了什麼🌝 #ep72 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"我也可以付出❤️#ep73 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"愛自己愛過頭？ #ep73 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"觀音社牛症 #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"媽，我還缺一點頭期❤️ #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"皮在癢🐆 #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"還是愛媽媽啦❤️ #ep75 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"那位同學後來跑去演戲了🤣 #ep76 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"EP82｜火的魔法 ft.江江" = "extra"
