"三寶基因序列已上線#ep71 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"恭喜發財 #ep72 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"我看了什麼🌝 #ep72 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"我也可以付出❤️#ep73 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"愛自己愛過頭？ #ep73 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"觀音社牛症 #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"媽，我還缺一點頭期❤️ #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"皮在癢🐆 #ep74 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"還是愛媽媽啦❤️ #ep75 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"那位同學後來跑去演戲了🤣 #ep76 #謝依霖 #陳品豐 #丹丹老師 #神仙補習班 #shorts" = "extra"
"EP82｜火的魔法 ft.江江" = "extra"
