[spotify]
"#202 微雷《小丑：雙重瘋狂》你也陷入導演陷阱了嗎？ 這部片從宣傳開始就充滿了心理暗示｜嗚喵備忘錄" = "https://open.spotify.com/episode/4KOgz4lBfow7wZZriYueUG"
"#201 不做Podcast，做youtuber比較好賺？也不一定啦！閒聊系列+哈拉瑞《連結》簡單隨便翻翻第一印象｜嗚喵備忘錄" = "https://open.spotify.com/episode/2XKmxy8NjluTMxOvl3CIZm"
"#200 這本小說我有親身經歷，過度親切真的很可怕《鄰居》、《法醫女王》、《高效海綿閱讀法》簡單導讀｜嗚喵備忘錄" = "https://open.spotify.com/episode/4Zj7TFS4HnLKJiWHZ8aSag"
"#199 在愛妮島的海灘上看《 我在amazon上班 需要紅酒與心理師 》好像太嘲諷了｜嗚喵備忘錄" = "https://open.spotify.com/episode/2AwmlIHVsswDWkLRjJUjDZ"
"#198 3本 小說 觀後感《奇蹟淚水管理局》《為了這個家，我殺了我自己》《正念殺機》｜嗚喵備忘錄" = "https://open.spotify.com/episode/5yWWf8kTEJ0UPaUz2avJLh"
"#197 回應關於我分享盜版漫畫APP截圖的問題 & 聊聊《你願意人生就值得》蔡康永的新作｜嗚喵備忘錄" = "https://open.spotify.com/episode/4hA2ZFPzgqA0IOSjsRCxDk"
"#196 媽媽得了癌症，一小時長片道出年輕人不敢說的心聲｜嗚喵備忘錄" = "https://open.spotify.com/episode/6Lpflh9jxjKBb80jEOviho"
"#195 【完整暴雷版】開高走低但還是看到早上四點的推理小說《黑色亡魂》我個人偏推薦啦｜嗚喵備忘錄" = "https://open.spotify.com/episode/1tVbbuGkItLXVlip2F1uw5"
"#194 差點在東京跟老公吵起來，男女逛街態度差好多《可以生氣，但不要發脾氣》實際運用｜嗚喵備忘錄" = "https://open.spotify.com/episode/3fu1HgLpf7qTT4liasMUOo"
"#193 微雷影評，爸爸你是連環殺人兇手嗎？《圈套》喬許哈奈特演技爆炸｜嗚喵備忘錄" = "https://open.spotify.com/episode/7D6fsEUArx57OgyqNHREqG"
"#192 人生必讀中的必讀，顛覆行動力！看完絕對加速人生100%的經典好書《隱性潛能》大推博客來版本｜嗚喵備忘錄" = "https://open.spotify.com/episode/0mzd7NOrCFPgNNiPSyXGaY"
"#191 婚姻的意義？如何維持好心情？貓仙姑Q&A 10題大哉問｜嗚喵備忘錄" = "https://open.spotify.com/episode/23nF46YpupCnGC8xwacKHU"
"#190 溝通，遠比你想的重要 《高產出的本事》會講話的人生！風生水起｜嗚喵備忘錄" = "https://open.spotify.com/episode/0qgosQjKEyiHvgwsCprOc1"
"#189 不是出於孝順才照顧你《錢先花光，還是命先沒了？：長照4個90歲老人的我，將如何面對老後生活？》百善孝為先個屁啦｜嗚喵備忘錄" = "https://open.spotify.com/episode/3WIkyVNBo1O4yhwoLITt1D"
"#188 越漂亮的女人越危險，媽媽囑咐過《家弒絕招》家弒服務第二集歃血登場｜嗚喵備忘錄" = "https://open.spotify.com/episode/5hLzj5ppZBewsPoV6dlsrd"
"#187 從「過度獨立」到「享受獨立」孤獨放馬過來啊！我才沒有哭呢｜嗚喵備忘錄" = "https://open.spotify.com/episode/06k2h6vGzwbeuAYzzGFliv"
"#186 當不了網紅才去做廣告人?! 《請叫我「遊民小姐」！：躺平、安靜離職很可以！勇敢出走，做自己人生的老闆》作者閃亮登場｜嗚喵備忘錄" = "https://open.spotify.com/episode/0lOdshcZSmUYbWmk2BnprO"
"#185 端午節快樂，閒聊系列：容易滿足真的不可以嗎？｜嗚喵備忘錄" = "https://open.spotify.com/episode/1RAIeTXykj9il2hmpecoxM"
"#184 善良跟我想得太不一樣了《慷慨的感染力》 比爾蓋茲年度推薦，這個世界最需要的一本書｜嗚喵備忘錄" = "https://open.spotify.com/episode/7z4zpahwToVpifeCZdmaO7"
"#183 這些事情不吐不快啊！拜託編輯們多配合《超爆蘋果橘子經濟學》太神奇的一本書｜嗚喵備忘錄" = "https://open.spotify.com/episode/7rZBs9jvL7ilhIXAxMxazM"
"#182 暴雷 2024 上半年最值得一看的本格推理小說《奪命炎上》網路生態可以多噁心｜嗚喵備忘錄" = "https://open.spotify.com/episode/16VgmQU5eIEdXDpf6TA5B3"
"#181 借力使力，才能輕鬆應對人生《焦慮是你的優勢》高敏感的人生勝利法｜嗚喵備忘錄" = "https://open.spotify.com/episode/0GdZDgCxC1XpbR1Yulw1Ei"
"#180 怎麼樣的母愛才不會是沉重的負擔？簡單說說《母愛的枷鎖，女兒的牢籠》《從我們開始》｜嗚喵備忘錄" = "https://open.spotify.com/episode/2rtNvFzkzbDKX6rNGQ48lv"
"#179 年收六億的醫生兼自媒體人，只要把工作當遊戲！連工作倦怠和拖延症都能不藥而癒《高效原力》Dr Ali Abdaal｜嗚喵備忘錄" = "https://open.spotify.com/episode/5CeH6sZAoJluukBc8F8wNw"
"#178 意料之外這次都靠 YOUTUBER 救場!! 白癡公主 真的 會演戲耶!!但《鬼天廈》還是救了個命的超難看｜嗚喵備忘錄" = "https://open.spotify.com/episode/1eDx7MLzd8JHHCQVEb2Gk1"
"#177 心態致勝是真的 ：自媒體上最大困難、如何面對刁難上司、伴侶不愛我了怎麼辦｜嗚喵備忘錄" = "https://open.spotify.com/episode/52TWIHRvhm5ew3wBTP097D"
"#176 不要當地攤貨，請保持你的稀有特質《體貼是練出來的》職場默默好人緣的關鍵｜嗚喵備忘錄" = "https://open.spotify.com/episode/4aepDQT01zkT5HiT9Px5lq"
"#175 和身體與飢餓和解，飲食焦慮從陷入到逃離的過程《我不餓但我就是想吃》Judson Brewer｜嗚喵備忘錄" = "https://open.spotify.com/episode/1gLEGbc1fzh6qr038de0NB"
"#174 人生沒有如果，只有結果和後果！盤點自己2024 Q1的表現｜嗚喵備忘錄" = "https://open.spotify.com/episode/00bOL5OZiiMVvLwAokDYLx"
"#173 你會喜歡這本書嗎《我，刀槍不入》不斷超越卓越的背後，是不是無法跟自己和解｜嗚喵備忘錄" = "https://open.spotify.com/episode/13XacaSZHn3mpINaxyN4dO"
"#172 貫徹知足常樂，所以《成不了大人物的我們，決定成為簡單的人》極簡生活的終極型態｜嗚喵備忘錄" = "https://open.spotify.com/episode/252WNwnUQWTOmgeB92GPRq"
"#171 比較心態可能會是你的人生加速器《逆習慣》我的人生必讀推薦｜嗚喵備忘錄" = "https://open.spotify.com/episode/0oGLbLOaBCLgjIVxK45XpU"
"#170 沒有你，就沒有我！國際書展事後感想，分享《心態致瘦》《從好公司輕鬆提款》的心得｜嗚喵備忘錄" = "https://open.spotify.com/episode/0XCARQDJmZUsTF44ffSjIh"
"#169 不理財真的不行了，推薦以及不推薦的兩本理財書《從好公司輕鬆提款》《想要脫窮，先買張股票》｜嗚喵備忘錄" = "https://open.spotify.com/episode/6dBZr1OTJmGyAHKlNAtnGv"
"#168 (無雷推薦) 我求妳各位都一定要去看《可憐的東西》+ 過年期間可以看《隱蔽嫌疑人》推理小說｜嗚喵備忘錄" = "https://open.spotify.com/episode/2sCedqVkNwzfjshXaVI6ij"
"#167 紀錄時間一個月後的改變 《發現我的多重職涯組合》枕邊人也默默被影響了嗎" = "https://open.spotify.com/episode/6zzsyGHu5tHLCJgRxGwCL8"
"#166 不知道不會怎麼樣，知道了會很不一樣！廣告圈最熱血的傳奇人物 Wawa 來啦｜嗚喵備忘錄" = "https://open.spotify.com/episode/55Hu7G976vFiii1fvyQG1M"
"#165 我在電影《金手指》學到的三件事 梁朝偉、劉德華，再度贏得全面勝利｜嗚喵備忘錄" = "https://open.spotify.com/episode/76EQ5vhJluOScOsQQzOTqK"
"#164 增加 2024 的行動力《好奇心行動攻略》年度目標達成率救星｜嗚喵備忘錄" = "https://open.spotify.com/episode/5kYdRtbNcQqk8a4SiaDLJC"
"#163 2024 新年新希望！是不是要來借貓手了...｜嗚喵備忘錄" = "https://open.spotify.com/episode/0ar08ZFmHeKP9PUy16IiEw"
"#162 努力不懈 或 躺平放棄，你選哪個《投降輸一半》｜嗚喵備忘錄" = "https://open.spotify.com/episode/4omw4NcY8RuQRUeOz9CQkB"
"#161 史蒂芬金大推，年度必讀推薦的小說《詭畫連篇》｜嗚喵備忘錄" = "https://open.spotify.com/episode/58lw8JZTezlW1XqzuiMkfx"
"#160 這本書真的超難看｜嗚喵備忘錄" = "https://open.spotify.com/episode/0Q9ixqOLuM7syprt6v1HSY"
"#159 沒有誰是壞人，我們都只是有時候會做壞事的人《以我們告終》It Ends with Us｜嗚喵備忘錄" = "https://open.spotify.com/episode/0lm6j52rLlQLBFlHRanXK0"
"#158 要你創新，公司卻懲罰犯錯的人？鼓勵團隊合作，卻獎勵個人績效？簡單聊聊《誘因設計》｜嗚喵備忘錄" = "https://open.spotify.com/episode/4Y2HNKseyZiYtzbiWzeMpH"
"#157 用 繪畫 克服我的 心魔｜嗚喵備忘錄" = "https://open.spotify.com/episode/4g3BkX9tZ1iXeasbqnIx5A"
"#156 萬聖節特別節目！那些年我們看過的 恐怖小說＆ 新生代作家 阿泉來堂《 泣女大人 》《 緇衣巫女 》｜嗚喵備忘錄" = "https://open.spotify.com/episode/0kNlTghENAxEQUKeZHVMNX"
"#155 這本書要小心看！絕對不是給月光族找藉口 《別把你的錢留到死》補充說明｜嗚喵備忘錄" = "https://open.spotify.com/episode/6d0cGTYvLLQzVvLisIxCts"
"#154 花月殺手 觀影前須知，你認為的 善良 可能只是停留在表面而已《 善行 》分析角色｜嗚喵備忘錄" = "https://open.spotify.com/episode/6kxqBPjVfYeoNlzi1B4sRt"
"#153 和老公一起去上理財課，從金錢焦慮到體感通膨 ＆ＹＴ猴子的小感嘆｜嗚喵備忘錄" = "https://open.spotify.com/episode/6mycPYpVE6sxFlYeKPygn6"
"#152 暴雷！宮崎駿最新大作《蒼鷺與少年》其實跟《你想活出怎樣的人生》一點關係都沒有?? 想看懂電影先來了解背景故事吧｜嗚喵備忘錄" = "https://open.spotify.com/episode/4Twonffe8LsALs1y4qm9xE"
"#151 接案人生與金錢焦慮該怎麼和平共處 《三千圓的用法》父債子償有解法嗎?｜嗚喵備忘錄" = "https://open.spotify.com/episode/5qRDBTbXvdk81TcRR9InQx"
"#150 無雷 心得分享 ，第四季 最後兩集逆轉勝《性愛自修室》長大就是這麼一回事｜嗚喵備忘錄" = "https://open.spotify.com/episode/4uzcgw3Es9Mp0XAz09saIH"
