"EP111 The Last of Episode" = "Mar 2023"
"EP110 當代戀愛必修（？）課" = "Mar 2023"
"EP109 逆。馬斯洛金字塔" = "Feb 2023"
"EP108 用政客的方式交往" = "Feb 2023"
"EP107 不錄了不錄了" = "Feb 2023"
"EP106 十天的年假結果做了什麼？" = "Feb 2023"
"EP105 春節乞丐" = "Jan 2023"
"EP104 歡迎光臨現在阿罵過世中" = "Dec 2022"
"EP103 HOHOHO聖誕特警" = "Dec 2022"
"EP102 境外勢力動起來" = "Dec 2022"
"EP101 超級政見生死鬥" = "Nov 2022"
"EP100 全台選舉大預測" = "Nov 2022"
"EP99 二十大賓果" = "Oct 2022"
"EP98 丟臉丟大了" = "Oct 2022"
"EP97 叫爸叫媽 到我為止" = "Oct 2022"
"EP96 台北人的社交生存法" = "Oct 2022"
"EP95 台北人觀察圖鑑" = "Oct 2022"
"EP94 盜亦有道" = "Sep 2022"
"EP93 台灣的王" = "Sep 2022"
"EP92 烤肉的文化衝擊" = "Sep 2022"
"EP91 House of 蘭陽" = "Sep 2022"
"EP90 你就是牙醫師的麥克風 feat. 瞇瞇眼" = "Aug 2022"
"EP89 拖延病患者的快樂" = "Aug 2022"
"EP88 給長輩一個 RESPECT" = "Aug 2022"
"EP87 當一個不專情的選民" = "Jul 2022"
"EP86 得了直男病的女子" = "Jul 2022"
"EP85 愛情就像一隻攀岩的貓" = "Jul 2022"
"EP84 直男檢討會" = "Jul 2022"
"EP83 來講講講講蔣萬安" = "Jun 2022"
"EP82 我的確診日記" = "Jun 2022"
"EP81 勢利眼！開眼！" = "Jun 2022"
"EP80 求婚大作戰" = "May 2022"
"EP79 假如伍佰老師舔共 ...... ？" = "May 2022"
"EP78 攀岩時發出的聲音" = "May 2022"
"EP77 渣男大考驗" = "May 2022"
"EP76 要不要看尼斯湖水怪？" = "Apr 2022"
"EP75 自行車道爭霸戰" = "Apr 2022"
"EP74 最佳約會行程" = "Apr 2022"
"EP73  冷風中站了七分鐘" = "Mar 2022"
"EP72 不是宜蘭嗎？怎麼變波蘭！！" = "Mar 2022"
"EP71 你看起來就是那種人啊！" = "Mar 2022"
"EP70 時代革命 & 烏克蘭" = "Mar 2022"
"EP69 一個十年還是十個各一年？" = "Feb 2022"
"EP68 絕對會讓你想砸車的歌" = "Feb 2022"
"EP67 我是被地中海滋養的" = "Feb 2022"
"EP66 你所不知道的袋鼠媽媽" = "Jan 2022"
"EP65 火鍋裡的小驚喜" = "Jan 2022"
"EP64 辣個男人終於來了" = "Jan 2022"
"EP63 給我付出代駕吧！！" = "Jan 2022"
"EP62 真的有王力宏了" = "Dec 2021"
"EP61 被王力宏淹沒的公投" = "Dec 2021"
"EP60 刻在你禮物上的名字" = "Dec 2021"
"EP59 淺談冠廷宇宙" = "Dec 2021"
"EP58 難吃的食物是創作的養分" = "Nov 2021"
"EP57 藏到自己都找不到" = "Nov 2021"
"EP56 你那時候難過多久？" = "Nov 2021"
"EP55 做好準備的人才能過萬聖節" = "Oct 2021"
"EP54 孩子們心中的 007" = "Oct 2021"
"EP53 冷血男的眼淚" = "Oct 2021"
"EP52 如何與劍術大師對決" = "Oct 2021"
"EP51 你相信黨嗎？" = "Oct 2021"
"EP50 一周年紀念" = "Sep 2021"
"EP49 囚犯困境" = "Sep 2021"
"EP48 關於愛情的靈魂拷問" = "Sep 2021"
"EP47 承認吧人就是這麼自私" = "Aug 2021"
"EP46 竟然敢自稱拉麵！？" = "Aug 2021"
"EP45 愛可以解釋一切" = "Aug 2021"
"EP44 How To Lose？" = "Aug 2021"
"EP43 史上第二和諧的留言區" = "Aug 2021"
"EP42 整集都是詐騙！？" = "Jul 2021"
"EP41 你的歌單都叫什麼名字？" = "Jul 2021"
"EP40 愛馬仕等級的炸" = "Jul 2021"
"EP39 廉價的恨" = "Jul 2021"
"EP38 不要一直想拉麵和牛肉湯" = "Jun 2021"
"EP37 登記打疫苗不要用谷歌表單奧" = "Jun 2021"
"EP36 真的是笑死" = "Jun 2021"
"EP35 想得卻不可得你奈疫苗何" = "Jun 2021"
"EP34 作秀的選擇" = "May 2021"
"EP33 第一次約會要去哪" = "May 2021"
"EP32 乖乖在家防疫不要亂跑" = "May 2021"
"EP31 平行時空的貓" = "May 2021"
"EP30 將核彈交給恐怖分子" = "May 2021"
"EP29 想成為獨角獸" = "Apr 2021"
"EP28 要做免治馬桶，不當中央空調" = "Apr 2021"
"EP27 在交友軟體上假扮成孔劉" = "Apr 2021"
"EP26 你要在這裡愛國你要先講" = "Apr 2021"
"EP25 只有我覺得是這樣嗎？" = "Mar 2021"
"EP24 台北人才懂的鄉愁啦" = "Mar 2021"
"EP23 一切都是心魔在作怪" = "Mar 2021"
"EP22 謝謝謝謝謝謝不好意思不好意思不好意思" = "Mar 2021"
"EP21 醫生寫的字真的不是外星文字嗎？" = "Feb 2021"
"SP 如何成就一個完美的情人節約會？" = "Feb 2021"
"EP20 寫作的人和寫作文的人" = "Jan 2021"
"EP19 有一天，人類會回想起國瑜統治的恐怖？" = "Jan 2021"
"EP18 我像不像許光漢？" = "Jan 2021"
"EP17 吃烤鴨時會思考的哲學問題" = "Jan 2021"
"EP16 發文前不給經紀人看是一件勇敢冒險的事" = "Jan 2021"
"EP15 欸你知道「瞎掰」的中國用語是什麼嗎？" = "Dec 2020"
"EP14 如何向重要的人事物道別？以中天為例" = "Dec 2020"
"EP13 只准信徒放炮，不許百姓打砲" = "Dec 2020"
"EP12 有些動態回顧跳出來真的很羞恥" = "Dec 2020"
"EP11 在中天找到一片藍海的饒舌歌手" = "Nov 2020"
"EP10 突然發現自己應該去開一間公關公司" = "Nov 2020"
"EP9 六都市長拳擊擂台賽" = "Nov 2020"
"EP8 這則新聞我要給一千一百二十顆星星" = "Nov 2020"
"EP7 智能社會進退兩難，性感荷官線上發牌？？/ 回覆 YT 會員留言" = "Nov 2020"
"EP6 和烏克蘭勾結叫做通烏門，那和剛果私通是什麼門？" = "Oct 2020"
"EP5 史上最綜藝的一次業配拍攝" = "Oct 2020"
"EP4 我們終於向行車紀錄器下跪了" = "Oct 2020"
"EP3 月圓人團圓，辣個跟著月亮走的男人會來團圓嗎？" = "Oct 2020"
"EP2 魏德聖訪後心得 / 寫信告訴我今天公視是什麼顏色" = "Sep 2020"
"EP1 很多秘密沒辦法藏一輩子" = "Sep 2020"
"［EP1 補充教材］時力退黨黨員登《央視會客廳》之全程錄音" = "Sep 2020"
"EP0 本台全程未參與《六點半左右》的節目製作" = "Sep 2020"
"Teaser｜《地下電台一分鐘》" = "Sep 2020"
