"EP111 The Last of Episode" = "https://open.spotify.com/episode/5T0yXrghVmBw5OA8eQyslL"
"EP110 當代戀愛必修（？）課" = "https://open.spotify.com/episode/0mcGDESMCwUq53sLJa1XWw"
"EP109 逆。馬斯洛金字塔" = "https://open.spotify.com/episode/3QyRzVbREb05sewu9gskf5"
"EP108 用政客的方式交往" = "https://open.spotify.com/episode/649kmE0m4ehUrwrRmF5NXy"
"EP107 不錄了不錄了" = "https://open.spotify.com/episode/1Yp0TxRxJvPxVL0YfL1T5J"
"EP106 十天的年假結果做了什麼？" = "https://open.spotify.com/episode/6El3IQoCUpL9wqHbG8fCtG"
"EP105 春節乞丐" = "https://open.spotify.com/episode/6luQWYNs1Qx2QC6O7eJpCg"
"EP104 歡迎光臨現在阿罵過世中" = "https://open.spotify.com/episode/0gQ4Ol5kXF5Bxh2pWtUQzW"
"EP103 HOHOHO聖誕特警" = "https://open.spotify.com/episode/0YqVk6n1HiICTpIdPd08cw"
"EP102 境外勢力動起來" = "https://open.spotify.com/episode/2Ykhl52x6pCnqbSbnZui2b"
"EP101 超級政見生死鬥" = "https://open.spotify.com/episode/3MhqPnUXF5l4spT6lTlrjx"
"EP100 全台選舉大預測" = "https://open.spotify.com/episode/1rknaoo96sfDbe8410xMTD"
"EP99 二十大賓果" = "https://open.spotify.com/episode/1p5nn7007UPLkhjTUB1M0O"
"EP98 丟臉丟大了" = "https://open.spotify.com/episode/23vL3piMgibrP3NxGFKFtM"
"EP97 叫爸叫媽 到我為止" = "https://open.spotify.com/episode/6yrVYlNXJfqEh17PWRjRZ4"
"EP96 台北人的社交生存法" = "https://open.spotify.com/episode/4i8076FpNj9wt2CDrXPzSV"
"EP95 台北人觀察圖鑑" = "https://open.spotify.com/episode/4SpLqpMHaXWybqoeEt0TRc"
"EP94 盜亦有道" = "https://open.spotify.com/episode/20T7R8Cn2QQcW42poSrfOE"
"EP93 台灣的王" = "https://open.spotify.com/episode/5bTQ0xmBLEUj5i9ZakeqHd"
"EP92 烤肉的文化衝擊" = "https://open.spotify.com/episode/7qSqq0HLwl0LVYqRUcxNnd"
"EP91 House of 蘭陽" = "https://open.spotify.com/episode/6jzVcZv1Vmy4cNWoV90TKs"
"EP90 你就是牙醫師的麥克風 feat. 瞇瞇眼" = "https://open.spotify.com/episode/55t8DoOHKHPLPzv5vRqjS0"
"EP89 拖延病患者的快樂" = "https://open.spotify.com/episode/13NZpFBC59vM8mOdiAleB2"
"EP88 給長輩一個 RESPECT" = "https://open.spotify.com/episode/7smWF1DBLCP2X0hsXg1TRm"
"EP87 當一個不專情的選民" = "https://open.spotify.com/episode/0kFIk7rAxHyGcGO891YZVM"
"EP86 得了直男病的女子" = "https://open.spotify.com/episode/12N3VCu1zmrHPd55RGN2ag"
"EP85 愛情就像一隻攀岩的貓" = "https://open.spotify.com/episode/1ahPyg5zqSr4x7eJDZjkVe"
"EP84 直男檢討會" = "https://open.spotify.com/episode/1HVQTZAfbZSNmaL8oZ0UxI"
"EP83 來講講講講蔣萬安" = "https://open.spotify.com/episode/1YyjOjiXRcmC279x7MMGEo"
"EP82 我的確診日記" = "https://open.spotify.com/episode/1mKiUQzlqyL4almJSnLXtJ"
"EP81 勢利眼！開眼！" = "https://open.spotify.com/episode/4wkGAkLY3OGBW4eSkrY7wX"
"EP80 求婚大作戰" = "https://open.spotify.com/episode/0TMQ57idDoxizzLVpGgbde"
"EP79 假如伍佰老師舔共 ...... ？" = "https://open.spotify.com/episode/1fWXz0jGYSWaie4Dgu5YVK"
"EP78 攀岩時發出的聲音" = "https://open.spotify.com/episode/1sIAshbJCPYArKo2Q64CfX"
"EP77 渣男大考驗" = "https://open.spotify.com/episode/3X5iuoVSBxrFBtatkJggIW"
"EP76 要不要看尼斯湖水怪？" = "https://open.spotify.com/episode/24PlbsJ57tWzxqH1G2WbWk"
"EP75 自行車道爭霸戰" = "https://open.spotify.com/episode/6DGWNzYYLpkkYwjHp4WmSz"
"EP74 最佳約會行程" = "https://open.spotify.com/episode/1HD9vkheDwXje83yqF4rgg"
"EP73 冷風中站了七分鐘" = "https://open.spotify.com/episode/68jNBsLxNjvh7XOK0zOjKl"
"EP72 不是宜蘭嗎？怎麼變波蘭！！" = "https://open.spotify.com/episode/7ob1uTH0wW84ckM6RbGFqA"
"EP71 你看起來就是那種人啊！" = "https://open.spotify.com/episode/4awTJyV1mIoxp8SsPZJnSv"
"EP70 時代革命 & 烏克蘭" = "https://open.spotify.com/episode/0ZJuJoM6fmQ76burgE0vlE"
"EP69 一個十年還是十個各一年？" = "https://open.spotify.com/episode/0NLu0vFeDudz5PM1Ijg0mF"
"EP68 絕對會讓你想砸車的歌" = "https://open.spotify.com/episode/4ITajRLwaJZwyumXyVKBqH"
"EP67 我是被地中海滋養的" = "https://open.spotify.com/episode/5ltw2N8wnmJNNDmKCnlEQs"
"EP66 你所不知道的袋鼠媽媽" = "https://open.spotify.com/episode/1tpVYWcAhoHFRPAW8X2hjn"
"EP65 火鍋裡的小驚喜" = "https://open.spotify.com/episode/2HCuqLTRFMqujRZxiuZR0C"
"EP64 辣個男人終於來了" = "https://open.spotify.com/episode/37bmezECgzL9S2PWve4X0S"
"EP63 給我付出代駕吧！！" = "https://open.spotify.com/episode/1hk8nJOLAf6dJxur7pf57p"
"EP62 真的有王力宏了" = "https://open.spotify.com/episode/0cICLFLZnNeI6Fc3K7m26P"
