blg00001 = ["valuen"]
blg00002 = ["valuen"]
blg00003 = ["valuen"]
blg00004 = ["valuen"]
blg00005 = ["valuen"]
blg00006 = ["valuen"]
blg00007 = ["valuen"]
blg00008 = ["valuen"]
blg00009 = ["valuen"]
blg00010 = ["valuen"]
blg00011 = ["valuen"]
blg00012 = ["valuen"]
blg00013 = ["valuen"]
blg00014 = ["valuen"]
blg00015 = ["valuen"]
blg00016 = ["valuen"]
blg00017 = ["valuen"]
blg00018 = ["valuen"]
blg00019 = ["valuen"]
blg00020 = ["valuen"]
blg00021 = ["valuen"]
blg00022 = ["valuen"]
blg00023 = ["valuen"]
blg00024 = ["valuen"]
blg00025 = ["valuen"]
blg00026 = ["valuen"]
blg00027 = ["valuen"]
blg00028 = ["valuen"]
blg00029 = ["valuen"]
blg00030 = ["valuen"]
blg00031 = ["valuen"]
blg00032 = ["valuen"]
blg00033 = ["valuen"]
blg00034 = ["valuen"]
blg00035 = ["valuen"]
blg00037 = ["valuen"]
blg00038 = ["valuen"]
blg00039 = ["valuen"]
blg00041 = ["valuen"]
blg00042 = ["valuen"]
blg00043 = ["valuen"]
blg00045 = ["valuen"]
blg00046 = ["valuen"]
blg00047 = ["valuen"]
blg00049 = ["valuen"]
blg00050 = ["valuen"]
blg00051 = ["valuen"]
blg00053 = ["valuen"]
blg00054 = ["valuen"]
blg00055 = ["valuen"]
blg00056 = ["valuen"]
blg00057 = ["valuen"]
blg00058 = ["valuen"]
blg00059 = ["valuen"]
blg00061 = ["valuen"]
blg00063 = ["valuen"]
blg00065 = ["valuen"]
blg00067 = ["valuen"]
blg00069 = ["valuen"]
blg00070 = ["valuen"]
blg00071 = ["valuen"]
blg00072 = ["valuen"]
blg00073 = ["valuen"]
blg00074 = ["valuen"]
blg00075 = ["valuen"]
blg00076 = ["valuen"]
blg00077 = ["valuen"]
blg00078 = ["valuen"]
blg00079 = ["valuen"]
blg00081 = ["valuen"]
blg00083 = ["valuen"]
blg00084 = ["valuen"]
blg00085 = ["valuen"]
blg00087 = ["valuen"]
blg00088 = ["valuen"]
blg00089 = ["valuen"]
blg00090 = ["valuen"]
blg00091 = ["valuen"]
blg00092 = ["valuen"]
blg00093 = ["valuen"]
blg00094 = ["valuen"]
blg00096 = ["valuen"]
blg00098 = ["valuen"]
blg00100 = ["valuen"]
blg00102 = ["valuen"]
blg00103 = ["valuen"]
blg00104 = ["valuen"]
blg00106 = ["valuen"]
blg00108 = ["valuen"]
blg00110 = ["valuen"]
blg00115 = ["valuen"]
blg00116 = ["valuen"]
blg00119 = ["valuen"]
blg00122 = ["valuen"]
blg00124 = ["valuen"]
blg00128 = ["valuen"]
blg00134 = ["valuen"]
blg00135 = ["valuen"]
blg00148 = ["valuen"]
blg00151 = ["valuen"]
blg00169 = ["valuen"]
blg00176 = ["valuen"]
blg00183 = ["valuen"]
blg00185 = ["valuen"]
blg00187 = ["valuen"]
blg00197 = ["valuen"]
blg00206 = ["valuen"]
blg00213 = ["valuen"]
blg00428 = ["valuen"]
blg00431 = ["valuen"]
blg00557 = ["valuen"]
blg00560 = ["valuen"]
blg00566 = ["valuen"]
blg00577 = ["valuen"]
blg00580 = ["valuen"]
blg00581 = ["valuen"]
blg00582 = ["valuen"]
blg00584 = ["valuen"]
blg00598 = ["valuen"]
blg00613 = ["valuen"]
blg00619 = ["valuen"]
blg00621 = ["valuen"]
blg00622 = ["valuen"]
blg00627 = ["valuen"]
blg00628 = ["valuen"]
blg00629 = ["valuen"]
blg00631 = ["valuen"]
blg00632 = ["valuen"]
blg00633 = ["valuen"]
blg00646 = ["valuen"]
blg00647 = ["valuen"]
blg00648 = ["valuen"]
blg00649 = ["valuen"]
blg00650 = ["valuen"]
blg00652 = ["valuen"]
blg00653 = ["valuen"]
blg00656 = ["valuen"]
blg00670 = ["valuen"]
blg00672 = ["valuen"]
blg00676 = ["valuen"]
blg00683 = ["valuen"]
blg00691 = ["valuen"]
blg00701 = ["valuen"]
blg00726 = ["valuen"]
blg00733 = ["valuen"]
blg00737 = ["valuen"]
blg00745 = ["valuen"]
blg00754 = ["valuen"]
blg00760 = ["valuen"]
blg00784 = ["valuen"]
blg00787 = ["valuen"]
blg00797 = ["valuen"]
blg00807 = ["valuen"]
blg00809 = ["valuen"]
blg00827 = ["valuen"]
blg00831 = ["valuen"]
blg00832 = ["valuen"]
blg00844 = ["valuen"]
blg00865 = ["valuen"]
blg00869 = ["valuen"]
blg00872 = ["valuen"]
blg00875 = ["valuen"]
blg00877 = ["valuen"]
blg00879 = ["valuen"]
