"rss" = "https://feeds.buzzsprout.com/1974862.rss"
"apple" = "https://podcasts.apple.com/tw/podcast/%E7%99%BE%E9%9D%88%E6%9E%9C-news/id1106847606"
# "google" = "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zb3VuZGNsb3VkLmNvbS91c2Vycy9zb3VuZGNsb3VkOnVzZXJzOjIyMTM2MTk4MC9zb3VuZHMucnNz"
"spotify" = "https://api.spotify.com/v1/shows/5Vv32KtHB3peVZ8TeacUty/episodes?market=TW&limit=50"
"youtube" = "https://www.youtube.com/feeds/videos.xml?channel_id=UCD2KoUc0f4Bv2Bz0mbOah8g"

[correct]
"\u200b" = ""
"啦‍♂️、" = "啦🙅‍♂️、"
"Russia\"" = "Russia”"
"旅游" = "旅遊"
"一周" = "一週"
"讀書會 傀儡花：" = "讀書會：傀儡花 "
# https://ronjabook.blogspot.com/2012/03/blog-post_25.html
"繞境" = "遶境"
"蓋亞納" = "蓋亞那"
" - 0" = " - #"
"The KK Show - #90 葉耀元教授" = "The KK Show - #91 葉耀元教授"
"心理咨商" = "心理諮商"
"荷花邊" = "荷葉邊"
"5，6" = "5、6"
"醫護人員We Love You、" = "醫護人員We Love You！"
"與在中國封城的聽眾聊天" = "歡迎被封城的聽眾來聊天"
"意面" = "意麵"
"泰皇" = "泰王"
"、、" = "、"
"巴賽隆納" = "巴塞隆納"
"魷魚游戲" = "魷魚遊戲"
"百靈果之友: 001 @阿滴英文" = "百靈果之友: 001 阿滴"
"百靈果之友: 002@呱吉" = "百靈果之友: 002 呱吉"
"百靈果之友: 003@ " = "百靈果之友: 003 "
"百靈果之友: 004@ " = "百靈果之友: 004 "
"讀書會：同情者 CH 2 越戰美國大兵有嚴重的用藥問題" = "越戰美國大兵有嚴重的用藥問題、讀書會：同情者 CH 2"
