# 聽眾

[Xin]
inclusive = ["Xin"]
exclusive = []
category = ["聽眾"]

[JC]
inclusive = ["JC"]
exclusive = []
category = ["聽眾"]

[Vasilisa]
inclusive = ["Vasilisa"]
exclusive = []
category = ["聽眾"]

[Angeli]
inclusive = ["Angeli"]
exclusive = []
category = ["聽眾"]

[Angel]
inclusive = ["Angel"]
exclusive = ["Angeli"]
category = ["聽眾"]

[Feyza]
inclusive = ["Feyza"]
exclusive = []
category = ["聽眾"]

[V]
inclusive = ["維吾爾的故事 - V"]
exclusive = []
category = ["聽眾"]

[Catherine]
inclusive = ["Catherine"]
exclusive = []
category = ["聽眾"]

# 其他

[Howard]
inclusive = ["Howard"]
exclusive = []
category = ["朋友","Podcaster","專業人士","口譯員"]

[Ivan]
inclusive = ["Ivan"]
exclusive = []
category = ["朋友"]

["Shao Yong"]
inclusive = ["Shao Yong"]
exclusive = []
category = ["朋友","專業人士","健身","教練","運動"]

["趙哥"]
inclusive = ["趙哥"]
exclusive = []
category = ["朋友"]

[Lesley]
inclusive = ["Lesley"]
exclusive = []
category = ["專業人士"]

["Aaron"]
inclusive = ["Aaron"]
exclusive = []
category = ["老闆"]

["尚恩"]
inclusive = ["尚恩"]
exclusive = []
category = ["老闆"]

["李小牧"]
inclusive = ["李小牧"]
exclusive = []
category = ["老闆"]

["Anton @僑昱建築"]
inclusive = ["Anton"]
exclusive = []
category = ["老闆"]

["陳沂"]
inclusive = ["陳沂"]
exclusive = []
category = ["朋友","藝人"]

["楊杰凱"]
inclusive = ["楊杰凱"]
exclusive = []
category = ["專業人士","專利師"]

["黑嘉嘉"]
inclusive = ["黑嘉嘉"]
exclusive = []
category = ["專業人士"]

["曹興誠"]
inclusive = ["曹興誠"]
exclusive = []
category = ["老闆"]

[Jay]
inclusive = ["Netflix - Jay"]
exclusive = []
category = ["老闆"]

["Jay哥"]
inclusive = ["Jay哥"]
exclusive = []
category = ["老闆"]

["吳桑"]
inclusive = ["吳桑"]
exclusive = []
category = ["老闆"]

["Nick（前小紅書工程師）"]
inclusive = ["小紅書演算法工程師 - Nick"]
exclusive = []
category = ["專業人士","工程師"]

["顧立楷"]
inclusive = ["顧立楷"]
exclusive = []
category = ["老闆"]

["林榮基"]
inclusive = ["林榮基"]
exclusive = []
category = ["老闆"]

[Neil]
inclusive = ["Neil"]
exclusive = []
category = ["編輯"]

["美國台灣觀測站"]
inclusive = ["美國台灣觀測站"]
exclusive = []
category = ["時事"]

[IORG]
inclusive = ["IORG"]
exclusive = []
category = ["時事","事實查核"]

["可心"]
inclusive = ["可心","IORG"]
exclusive = []
category = ["時事","事實查核"]

["咪咪"]
inclusive = ["咪咪"]
exclusive = []
category = ["時事","事實查核"]

["雕大 @IEObserve"]
inclusive = ["IEObserve"]
exclusive = []
category = ["時事"]

["徐瑜 @陳綢兒少家園"]
inclusive = ["徐瑜"]
exclusive = []
category = ["時事"]

["士杰"]
inclusive = ["士杰"]
exclusive = []
category = ["時事"]

["沈伯洋（助理）教授"]
inclusive = ["沈伯洋"]
exclusive = []
category = ["時事","事實查核","學者"]

["劉必榮教授"]
inclusive = ["劉必榮"]
exclusive = []
category = ["時事","學者"]

["馮建三教授"]
inclusive = ["馮建三"]
exclusive = []
category = ["時事","學者"]

["張五岳"]
inclusive = ["張五岳"]
exclusive = []
category = ["時事"]

["Luke Martin"]
inclusive = ["Luke Martin"]
exclusive = []
category = ["時事"]

["東冬侯溫"]
inclusive = ["東冬侯溫"]
exclusive = []
category = ["原住民"]

["Pom 咩"]
inclusive = ["Pom咩"]
exclusive = []
category = ["百靈果親屬"]

[Wolf]
inclusive = ["Wolf"]
exclusive = []
category = ["來賓"]

["中國體制內的第二代"]
inclusive = ["中國體制內的第二代"]
exclusive = []
category = ["來賓"]

["沈棟"]
inclusive = ["沈棟"]
exclusive = []
category = ["來賓"]

["Tony"]
inclusive = ["軍火 - Tony"]
exclusive = []
category = ["來賓"]

[Edan]
inclusive = ["Edan"]
exclusive = []
category = ["來賓"]

["雞哥"]
inclusive = ["雞哥"]
exclusive = []
category = ["來賓"]

["小飛"]
inclusive = ["小飛"]
exclusive = []
category = ["來賓"]
