# 讀書會

["王子習近平"]
inclusive = ["王子習近平"]
exclusive = []
category = ["讀書會"]

["Hot Money"]
inclusive = ["讀書會Hot Money"]
exclusive = []
category = ["讀書會"]

["八尺門的辯護人"]
inclusive = ["八尺門的辯護人"]
exclusive = []
category = ["讀書會"]

["同情者"]
inclusive = ["同情者"]
exclusive = []
category = ["讀書會"]

["柏青哥"]
inclusive = ["柏青哥"]
exclusive = []
category = ["讀書會"]

["Fat Leonard"]
inclusive = ["Fat Leonard"]
exclusive = ["推薦Podcast"]
category = ["讀書會"]

["林獻堂環球遊記"]
inclusive = ["環球遊記","林獻堂環球遊記"]
exclusive = []
category = ["讀書會"]

["吃佛"]
inclusive = ["吃佛","Eat The Buddha"]
exclusive = ["推薦書"]
category = ["讀書會"]

["宮前町九十番"]
inclusive = ["宮前町九十番"]
exclusive = []
category = ["讀書會"]

["CIA洗腦計畫"]
inclusive = ["讀書會：CIA洗腦計劃","讀書會：CIA的洗腦計劃","讀書會： CIA 洗腦計劃","讀書會：CIA洗腦計畫"]
exclusive = []
category = ["讀書會"]

["蚵仔煎的身世"]
inclusive = ["蚵仔煎的身世"]
exclusive = []
category = ["讀書會"]

["傀儡花"]
inclusive = ["讀書會：傀儡花"]
exclusive = []
category = ["讀書會"]

["毒家企業"]
inclusive = ["讀書會：毒家企業","讀書會： Narconomics"]
exclusive = []
category = ["讀書會"]

["宋氏三姊妹"]
inclusive = ["讀書會 宋氏三姐妹","讀書會：宋氏三姐妹","讀書會：宋氏三姐妹","讀書會：宋氏三姊妹"]
exclusive = []
category = ["讀書會"]

["T.R.W.I.H. by John Bolton"]
inclusive = ["The Room Where It Happened by John Bolton"]
exclusive = []
category = ["讀書會"]

["Rage by Bob Woodward"]
inclusive = ["Rage by Bob Woodward"]
exclusive = []
category = ["讀書會"]

["浪淘沙"]
inclusive = ["讀書會：浪淘沙"]
exclusive = []
category = ["讀書會"]

["戰裡的夏里特"]
inclusive = ["Charité at War｜戰裡的夏里特"]
exclusive = []
category = ["讀書會"]

["鴻：三代中國女人"]
inclusive = ["鴻：三代中國女人"]
exclusive = []
category = ["讀書會"]

["This American Life"]
inclusive = ["This American Life - Ten Sessions"]
exclusive = []
category = ["讀書會"]

["核爆家園"]
inclusive = ["Chernobyl 核爆家園"]
exclusive = []
category = ["讀書會"]

["陳澄波密碼"]
inclusive = ["讀書會：陳澄波密碼"]
exclusive = []
category = ["讀書會"]

["以母之名"]
inclusive = ["Born a crime 以母之名"]
exclusive = []
category = ["讀書會"]
