name: Update podcast content and deploy static content to Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Initial:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove klolt_docs.7z
        run: |
          touch /mnt/sd3/record/klolt_docs.7z
          rm -v /mnt/sd3/record/klolt_docs.7z
      - name: Prepare klolt_docs.7z
        run: |
          7z a -mx0 -aoa -r /mnt/sd3/record/klolt_docs.7z /mnt/sd3/record/klo.lt/docs
      - name: Pull klolt_docs.7z
        run: |
          rsync -P /mnt/sd3/record/klolt_docs.7z ./
      - name: Extract klolt_docs.7z
        run: |
          7z x ./klolt_docs.7z
          rm -v ./klolt_docs.7z
      - name: Pull records
        run: |
          rsync -Prc /mnt/sd3/record/klo.lt/record/08c/record ./record/08c/
          rsync -Prc /mnt/sd3/record/klo.lt/record/asc/record ./record/asc/
          rsync -Prc /mnt/sd3/record/klo.lt/record/ays/record ./record/ays/
          rsync -Prc /mnt/sd3/record/klo.lt/record/blg/record ./record/blg/
          rsync -Prc /mnt/sd3/record/klo.lt/record/bts/record ./record/bts/
          rsync -Prc /mnt/sd3/record/klo.lt/record/ct4/record ./record/ct4/
          rsync -Prc /mnt/sd3/record/klo.lt/record/exr/record ./record/exr/
          rsync -Prc /mnt/sd3/record/klo.lt/record/fcf/record ./record/fcf/
          rsync -Prc /mnt/sd3/record/klo.lt/record/fnf/record ./record/fnf/
          rsync -Prc /mnt/sd3/record/klo.lt/record/hsd/record ./record/hsd/
          rsync -Prc /mnt/sd3/record/klo.lt/record/inf/record ./record/inf/
          rsync -Prc /mnt/sd3/record/klo.lt/record/jst/record ./record/jst/
          rsync -Prc /mnt/sd3/record/klo.lt/record/nkw/record ./record/nkw/
          rsync -Prc /mnt/sd3/record/klo.lt/record/plr/record ./record/plr/
          rsync -Prc /mnt/sd3/record/klo.lt/record/pws/record ./record/pws/
          rsync -Prc /mnt/sd3/record/klo.lt/record/stp/record ./record/stp/
          rsync -Prc /mnt/sd3/record/klo.lt/record/tts/record ./record/tts/
          rsync -Prc /mnt/sd3/record/klo.lt/record/twc/record ./record/twc/
          rsync -Prc /mnt/sd3/record/klo.lt/record/wbr/record ./record/wbr/
      - name: record
        run: |
          rsync -Prc ./static_files/* ./docs/
      - name: check py requirements
        run: |
          pip3 install -r requirements.txt
      - name: Update rss - prepare Spotify
        env:
          SPT_ID: ${{ secrets.spotify_client_id }}
          SPT_SC: ${{ secrets.spotify_client_secret }}
        run: |
          python3 secret.py --spotify_id "$SPT_ID" --spotify_secret "$SPT_SC"
  Update:
    needs: Initial
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Update rss - update 08C
        run: |
          python3 update.py 08c
          sleep 6
      - name: Update rss - update ASC
        run: |
          python3 update.py asc
          sleep 7
      - name: Update rss - update AYS
        run: |
          python3 update.py ays
          sleep 5
      - name: Update rss - update BLG
        run: |
          python3 update.py blg
          sleep 10
      - name: Update rss - update bts
        run: |
          python3 update.py bts
          sleep 8
      - name: Update rss - update ct4
        run: |
          python3 update.py ct4
          sleep 10
      - name: Update rss - update EXR
        run: |
          python3 update.py exr
          sleep 8
      - name: Update rss - update fcf
        run: |
          python3 update.py fcf
          sleep 7
      - name: Update rss - update fnf
        run: |
          python3 update.py fnf
          sleep 6
      - name: Update rss - update hsd
        run: |
          python3 update.py hsd
          sleep 8
      - name: Update rss - update inf
        run: |
          python3 update.py inf
          sleep 9
      - name: Update rss - update JST
        run: |
          python3 update.py jst
          sleep 9
      - name: Update rss - update nkw
        run: |
          python3 update.py nkw
          sleep 8
      - name: Update rss - update plr
        run: |
          python3 update.py plr
          sleep 7
      - name: Update rss - update pws
        run: |
          python3 update.py pws
          sleep 10
      - name: Update rss - update stp
        run: |
          python3 update.py stp
          sleep 10
      - name: Update rss - update tts
        run: |
          python3 update.py tts
          sleep 7
      - name: Update rss - update twc
        run: |
          python3 update.py twc
          sleep 6
      - name: Update rss - update wbr
        run: |
          python3 update.py wbr
          sleep 6
      - name: Merge feed source
        run: |
          python3 merge.py 08c
          python3 merge.py asc
          python3 merge.py ays
          python3 merge.py blg
          python3 merge.py bts
          python3 merge.py ct4
          python3 merge.py exr
          python3 merge.py fcf
          python3 merge.py fnf
          python3 merge.py hsd
          python3 merge.py inf
          python3 merge.py jst
          python3 merge.py nkw
          python3 merge.py plr
          python3 merge.py pws
          python3 merge.py stp
          python3 merge.py tts
          python3 merge.py twc
          python3 merge.py wbr
      - name: Annotate feed with various info
        run: |
          python3 annotate.py 08c > record/08c/filter.txt
          python3 annotate.py asc > record/asc/filter.txt
          python3 annotate.py ays > record/ays/filter.txt
          python3 annotate.py blg > record/blg/filter.txt
          python3 annotate.py bts > record/bts/filter.txt
          python3 annotate.py ct4 > record/ct4/filter.txt
          python3 annotate.py exr > record/exr/filter.txt
          python3 annotate.py fcf > record/fcf/filter.txt
          python3 annotate.py fnf > record/fnf/filter.txt
          python3 annotate.py hsd > record/hsd/filter.txt
          python3 annotate.py inf > record/inf/filter.txt
          python3 annotate.py jst > record/jst/filter.txt
          python3 annotate.py nkw > record/nkw/filter.txt
          python3 annotate.py plr > record/plr/filter.txt
          python3 annotate.py pws > record/pws/filter.txt
          python3 annotate.py stp > record/stp/filter.txt
          python3 annotate.py tts > record/tts/filter.txt
          python3 annotate.py twc > record/twc/filter.txt
          python3 annotate.py wbr > record/wbr/filter.txt
      - name: Export feed into js file
        run: |
          touch docs/klt-playlist.json
          touch docs/klt-tag_class.json
          touch docs/klt-class_tag.json
          rm -v docs/klt-playlist.json docs/klt-tag_class.json docs/klt-class_tag.json
          python3 export.py 08c `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py asc `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py ays `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py blg `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py bts `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py ct4 `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py exr `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py fcf `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py fnf `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py hsd `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py inf `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py jst `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py nkw `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py plr `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py pws `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py stp `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py tts `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py twc `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
          python3 export.py wbr `TZ='<UTC+8>-8' date +'d%y%m%dt%H%M'`
  Deploy:
    needs: Update
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Setup git config
        env:
          EMAIL: ${{ secrets.email }}
          KEY: ${{ secrets.key }}
        run: |
          git config user.name "RSS Update Bot"
          git config user.email "$EMAIL"
          git config user.signingkey "$KEY"
      - name: Check git status
        id: check_git_status
        run: |
          echo "git_status="`git status --porcelain`
          echo "git_status="`git status --porcelain` >> $GITHUB_OUTPUT
      - name: Commit updates
        if: ${{ steps.check_git_status.outputs.git_status != '' }}
        run: |
          echo git_status: ${{ steps.check_git_status.outputs.git_status }}
          git add -A
          git commit -S -m "___ RSS FEED UPDATE "`TZ='<UTC+8>-8' date +'%b_%d,_%Y_%H:%M:%S'`" #bot_action"
          git push https://${{ secrets.PAT }}@github.com/SotongDJ/klo.lt.git
      - name: Echo status
        run: |
          echo ${{ needs.build.outputs.git_status }}
      - name: Save changes
        run: |
          rsync -Prc ./docs /mnt/sd3/record/klo.lt/
          rsync -Prc ./record/08c/record /mnt/sd3/record/klo.lt/record/08c/
          rsync -Prc ./record/asc/record /mnt/sd3/record/klo.lt/record/asc/
          rsync -Prc ./record/ays/record /mnt/sd3/record/klo.lt/record/ays/
          rsync -Prc ./record/blg/record /mnt/sd3/record/klo.lt/record/blg/
          rsync -Prc ./record/bts/record /mnt/sd3/record/klo.lt/record/bts/
          rsync -Prc ./record/ct4/record /mnt/sd3/record/klo.lt/record/ct4/
          rsync -Prc ./record/exr/record /mnt/sd3/record/klo.lt/record/exr/
          rsync -Prc ./record/fcf/record /mnt/sd3/record/klo.lt/record/fcf/
          rsync -Prc ./record/fnf/record /mnt/sd3/record/klo.lt/record/fnf/
          rsync -Prc ./record/hsd/record /mnt/sd3/record/klo.lt/record/hsd/
          rsync -Prc ./record/inf/record /mnt/sd3/record/klo.lt/record/inf/
          rsync -Prc ./record/jst/record /mnt/sd3/record/klo.lt/record/jst/
          rsync -Prc ./record/nkw/record /mnt/sd3/record/klo.lt/record/nkw/
          rsync -Prc ./record/plr/record /mnt/sd3/record/klo.lt/record/plr/
          rsync -Prc ./record/pws/record /mnt/sd3/record/klo.lt/record/pws/
          rsync -Prc ./record/stp/record /mnt/sd3/record/klo.lt/record/stp/
          rsync -Prc ./record/tts/record /mnt/sd3/record/klo.lt/record/tts/
          rsync -Prc ./record/twc/record /mnt/sd3/record/klo.lt/record/twc/
          rsync -Prc ./record/wbr/record /mnt/sd3/record/klo.lt/record/wbr/
      - name: Backup changes
        run: |
          if [ ! -f `TZ='<UTC+8>-8' date +'/mnt/sd3/record/backup/klolt-%b%d_%Y.7z'` ]; then
              echo "Creating baseline archive: "`TZ='<UTC+8>-8' date +'/mnt/sd3/record/backup/klolt-%b%d_%Y.7z'`
              7z a -r `TZ='<UTC+8>-8' date +'/mnt/sd3/record/backup/klolt-%b%d_%Y.7z'` /mnt/sd3/record/klo.lt
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
