name: Deploy static content to Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Remove klolt_docs.7z
      #   run: |
      #     touch /mnt/sd3/record/klolt_docs.7z
      #     rm -v /mnt/sd3/record/klolt_docs.7z
      # - name: Prepare klolt_docs.7z
      #   run: |
      #     7z a -mx0 -aoa -r /mnt/sd3/record/klolt_docs.7z /mnt/sd3/record/klo.lt/docs
      # - name: Pull klolt_docs.7z
      #   run: |
      #     rsync -P /mnt/sd3/record/klolt_docs.7z ./
      # - name: Extract klolt_docs.7z
      #   run: |
      #     7z x ./klolt_docs.7z
      #     rm -v ./klolt_docs.7z
      - name: Pull update
        run: |
          rsync -Pr /mnt/sd3/record/klo.lt/docs ./
      - name: Deploy statics
        run: |
          rsync -Prc ./static_files/* ./docs/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
